### ISSUE TITLE
Remove redundant relationships

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#10]
In OLS uberon, 'phalanx' is show with a direct child 'manual digit 1 phalanx'.

In fact in the (pre-reasoned) released version of uberon, there are two SubClassOf axioms for 'manual digit 1 phalanx' with a named superclass:

    SubClassOf: 'phalanx of manus'
    SubClassOf: 'manual digit 1 phalanx endochondral element'

(ie there is an intermediate class)

And an equivalence axiom to

    'phalanx' and part_of some 'manual digit 1'

I believe that OLS may be showing 'relaxed' superclass axioms from the equivalence axiom (see https://github.com/ontodev/robot/issues/7). This is a safe thing to do, because some ontology release pipelines do not perform a relaxation step (or they may relax and then remove trivial inferences, or indeed they may omit any kind of pre-reasoning).

However, if relaxing is performed, then redundancy removals should be performed after the fact, or the algorithm should be only to relax if it does not produce a redundancy. 

It turns out that the specification of the right kind of behavior for an ontology release tool to produce optimal behavior in all browsers is a bit verbose. Some discussion here, comments welcome: https://github.com/ontodev/robot/issues/16

I understand for OLS you don't do any reasoning, so there are certain expectations about ontology structure? Are these stated?

**Comment by simonjupp** [comment]
OLS is set up to use a reasoner to build the index, but I use the OWL structural reasoner for OBO ontologies because I'm assuming that any is-a redundancy has been removed. The other motivation for doing this was that I had problems building the index with using ELK over some the big ontologies (NCBI taxon and Gaz). 

I think I can fix this by reverting back to ELK by default for OBO, and having something in our config where I forces NCBI, Gaz and any other big ones to use the structural reasoner. I'll experiment with loading uberon and classifying and see how it looks in OLS.

**Comment by cmungall** [comment]
On 1 Oct 2015, at 2:22, simonjupp wrote:

> OLS is set up to use a reasoner to build the index, but I use the OWL 
> structural reasoner for OBO ontologies because I'm assuming that any 
> is-a redundancy has been removed.

It depends how you define removal of is-a redundancy

In most cases, it should have been done, and it has been done in uberon

the issue is that the equivalence axiom is not redundant in terms of EL, 
but it is redundant when you consider *only* the subclass hierarchy. For 
uberon, strict subclass redundancy has been eliminated, but equivalence 
axioms are still retained, which creates visual redundancy when the 
structure reasoner considers the union of subclass and equivalence 
axioms

> The other motivation for doing this was that I had problems building 
> the index with using ELK over some the big ontologies (NCBI taxon and 
> Gaz).
>
> I think I can fix this by reverting back to ELK by default for OBO, 
> and having something in our config where I forces NCBI, Gaz and any 
> other big ones to use the structural reasoner. I'll experiment with 
> loading uberon and classifying and see how it looks in OLS.

Seems a bit fragile but if it works…

Might be easier to implement the desired redundancy removal as a layer 
on top of the reasoning step

**Comment by simonjupp** [comment]
You are right, the structural owl reasoner is pulling in parent classes from the equivalence axioms. I didn't realise it would do that. I reloaded uberon and built the index with elk and the redundancy was gone. 

I'm happy to change the OBO loader to default to ELK. We have some additional config that we need for all the ontologies anyway, so adding a flag for ncbi and gaz to say don't classify is not a big deal.

**Comment by cmungall** [comment]
is this something that has to be configured on a per-ontology basis?

this shows up under 'disease'

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0017820

yet:

```
curl -s -L http://purl.obolibrary.org/obo/mondo.obo | grep -A20 '^id: MONDO:0017820'
id: MONDO:0017820
name: disease with Cushing syndrome as a major feature
def: "A disease in which Cushing syndrome is a major feature." [MONDO:DesignPattern]
subset: ordo_group_of_disorders {source="Orphanet:314749"}
synonym: "rare disease with Cushing syndrome as a major feature" EXACT [Orphanet:314749]
xref: Orphanet:314749 {source="MONDO:Leader", source="MONDO:equivalentTo"}
is_a: MONDO:0018912 {source="Orphanet:314749"} ! Cushing syndrome
intersection_of: MONDO:0000001 ! disease
intersection_of: disease_has_major_feature MONDO:0018912 ! Cushing syndrome
relationship: disease_has_major_feature MONDO:0018912 ! Cushing syndrome
property_value: exactMatch Orphanet:314749
```

**Comment by simonjupp** [comment]
I set mondo to use the structural reasoner back when we were loading the full version and it was causing problems for our indexer. Now we have the simple version I can probably switch this back to default (ELK). I'll give it a go.
