### ISSUE TITLE
OLS is not reachable

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#106]
I am getting a 404 by tomcat on OLS.
Webservices are also down.

via
http://www.ebi.ac.uk/ols/index
and the java library

**Comment by simonjupp** [comment]
Thanks. There have been some issues effecting a lot of EBI service today. It's back now, I'll look into why the failover didn't kick in tomorrow.

**Comment by matthiaskoenig** [comment]
perfect. thanks
