### ISSUE TITLE
Update SBO ontology

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#107]
There are some new terms in SBO which are not available via OLS.
See for instance
http://www.ebi.ac.uk/sbo/main/SBO:0000627
vs
http://www.ebi.ac.uk/ols/api/ontologies/SBO/terms?obo_id=SBO:0000627

**Comment by simonjupp** [comment]
This is an issue with the PURL pointing to an old version of the ontology, I've informed the OBO library maintainers.

**Comment by simonjupp** [comment]
This has now been updated,

**Comment by matthiaskoenig** [comment]
Thanks a lot.
