### ISSUE TITLE
Clipboard button doesn't copy to clipboard, it only highlights

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#109]
Surprising behaviour for a 'copy to clipboard' button, which doesn't copy to the clipboard but only highlights the URI, and still requires Ctrl-C afterwards.

**Comment by LLTommy** [comment]
Hi there! 
I am pretty sure you are using safari? Is that correct? I tested it with other browsers and it works fine - Safari does not support to copy something directly - (that is what the developers of the library  that we use say) - so highlighting is the best we can do for now.

**Comment by mcourtot** [comment]
Thanks @LLTommy! I just checked with chrome and it does work as expected indeed. Closing this ticket as Won't fix.
