### ISSUE TITLE
OLS does not handle non-isa-complete ontologies well

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#11]
E.g. try 'ileum mucosa' in MA

Not necessarily OLS' fault. Just a clash of implicit assumptions, between obo-edit developed ontologies and Protege developed ontologies.

This may be subsumed into a general ticket about displaying partonomies. For many AOs the partonomy is more important than the subclass hierarchy (for an extreme example, see EMAP)

**Comment by simonjupp** [comment]
I'm hoping a path to root graph visualisation we are working on will appease most users. I'm still against putting relations in trees if we can avoid it. Works ok for MA, but I tried to have a look at generating a tree with isa + part of for uberon on go and for some terms the poly hierarchy tree view is insane.

**Comment by cmungall** [comment]
Right, but looking at an anatomy ontology without partonomy doesn't make any sense (unless it's FMA which recapitulates the majority of its partonomy via named classes, in a semi-snomed-SEP pattern). Same for GO BP. The view will be view at best incomplete, possibly misleading.

The blame could be laid squarely at the feet of the whole all-paths-to-root view (which even with isa still explodes). Have you looked at the lineage tab in AmiGO?

http://amigo.geneontology.org/amigo/term/GO:0002516#display-lineage-tab
http://amigo.geneontology.org/amigo/term/GO:2000820#display-lineage-tab

Can be confusing at first but a lot of the GO people really like it once they understand it. It scales well for mixing in a number of OPs (but they have to be restricted to intuitive traversal-type OPs. Throwing in has-part will anger people). I believe you may generate some of the js format required for this widget. cc @kltm 

It would be nice if users could switch between is-a and an OP like part-of. However, showing an only part-of view naively will result in broken trees as not every class has an explicit part-of axiom. I've written command line ascii tree viewers using
https://github.com/owlcollab/expression-materializing-reasoner/
cc @hdietze 

For purely subclass views over very latticey ontologies, what I have always wanted is a toggle that can dynamically switch the axis of classification. This could be a nested thing. For example, in the GO biochemical branch, if I could switch between seeing a process-level distinction (e.g. on the genus) vs chemical (possibly showing the base chemical hierarchy to the side). Maybe even switching deeper - based on classification in CHEBI - is it structural, or role based? (although CHEBI is not axiomatized enough for this, would work better with anatomy). Basically showing all paths through a lattice that has been derived Rector-style from two trees is just not helpful, we need to figure out a way that deconstructs the lattice shows people where they are in the trees. cc @dosumis

(sorry, should be separate ticket)

**Comment by simonjupp** [comment]
I've added support for partonomies now (not live yet). The trees have exploded a bit, but the anatomy ontologies do look a lot better for it. 

It took me a while to understand the amigo view but I think it's quite neat. Am I right in thinking that this is precomputed when you build the amigo indexes? 

Next challenge of course is which part of?

http://www.ebi.ac.uk/ols/beta/search?q=part+of&start=0&type=property&groupField=iri&exact=on

We already have 14 in OLS! I 'm adding some config to support all of these. We have a property field called hierarchical_property that takes a list of OPs that should be used in the tree view. If you added this to the OBO yaml spec then we could pick that up from source. 

Haven't added support for 'develops from' yet. Is there any ontology that will be severely effected by this? for now?

I also like the idea of having something that's a bit more dynamic, where you can toggle in relations as you want. I think this will be doable with the infrastructure we have, we just need some bandwidth to work on the UI components. We have someone who has just started who is going to be looking into this.

**Comment by dosumis** [comment]
All of those po relations from obo ontologies should be resolving to
BFO_0000050 in OWL.  Simple change to OBO will force this in conversion.

**Comment by cmungall** [comment]
Hmm MA used to have it.. vanished

**Comment by cmungall** [comment]
On 6 Oct 2015, at 3:09, simonjupp wrote:

> I've added support for partonomies now (not live yet). The trees have 
> exploded a bit, but the anatomy ontologies do look a lot better for 
> it.
>
> It took me a while to understand the amigo view but I think it's quite 
> neat. Am I right in thinking that this is precomputed when you build 
> the amigo indexes?

The JSON objects are pre-computed but I believe the layout is 
dynamically calculated. @kltm

>
> Next challenge of course is which part of?
>
> http://www.ebi.ac.uk/ols/beta/search?q=part+of&start=0&type=property&groupField=iri&exact=on
>
> We already have 14 in OLS! I 'm adding some config to support all of 
> these. We have a property field called hierarchical_property that 
> takes a list of OPs that should be used in the tree view. If you added 
> this to the OBO yaml spec then we could pick that up from source.
>
> Haven't added support for 'develops from' yet. Is there any ontology 
> that will be severely effected by this? for now?

None will be severely affects. It's very useful to have for most anatomy 
ontologies, but omitting it is not severe the way omitting part-of is

> I also like the idea of having something that's a bit more dynamic, 
> where you can toggle in relations as you want. I think this will be 
> doable with the infrastructure we have, we just need some bandwidth to 
> work on the UI components. We have someone who has just started who is 
> going to be looking into this.

ok, great.
