### ISSUE TITLE
show/hide siblings

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#110]
Hi,

Not really a bug, more of a question regarding the default behaviour of OLS. When looking for a term, e.g. "structural variant" in SO, http://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0001537, by default when the page opens the term is hanging there alone. It took me a little while to figure out that I could click on 'show siblings' to view the term in context. I think most users would expect the opposite, i.e. when opening the page you have more details and you can then decide to hide information. 

Similarly, when looking at the same page http://www.ebi.ac.uk/ols/ontologies/so/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSO_0001537, if I close the tree by clicking on the box next to the parent term 'sequence_variant', and open it again, I would expect the whole hierarchy to show up.

Finally, the page with the siblings showing can't be linked to, so sharing the full view with colleagues is not easily feasible - maybe a parameter could be passed in the URL?

Again, not bugs, but behaviours that I found odd.

Thanks,
Melanie

**Comment by simonjupp** [comment]
I think there are also cases where showing the full tree by default is too much. I've seen cases where the term the page is about gets hidden deep down in the page if you expand all siblings by default. Click show siblings on http://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0016182 for an example of what I mean. 

I'm thinking to add some more tree view options, like expand direct vs expand all siblings. I also think a collapsed tree, more like what AmiGO has is also useful when you have terms with multiple classifications. 

We can fix the close/open parent term issue, I agree this should show all children when reopened. I'll also add support for linking to an expanded view.

**Comment by mcourtot** [comment]
Sounds all great. I agree wrt to 'too much' when multiple parentage. An option like in Protege where you can either open the branch you're clicking on or expand the whole tree maybe? Though that may be overloading the UI. Thanks for the feedback!
