### ISSUE TITLE
FAQ typos

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#111]
How does OLS handle OWL imports?
OWL imports are respects so any impoprted files will be indexes as part of the ontology. 

I'm also not sure saying 'OWL imports are respected' is the best way to phrase this. Maybe something like  'Resources imported via `owl:imports` statements will be indexed as part of the ontology that imports them.' ?

**Comment by simonjupp** [comment]
I'd already  edited that in the dev branch a few weeks ago. Just pushed the changes now, will be live on next release.
