### ISSUE TITLE
When I click on a leaf the rest of the tree disappears ....

### ISSUE THREAD

**Issue by joncison** [EBISPOT/OLS#113]
Hi @simonjupp 

Once I click on a leaf, the rest of the tree disappears with no way back (other than clicking "Back" in the browser,  but that takes me back to the top).   Is this intentional or am I doing something wrong?  I find browsing hard going this way ...

Cheers

**Comment by LLTommy** [comment]
Hi there,
yes, once you click on a leaf in the tree, all the information on the page is updated including the tree. This is how it works at the moment and you don't do anything wrong. We are aware that this behaviour sometimes is a bit awkward, the reason for it I'd label as internal technical reasons. I don't know if we have the time to change that anytime soon, so for the moment, you have to live with it I am afraid.

**Comment by joncison** [comment]
OK, but I'd urge you to take a look at this please, because for me, it severely compromises the usability.  I'd say I can't really use the widget to navigate the tree.  I'd like to have the EDAM URIs to resolve to OLS but this issue is a show stopper.  In many other aspects OLS rocks! Keep up the good work!

**Comment by simonjupp** [comment]
Hi Jon. I agree with you that when you are in "browse around mode", this can be a bit frustrating.  I also think it's important that when you focus on a term you see the full classification (see this EFO example for a term with multiple classification http://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002107). In click around mode, this view would be lost without forcing the tree to reload. 

Either way, I agree that this is not optimal and I have some ideas on how we might improve this. We'll keep you posted.

**Comment by joncison** [comment]
I agree, seeing the full classification is awesome.  My feeling, though, is that we may not be able to have our cake and eat it, in a single UI paradigm.  So is their merit in the idea of having two distinct browse modes : 1) "browse around" and 2) "Details" (or whatever) ?

**Comment by simonjupp** [comment]
Looks like we could support an option to lock the tree, so state is saved between page refreshes. It already does that to support the back button, we just need to enable it for clicking new terms. Then we can add a button that forces the tree to refocus if you want it.

**Comment by joncison** [comment]
Cool, just ping me if you want me to take a look.
