### ISSUE TITLE
Error1s in  PORO

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#118]
There are some roots that are Error1
http://www.ebi.ac.uk/ols/ontologies/poro

My hypothesis is that github flaked when serving one of the imports, served back error HTML which the OWLAPI tried to read as OWL...?

But that still doesn't make sense, compare

http://www.ebi.ac.uk/ols/ontologies/poro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPORO_0000189

with 

http://www.ontobee.org/ontology/PORO?iri=http://purl.obolibrary.org/obo/PORO_0000189

**Comment by simonjupp** [comment]
Yes, this "Error" label comes from the OWL API. These come from the general class axioms that reference _:genid887 and _:genid888 in the master file. 

    <owl:Restriction>
        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000466"/>
        <rdfs:subClassOf rdf:nodeID="_:genid887"/>
    </owl:Restriction>
    <owl:Restriction>
        <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
        <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0001062"/>
        <rdfs:subClassOf rdf:nodeID="_:genid888"/>
    </owl:Restriction>

![screenshot 2016-10-06 16 33 54](https://cloud.githubusercontent.com/assets/385021/19159043/e25a461c-8be2-11e6-9b4a-1f0ad4ac17e9.jpeg)

**Comment by cmungall** [comment]
Oh, so it is PORO's fault after all. Sorry, I thought I checked the 
file. I have no idea how those got in there. You can close this ticket

**Comment by cmungall** [comment]
Turns out this is due to a rather interesting bug in the OWLAPI: https://github.com/owlcs/owlapi/issues/564

The sponge edit file is fine as it's functional syntax, the weirdness is generated when we make the RDF/XML for release. And as the OWLAPI is silent about these oddities it wasn't picked up til I saw it in OLS.

(oh, and I assumed it was an OLS issue as it didn't show up this way in OntoBee - but OntoBee is not being updated properly and has an old version of the sponge ontology)
