### ISSUE TITLE
subsets no longer returned by API?

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/OLS#119]
The annotation field used to contains a list of subsets, but no longer:

e.g. this term is in subset 'goslim_synapse': http://www.ebi.ac.uk/ols/api/ontologies/go/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0045202 

But:

  "annotation" : {
    "database_cross_reference" : [ "Wikipedia:Chemical_synapse", "NIF_Subcellular:sao914572699" ],
    "has_narrow_synonym" : [ "mixed synapse" ],
    "has_obo_namespace" : [ "cellular_component" ],
    "has_related_synonym" : [ "electrotonic synapse" ],
    "id" : [ "GO:0045202" ]
  },

API doc example still claims they are returned:

![image](https://cloud.githubusercontent.com/assets/112839/19486941/4f6a0778-9558-11e6-8319-ec4ea1ea43cc.png)

**Comment by dosumis** [comment]
Checked all other returned fields to see if this has been moved.  Don't see any sign of it.

**Comment by simonjupp** [comment]
Thanks. I'll push a fix for this shortly.
