### ISSUE TITLE
number 1 match is not displayed at number one

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/OLS#120]
![dorsalectodermprimodiumobsolete](https://cloud.githubusercontent.com/assets/10416372/19728898/111cc790-9b8d-11e6-8467-a6092b209602.png)

**Comment by simonjupp** [comment]
Hard to say which should score higher here. Given your search keywords, hits 1 and 3 both contain two of the keywords you search for. The 1st is scored higher because in that word two of the terms are next to each other. Might be able to tweak the scoring a bit to improve this.

**Comment by jmcmurry** [comment]
Are you sure, Simon? It looks like hit 3 is an exact label match on all three words in the right order. Hit 1 is an exact match but on only on two of the three words.

**Comment by jmcmurry** [comment]
ahhh; you're right. tricky

**Comment by siiraa** [comment]
biologically number 3 is the exact match, that's what i meant. is there a way to tweak the scoring for something like this?
