### ISSUE TITLE
Getting 404 on local instalation

### ISSUE THREAD

**Issue by EdiMel** [EBISPOT/OLS#123]
Hi

I'm trying to test a local OLS version, following http://www.ebi.ac.uk/ols/docs/installation-guide.  I'm getting 404 when I try to view a property on the web interface.  I think is related to this...  Is there a user forum or mailing list ? can someone give me a clue ? 

`31-Oct-2016 12:12:24.248 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource getResource(META-INF/resources/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.248 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     findResource(META-INF/resources/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.249 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     --> Resource not found, returning null
31-Oct-2016 12:12:24.249 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource   --> Resource not found, returning null
31-Oct-2016 12:12:24.249 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource getResource(resources/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.249 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     findResource(resources/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.250 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     --> Resource not found, returning null
31-Oct-2016 12:12:24.250 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource   --> Resource not found, returning null
31-Oct-2016 12:12:24.250 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource getResource(static/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.250 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     findResource(static/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.251 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     --> Resource not found, returning null
31-Oct-2016 12:12:24.251 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource   --> Resource not found, returning null
31-Oct-2016 12:12:24.251 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource getResource(public/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.251 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     findResource(public/ontologies/efo/img/ols-logo.jpg)
31-Oct-2016 12:12:24.251 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.findResource     --> Resource not found, returning null
31-Oct-2016 12:12:24.252 FINE [http-nio-8080-exec-7] org.apache.catalina.loader.WebappClassLoaderBase.getResource   --> Resource not found, returning null
`

**Comment by simonjupp** [comment]
Few things to check first
1. What OS are you using? 
2. Did you successfully mange to load some ontologies?
3. How are you running the application, directly from the jar or have you tried to deploy the war in a Tomcat instance?

**Comment by EdiMel** [comment]
Hi
1. Centos 6.x, openjdk 1.8
2. ols-config-importer and ols-indexer appears to be working fine
3. Tomcat instance 8.0.38

I did a quick check of 3.1.0.RELEASE and don't see this error.

**Comment by simonjupp** [comment]
So is the 3.1.0.RELEASE working as expected but building from a clean checkout of master not?
