### ISSUE TITLE
Can I update an ontology, please?

### ISSUE THREAD

**Issue by matuskalas** [EBISPOT/OLS#124]
Or are you guys responsible for updating ontologies within OLS?

In any case, it'll be awesome if OLS could update its version of the EDAM ontology to http://edamontology.org/EDAM_1.16.owl

Thanks a million for help!

**Comment by joncison** [comment]
mate - they pull it nightly from edamontology.org

**Comment by matuskalas** [comment]
Ah, that's really awesome! :+1:  I didn't know :-)
Sorry for the alarm then
