### ISSUE TITLE
Feature request: BioAssay Ontology

### ISSUE THREAD

**Issue by janelomax** [EBISPOT/OLS#125]
Hi Simon - any chance you could add BioAssay Ontology (BAO) to OLS? 

http://bioassayontology.org/

cheers

Jane

**Comment by simonjupp** [comment]
Yep, should be able to do that. I'll look into how it is distributed.

**Comment by simonjupp** [comment]
This is now loaded http://www.ebi.ac.uk/ols/ontologies/bao

**Comment by janelomax** [comment]
Awesome - perfect timing!
