### ISSUE TITLE
Open subtree issues?

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#128]
I went to http://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0050903, and clicked on the parent term "immortal human kidney-derived cell line cell" to try and see all subclasses of the term "immortal human kidney-derived cell line cell"

I am now here: http://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0000587, but clicking on the "+" sign next to it only opens/close the existing child term (CLO_0050903) - instead of opening/closing the whole list.

Note that by contrast accessing the page for "immortal human kidney-derived cell line cell" directly via the URL above, http://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0000587, allows for opening/closing of the whole list. Maybe some parameter/variable that should be cleared from the session?

**Comment by simonjupp** [comment]
Fixed
