### ISSUE TITLE
Deploying the app on local server not working

### ISSUE THREAD

**Issue by niklr** [EBISPOT/OLS#129]
First of all my setup looks like this:
- Ubuntu 14.04.3 LTS
- Java 1.8.0
- Maven 3.0.5
- Tomcat 7.0.52
- MongoDB 3.4.1
- Solr 5.2.1

I followed all steps of the installation guide (https://www.ebi.ac.uk/ols/docs/installation-guide) up to "Deploying the app on local server". Both WAR files (ols-boot.war and ols-web-3.1.0.RELEASE.war) have been copied to /var/lib/tomcat7/webapps/
After starting the tomcat7 service the applications (ols-boot and ols-web-3.1.0.RELEASE) are listed as expected in the tomcat manager. Unfortunately, trying to access the applications http://localhost:8080/ols-boot/ and http://localhost:8080/ols-web-3.1.0.RELEASE/ result in HTTP Status 404. Is there another way to check what went wrong other than the catalina log listed below?

According to the catalina logs the WAR deployment seems to be successful:
INFO: Starting service Catalina
Jan 07, 2017 11:52:21 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jan 07, 2017 11:52:21 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/manager.xml
Jan 07, 2017 11:52:22 AM org.apache.catalina.startup.HostConfig deployDescriptor
INFO: Deploying configuration descriptor /etc/tomcat7/Catalina/localhost/host-manager.xml
Jan 07, 2017 11:52:22 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ols-boot.war
Jan 07, 2017 11:52:46 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ols-web-3.1.0.RELEASE.war
Jan 07, 2017 11:52:59 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Jan 07, 2017 11:52:59 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Jan 07, 2017 11:52:59 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 37658 ms

**Comment by simonjupp** [comment]
Hi, 
First of all, you only need to install the ols-boot.war, deploying both might cause you problems. 

Can you confirm that you have a mongo and solr server running with some data loaded?

**Comment by niklr** [comment]
Thanks to https://github.com/MaastrichtUniversity/ols-docker I was able to deploy it. However, it seems the web service starts only if "./tomcat7 start" in "/etc/init.d/" is executed as root.
