### ISSUE TITLE
Title of the GO file changed to "Uberon Ontology Module for GO"

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#130]
As per https://github.com/geneontology/go-ontology/issues/12900#issuecomment-271288658 from @cmungall

Could you please advise? It seems the issue was fixed on our side but not overwritten in OLS.

**Comment by simonjupp** [comment]
OLS records if the ontology uses dc:title. In this case you used dc:title, and then you didn't but it's assuming you still are. I'll put a fix in.

**Comment by simonjupp** [comment]
Fixed
