### ISSUE TITLE
Orphanet PURLs not working

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#131]
This page http://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_2213

has this PURL:

http://www.orpha.net/ORDO/Orphanet_2213

Which just redirects to the OLS top page

**Comment by LLTommy** [comment]
The redirect is out of our control and I think Simon tried to tell them to stop this before ... without success it seems.

**Comment by simonjupp** [comment]
The uri redirect was to the old ols. We started forwarding old ols urls to the new but it doesn't work for ordo as it was previously named Orphanet. I can put in a temporary fix for this, and I'll ping Marc again about getting this updated.

**Comment by simonjupp** [comment]
waiting for action from @Orphanet

**Comment by Orphanet** [comment]
The URL rewriting is made at our INSERM IT department level. The new one will be 
http://www.orpha.net/ORDO/Orphanet_XXX=> http://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_XXX

**Comment by simonjupp** [comment]
Great thanks!
