### ISSUE TITLE
Import SKOS

### ISSUE THREAD

**Issue by d0rg0ld** [EBISPOT/OLS#132]
Hi there,

I found some code snippets related to the import of SKOS thesauri in the source code (ontology-tools, etc.) and therefore was wondering if this was indeed possible but not documented, or currently not working at all. The code suggests that the latter is the case but it would be great to get some more information about it, if possible.

Thanks and best regards,
Doron

**Comment by simonjupp** [comment]
Hi Doron, 
It's not yet possible but is something I thought about and would be relatively straightforward to support. It would require an implementation of the OntologyLoader.java interface, I already have a Java API to SKOS that would help with this https://github.com/simonjupp/java-skos-api

Is this something you need?

**Comment by d0rg0ld** [comment]
Hi Simon,

thanks for your quick reply and for sharing your considerations in this regard. I am currently evaluating different OLS and the integration of SKOS thesauri might indeed be one requirement. For testing, I am currently converting SKOS to OWL and then import into the OLS. Since a "native" import would of course be better,  it's good to know that your code already contains a foundation in this regard.

Best,
Doron
