### ISSUE TITLE
DUO IRI issue

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#135]
HI,

The ontology IRI for DUO is listed as http://purl.obolibrary.org/obo/duo at http://www.ebi.ac.uk/ols/ontologies/duo, while it should be http://purl.obolibrary.org/obo/duo.owl

The file at http://purl.obolibrary.org/obo/duo.owl seems correct and contains
`<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/duo.owl">`

**Comment by mcourtot** [comment]
This seems to be true for many (all?) resources under OLS:
 http://www.ebi.ac.uk/ols/ontologies/agro
http://www.ebi.ac.uk/ols/ontologies/cco
http://www.ebi.ac.uk/ols/ontologies/dron
http://www.ebi.ac.uk/ols/ontologies/probonto
...

**Comment by simonjupp** [comment]
yes, it's a bug. I think these purls used to resolve so I never spotted it was happening. Will be fixed in the next release.
