### ISSUE TITLE
Api terms search for a non existent term return 200 and an empty paged result

### ISSUE THREAD

**Issue by Kerruba** [EBISPOT/OLS#136]
If you try to 
```
curl http://www.ebi.ac.uk/ols/api/terms?iri=http%3A%2F%2Fwww.cropontology.org%2Fterms%2FCO_715%3A0000015%2F
```

the api returns a 200 status code and an empty paged result
```
{
  "_links" : {
    "self" : {
      "href" : "http://www.ebi.ac.uk/ols/api/terms"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
```

instead of a proper 404

**Comment by simonjupp** [comment]
/api/terms returns a list of resources, you can filter by IRI but there maybe multiple resources with that IRI so this will always return a 200. 

I'm creating a new ticket to have an API endpoint that will check for the existence of a term and return a 404 if it doesn't exist. I'll let you know when that is ready.
