### ISSUE TITLE
missing ICO?

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#137]
ICO shows up in the OBO registry, http://obofoundry.org/ontology/ico.html, but not in the OLS, http://www.ebi.ac.uk/ols/ontologies

May reflect a loading problem from the OBO registry? cc @cmungall

**Comment by cmungall** [comment]
products list is empty in the obo metadata

**Comment by mcourtot** [comment]
Pinged Oliver and Frank to update the ICO metadata file.

**Comment by mcourtot** [comment]
Added Travis check on OBOFoundry side: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/390

**Comment by mcourtot** [comment]
ICO back in OLS: http://www.ebi.ac.uk/ols/ontologies/ico
