### ISSUE TITLE
NCiT from OBO registry

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#138]
While adding a check for resources missing products (following up on https://github.com/EBISPOT/OLS/issues/137), I saw that NCiT, http://obofoundry.org/ontology/ncit.html, doesn't have a product ID and is therefore not loaded either. I know @simonjupp has been planning on loading it - are you planning on dealing with potentially 2 sources for the same resource? Would it be helpful to be able to load it forms he OBO registry for now?

cc @cmungall

**Comment by simonjupp** [comment]
I believe some work is being done to improve the OWL representation of NCiT, or at least make an OBO compatible version available via the OBO library. My preference would be to get it from OBO.

**Comment by cmungall** [comment]
You can get it from OBO now https://github.com/OBOFoundry/purl.obolibrary.org/pull/345

I expect it will show up here next cycle: http://www.ebi.ac.uk/ols/ontologies/ncit
