### ISSUE TITLE
Modification ontology

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#144]
@simonjupp We need to index the followinf PTM modification ontology: UNIMOD http://www.unimod.org/obo/unimod.obo it is in obo file. Can you do it? 

REgards 
Yasset

**Comment by simonjupp** [comment]
Hi Yasset, 
Yes we can. Do you have a title, short description and contact details  to complete the metadata?

```
  - id: unimod
    preferredPrefix: UNIMOD
    title: ...
    uri: http://www.unimod.org/obo/unimod.obo
    description: ...
    homepage: http://www.unimod.org/
    mailing_list: ... (or issues tracker url)
    ontology_purl : http://www.unimod.org/obo/unimod.obo
```

**Comment by ypriverol** [comment]
title: Unimod protein modification database for mass spectrometry. 
description: Unimod is a community supported, comprehensive database of protein modifications for mass spectrometry applications. That is, accurate and verifiable values, derived from elemental compositions, for the mass differences introduced by all types of natural and artificial modifications. Other important information includes any mass change, (neutral loss), that occurs during MS/MS analysis, and site specificity, (which residues are susceptible to modification and any constraints on the position of the modification within the protein or peptide). 
mailing_list: psidev-ms-vocab@lists.sourceforge.net

Let me know if you need anything else and where will be online. 
Thanks for the quick reply.

**Comment by simonjupp** [comment]
http://www.ebi.ac.uk/ols/ontologies/unimod

**Comment by ypriverol** [comment]
@simonjupp I have been testing the UNIMOD Ontology. all the xref 

>xref: record_id "1"
>xref: delta_mono_mass "42.010565"
>xref: delta_avge_mass "42.0367"
>xref: delta_composition "H(2) C(2) O"

has been added as url references, then this metadata is missing. Can be possible to have them as properties, or database_cross_references like the MOD ontology: 

http://www.ebi.ac.uk/ols/ontologies/mod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMOD_00475

Regards 
Yasset

**Comment by simonjupp** [comment]
MOD gets converted to OWL by the OBO library before loading into OLS, so it puts all the xrefs into the correct format for OLS to parse. As OLS loads UNIMOD directly from OBO it does it's own conversion that isn't picking up the xrefs in the same way. I suspect this is because we are using an older version of the OWL API for reading in OBO files. I need to investigate this a bit.

Aside from this, I wonder if xref is really the right property to be using here for these values?
