### ISSUE TITLE
linking obsoleted terms to the term that replaced them

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/OLS#15]
Some obsoleted terms have an annotation that links them to the term it was "replaced by" or an alternative term to consider. 

it seems both 
http://www.geneontology.org/formats/oboInOwl#replacedBy
http://www.geneontology.org/formats/oboInOwl#consider 

are widely used (do these come from OBO?) but the URIs don't resolve so it would be good to try and standardise on something. 

cc @cmungall

**Comment by cmungall** [comment]
> http://www.geneontology.org/formats/oboInOwl#replacedBy
You should never see this. 

I can't see the underlying URI here
http://www.ebi.ac.uk/ols/beta/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001026

But it should be an IAO one

> http://www.geneontology.org/formats/oboInOwl#consider

There is no IAO equivalent here, and the OBOF translation is frozen

http://owlcollab.github.io/oboformat/doc/obo-syntax.html#5.8

There is no plans to make the oio IRIs resolvable to anything more than an OWL doc. You can think of them like the owl vocab here.

**Comment by simonjupp** [comment]
OK. The URI from IAO is http://purl.obolibrary.org/obo/IAO_0100001 for 'term replaced by'. This doesn't resolve either. Also, the value is a literal and uses the OBO id rather than URI. 

Rather than try and do any smart hyperlinking, I'm going to move all of these assertions to the top of the page for obsolete terms so they are more obvious.

**Comment by cmungall** [comment]
@mcourtot any idea why it wouldn't resolve?

**Comment by mcourtot** [comment]
It resolves for me, so not sure whether it was a transient issue or else?
