### ISSUE TITLE
error in web services for HPO and GO terms

### ISSUE THREAD

**Issue by jpflorido** [EBISPOT/OLS#159]
Hi all,
I've been using the OLS REST API successfully for HPO and GO terms for one month, but now I got the following error:
![image](https://user-images.githubusercontent.com/5921257/31885402-ac53c166-b7f0-11e7-8c4a-242e77f7769a.png)
It seems that the server does not accept requests from outside of EBI.
Any idea of how to solve this issue?
Thanks
Javier

**Comment by LLTommy** [comment]
Could be that you have an http/https issue. Do you use the https URL (https://www.ebi.ac.uk/ols/api/) instead of the 'old' http URL? The EBI by default redirects now (since beginning of October) http requests to https and I wonder if that's the reason why you get this error message.

**Comment by jpflorido** [comment]
Great! That was the problem. Thanks for the quick reply!

**Comment by LLTommy** [comment]
Glad if this solved the problem for you! The change to https by default [(announcement](https://www.ebi.ac.uk/about/news/service-news/embl-ebi-be-https-default-1-october?utm_source=dlvr.it&utm_medium=twitter)) influences most EBI services, so this is something to keep in mind. We are aware that it's not ideal that OLS requests to the 'old' URL do not work anymore, maybe we can fix this in the future.
