### ISSUE TITLE
Some ID spaces should not be in all caps

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#16]
E.g. WBbt, FBbt, WBPhenotype

In general, if the ontology follows OBO Foundry id policy, the ontology id _must_ be all lowercase, and the ID space _should_ be all uppercase. However, there are some mixed case entries there.

(Note that althought CHEBI is sometimes written ChEBI, their published IDs are all uppercase, so no change required there).

**Comment by simonjupp** [comment]
We use the id (lowercase). If a preferred prefix is supplied then we use that for display only.

**Comment by simonjupp** [comment]
Trying to understand if there is anything we need to change here? I think the preferred prefix should be set in the yaml file if they are wrong anywhere.

**Comment by cmungall** [comment]
This is on the front page, under 'short name' where you uppercase. Not high priority, just potentially confusing for some like FBBT

**Comment by henrietteharmse** [comment]
This is no longer an issue as far as I can see.
