### ISSUE TITLE
Ontology visitings stats

### ISSUE THREAD

**Issue by LLTommy** [EBISPOT/OLS#163]
It would be nice to have ontology visiting stats on the OLS homepage

**Comment by joncison** [comment]
Definitely!  But this is duplicating https://github.com/EBISPOT/OLS/issues/97.

**Comment by LLTommy** [comment]
Ah, missed that one, cheers. So I close this.

**Comment by joncison** [comment]
but pls. post there to give @simonjupp a friendly nudge :)
