### ISSUE TITLE
Consider changing 'subclass of' to 'relationships'

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#17]
Nomenclature is a bit inconsistent:

```
#Parents
trunk mesenchyme
mesenchyme derived from neural crest
cardiac mesenchyme
#Subclass of:
part_of some embryo
part_of some endocardium
develops_from some neural crest
part_of some heart

#Related from
develops_from

sinoatrial valve , atrioventricular septum , atrioventricular valve , ventriculo bulbo valve , ventricular septum intermedium , cardial valve
```

Parents is not part of OWL nomenclature informally it often includes existential parents.

SubclassOf is technically correct for existential parents but seems odd to use this here but not for named superclasses

In the reciprocal direction 'related' is used. The reciprocal view doesn't seem completely symmetric as there is no 'children'

**Comment by simonjupp** [comment]
Agreed it's confusing. Mixture of old OLS nomenclature fighting with proper OWL. We have a mix of users, some don't want to see or care about the OWLyness, others do.
 
Related from should be anything that isn't available when you expand the tree to child nodes. Do you think we should show all the children in the info box too? I need to put some limits on what gets displayed by default, with a little expander to see more.

**Comment by cmungall** [comment]
Consistency is good, but there is a higher chance of explosion with named subclasses... but if this is an issue you should probably be defensive about it for existential axioms too
