### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#177]
https://www.ebi.ac.uk/ols/index

   Related Tools

   In addition to OLS the SPOT team also provides Zooma, a service to assist in mapping data to ontologies in OLS and Webulous, a tool for building ontologies from spreadsheets. Also, **look out in the new year for our new Ontology mapping service** that will assist you in mapping between different but related ontologies.

Can the bolded part be updated? https://lists.w3.org/Archives/Public/public-bioschemas/2017Nov/0092.html mentions we don't provide any mapping service, which is an issue as I told people we can use the OLS mapping service

**Comment by simonjupp** [comment]
Yep, this needs updating. Thanks.
