### ISSUE TITLE
OxO hanging for HPO

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#178]
https://www.ebi.ac.uk/spot/oxo/datasources/HPO

![image](https://user-images.githubusercontent.com/50745/33151455-0bfc7d98-cf8d-11e7-856b-5ba9b1cdd962.png)

**Comment by simonjupp** [comment]
Seems like a bug in the prefix resolution, will investigate. This works https://www.ebi.ac.uk/spot/oxo/datasources/HP
