### ISSUE TITLE
Tree browser shows existential parents in lineage but opening node only shows named subclasses

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#18]
E.g. navigating to 'manual digit' shows 'forelimb' as a "parent" (in the combined superclass and existential graph sense) [aside: would be useful to see indication of relationship type]

However, expanding this node only shows subclasses. So for example, if I start on the 'forelimb' page, I can't get back to 'manual digit' via tree browsing. This asymmetricality of behavior could be confusing

**Comment by cmungall** [comment]
Related: navigate to the manual digit 1 page. The tree view invitingly shows a `+`. Clicking this gives an eternal spinner.

I think this is something do with the fact that some things are part of md1, but nothing is a named subclass

**Comment by simonjupp** [comment]
Are you not seeing the part of icons?

**Comment by simonjupp** [comment]
Can't seem to reproduce any of that...

**Comment by simonjupp** [comment]
![screenshot 2015-10-16 16 48 21](https://cloud.githubusercontent.com/assets/385021/10546421/c28eb302-7425-11e5-9a63-25b405197368.jpeg)

**Comment by cmungall** [comment]
No icons for me in firefox 41.0.1

<img width="721" alt="screen shot 2015-10-16 at 9 03 40 am" src="https://cloud.githubusercontent.com/assets/50745/10546758/cc933eae-73e4-11e5-8dd1-b7c5800c1e36.png">

Seems to work in Chrome though

**Comment by cmungall** [comment]
expanding md1 also works in chrome. Still spins in FF...

**Comment by simonjupp** [comment]
ok, will investigate. ta.

**Comment by simonjupp** [comment]
Seem to work ok for me on 42.0.2. What OS are you on?
