### ISSUE TITLE
PO purl is truncated in OLS metadata display

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#182]
on https://www.ebi.ac.uk/ols/ontologies/po

the '.owl' is truncated, which seems odd

**Comment by simonjupp** [comment]
This was an old bug that we fixed, but the fixes for each ontology won't be seen until the ontology is reloaded. I looked at why PO hadn't updated and it seems http://purl.obolibrary.org/obo/po.owl has been failing to parse for a while. 

`org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=419:column=130] IRI 'http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/po#Japanese' cannot be resolved against current base IRI http://purl.obolibrary.org/obo/po.owl reason is: Illegal character in fragment at index 78: http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/po#Japanese`

**Comment by cmungall** [comment]
@mariealaporte noticed this

There seems to be something odd in the obo2owl conversion (which means a fix may not be instantaneous..)

we have a similar problem in uberon; but uberon loads fine in OLS?

```
2210:    <!-- http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/UBPROP_0000006 -->
2212:    <owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#http://purl.obolibrary.org/obo/UBPROP_0000006"/>
```

Do you know if OLS chokes because of the OWLAPI or because of some code that is specific to OLS?

OWLAPI seems to handle it OK

`robot convert -i po.owl -o foo.owl`

Anychance there is a workaround on the OLS side for now while we investigate in more detail?

**Comment by simonjupp** [comment]
The uberon one is fine, the problem is the double use of # in the PO version

**Comment by simonjupp** [comment]
Also OLS using OWL API 3.5, but I got the same error when loading po.owl into protege 5.1. Strange how it worked with robot! I'll investigate a bit tomorrow.

**Comment by cmungall** [comment]
OK, I discovered the problem in po

```
synonym: "第一花序軸 (Japanese, exact)" EXACT [NIG:Yukiko_Yamazaki] {http://purl.obolibrary.org/obo/po#Japanese=""}
```

it's easy to mess us the synonym types when using Protege

**Comment by cmungall** [comment]
@cooperl09 made a new PO release, I'm closing as I assume this will be fixed in the next PO load

**Comment by simonjupp** [comment]
You’ll see it loaded and the Iri updated overnight
