### ISSUE TITLE
OLS API issue

### ISSUE THREAD

**Issue by ckongEbi** [EBISPOT/OLS#183]
When we query the API with wrong parameter `eact=true` 

https://www.ebi.ac.uk/ols/api/search?q=VACTERL-like%20phenotype&queryFields=synonym&eact=true&ontology=efo,ordo,hpo

We are getting TO:0000387 plant trait returned, is this to be expected? 

Thanks

**Comment by simonjupp** [comment]
Yes, you are querying without an exact match so OLS will find any partial matches in the synonym field. The synonym for TO:0000387 contains the word "phenotype" which is matching "phenotype" in your query string.

**Comment by ckongEbi** [comment]
Should the response report the error when we gave them the wrong parameter variable? `eact` instead of `exact`

**Comment by simonjupp** [comment]
Yes, we should probably return a 400 error code for a bad request. We'll look into it, thanks
