### ISSUE TITLE
OLS suggest

### ISSUE THREAD

**Issue by mkoatwork** [EBISPOT/OLS#184]
using the API and 'suggest term' returns the suggested term concatenated with the ontology in the highlighting section of the JSON 

e.g. https://www.ebi.ac.uk/ols/api/suggest?q=enzymatic 
returns

{
  "responseHeader" : {
    "status" : 0,
    "QTime" : 1,
    "params" : {
      "hl" : "true",
      "fl" : "autosuggest",
      "start" : "0",
      "rows" : "10",
      "hl.simple.pre" : "<b>",
      "q" : "\"enzymatic\"",
      "defType" : "edismax",
      "group.main" : "true",
      "hl.simple.post" : "</b>",
      "qf" : "autosuggest^3 autosuggest_e^2 autosuggest_wse^1",
      "hl.fl" : "autosuggest",
      "wt" : "json",
      "group.field" : "autosuggest",
      "group" : "true"
    }
  },
  "response" : {
    "numFound" : 160,
    "start" : 0,
    "docs" : [ {
      "autosuggest" : "enzymatic"
    }, {
      "autosuggest" : "enzymatic reaction"
    }, {
      "autosuggest" : "Enzymatic RNA"
    }, {
      "autosuggest" : "enzymatic ligation"
    }, {
      "autosuggest" : "enzymatic cleavage"
    }, {
      "autosuggest" : "enzymatic amplification"
    }, {
      "autosuggest" : "enzymatic polymerisation"
    }, {
      "autosuggest" : "enzymatic polymerization"
    }, {
      "autosuggest" : "enzymatically hydrolysed carboxy methyl cellulose, enzymatically hydrolysed cellulose gum"
    }, {
      "autosuggest" : "enzymatically modified"
    } ]
  },
  "highlighting" : {
    "enzymaticso" : {
      "autosuggest" : [ "<b>enzymatic</b>" ]
    },
    "enzymatic reaction**cco**" : { },
    "Enzymatic RNAmirnao" : { },
    "enzymatic ligation**ero**" : { },
    "enzymatic cleavage**ero**" : { },
    "enzymatic amplification**ero**" : { },
    "enzymatic polymerisation**mop**" : { },
    "enzymatic polymerization**mop**" : { },
    "enzymatically hydrolysed carboxy methyl cellulose, enzymatically hydrolysed cellulose gum**genepio**" : { },
    "enzymatically modified**genepio**" : { }
  }
}

**Comment by simonjupp** [comment]
The key is the id of the document in the Solr index. The autosuggest endpoint contains unique labels and synonyms from each ontology so we construct the id using a combination of the term and the ontology. We can't change this, what are you trying to do?

**Comment by mkoatwork** [comment]
If it would be possible to split the term from the ontology e.g. last term in the JSON document above:
"enzymatically modifiedgenepio" : { } into  "enzymatically modified" and "genepio" this would help to find specific ontologies resp. specific ontology/term combinations. At the moment it is hard to split the term as one has to compare the last characters to any available ontology.

**Comment by simonjupp** [comment]
You also have the option to filter the suggest endpoint by ontology. https://www.ebi.ac.uk/ols/docs/api#_suggest_term

There is also the "select" endpoint is for finding specific term ontology combinations. You also have more control over what fields can be returned in the response. Is this a better fit for your needs?

https://www.ebi.ac.uk/ols/docs/api#_select_terms

**Comment by mkoatwork** [comment]
My feeling is, there is a bug in the return results. The list containing

"enzymatic reactioncco" : { },
"Enzymatic RNAmirnao" : { },
"enzymatic ligationero" : { },
"enzymatic cleavageero" : { },
"enzymatic amplificationero" : { },
"enzymatic polymerisationmop" : { },
"enzymatic polymerizationmop" : { },
"enzymatically hydrolysed carboxy methyl cellulose, enzymatically hydrolysed cellulose gumgenepio" : { },
"enzymatically modifiedgenepio" : { }

concatenates always the return term and the ontology. The results should look like 
"enzymatic reactioncco" : { }, should be "enzymatic reaction" and "cco"
"Enzymatic RNAmirnao" : { }, should be "Enzymatic RNA and "mirnao"
"enzymatic ligationero" : { }, should be "enzymatic ligation" and "ero"
"enzymatic cleavageero" : { }, should be "enzymatic cleavage" and "ero"
"enzymatic amplificationero" : { }, should be "enzymatic amplification" and "ero"
"enzymatic polymerisationmop" : { }, "enzymatic polymerisation" and "mop" 
and so on

**Comment by simonjupp** [comment]
This isn't a bug, it just reflects how we chose to create the id for each document in the index. We could have used a random number for these. You shouldn't be using these ids to extract any semantics about the record. If you want to know which ontology the suggestion comes from use the select endpoint.

**Comment by mkoatwork** [comment]
OK, so I have to run for each term a select to get the ontology where the term belongs to. Thanks for clarification.
