### ISSUE TITLE
Intermittent 500 Error

### ISSUE THREAD

**Issue by paulkorir** [EBISPOT/OLS#189]
Here's what I get as the response:

`{"timestamp":1518609382649,"status":500,"error":"Internal Server Error","exception":"java.net.UnknownHostException","message":"pg-wwwcache.ebi.ac.uk","path":"/ols/api/search"}`

Any clues on what's happening?

**Comment by paulkorir** [comment]
Now I'm getting: 

`{"timestamp":1518610038920,"status":500,"error":"Internal Server Error","exception":"java.net.SocketException","message":"Too many open files","path":"/ols/api/search"}`

**Comment by simonjupp** [comment]
The service is currently under extremely heavy usage and some of the nodes are being restarted. Let me know if you continue to experience problems.

**Comment by paulkorir** [comment]
Thanks for the update. I'll let you know if this continues.

**Comment by jpflorido** [comment]
I'm experiencing the same problem two days ago and now again.

**Comment by simonjupp** [comment]
I think we isolated the primary cause and will continue to monitor the service. Please let us know if you experience anymore problems.
