### ISSUE TITLE
xrefs should link out to external sources

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#19]
xrefs are a relic of the OBO world, but they are common. The expectation is that they should link out to something. 

E.g. mappings tab in:
http://amigo.geneontology.org/amigo/term/GO:0000104#display-xref-tab

There are various registries of prefixes. Most OBO ontologies are consistent with the GO one:
https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

Alternatively, it would be valid to simply not support this, and to have the policy that complete URIs be used, in conjunction with annotation properties that are more meaningful. This won't happen overnight though...

**Comment by simonjupp** [comment]
This may be something we do as part of OLS integration with the main EBI search engine.

**Comment by simonjupp** [comment]
Closing as OLS now creates external links based on db-xrefs.yaml. Work is continuing to improve this and better integrate with identifiers.org

**Comment by jmcmurry** [comment]
Amazing, thank you!
