### ISSUE TITLE
hyperlink annotation assertion IRIs 

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#191]
see the seeAlso metadata in

https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024265

unless i'm doing something wrong, the seeAlso AP has a URL as value (linking to GARD website) - be great to see this hyperlinked so we can link back

(this is somewhat redundant with the xrefs section, I thought this was going to use identifiers.org to make links? In any case it can be useful to include a specific seeAlso or similar property)

cc @GARDInfoCenter

**Comment by simonjupp** [comment]
Yep, the website should create hyperlinks for AP values starting with http/https/ftp. We'll get this added. 

OLS still uses the go-xrefs file to generate external links for CURIEs where we recognise the prefix. We are moving this to use OxO which imports the go xrefs file, identifiers.org and others to do a better job of prefix resolution.

**Comment by cmungall** [comment]
I just realized my ticket is a dupe with #155 

@simonjupp would be good to coordinate on prefix mashing.

We have a repo here:

 * https://github.com/prefixcommons/biocontext

This acts as a clearinghouse, and a way of seeing how different combinations of prefixes work.

It's driven by a Makefile that coordinates the slurping of prefixes from different sources. The makefile can also mash different json-ld contexts together to make a combined one (with priority rules and reporting for clashes). 

Not sure if that's useful to you..

**Comment by matentzn** [comment]
Would love the priority of this elevated. Since many, if not most, of the xrefs are to CURIEs, my heart would leap of joy if those could be hyperlinked as well.
