### ISSUE TITLE
error viewing genepio

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/OLS#196]
**but report from Damion Dooley on the OLS support list**

I was debugging why a bunch of Error 1, Error2 … messages are occuring at top level of ontology display:

https://www.ebi.ac.uk/ols/ontologies/genepio

If I'm not mistaken OLS is adding these error items as a result of annotations on a particular relation of a class:

  "Has component" exactly 1 [whatever]

Seems to get an error if that relation has an annotation for label or rdfs:comment etc. I think that would be an error in loading up ontology into OLS?

This can be seen in entry:

https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENEPIO_0002109

Now, it might be something tricky like the owl:AnnotationProperty isn't in the right file, but if so, I'm at a loss about which file… these are in the main genepio.owl file along with the "Draft EBI Antimicrobial succeptibility test …" entity.

   <owl:AnnotationProperty rdf:about="http://www.w3.org/2000/01/rdf-schema#comment"/>

   <owl:AnnotationProperty rdf:about="http://www.w3.org/2000/01/rdf-schema#label">
       <rdfs:label>label</rdfs:label>
   </owl:AnnotationProperty>

**Comment by Public-Health-Bioinformatics** [comment]
BTW, I was reading about an OWLAPI issue that was possibly related: https://github.com/owlcs/owlapi/issues/571 , about 

> "0 [main] ERROR org.semanticweb.owlapi.rdf.rdfxml.parser.OWLRDFConsumer - Entity not properly recognized, missing triples in input? http://org.semanticweb.owlapi/error#Error1 for type Class"

so I was wondering if OLS was reporting that same error for Genepio errors.

**Comment by simonjupp** [comment]
This is definitely coming from the OWL API and I can reproduce this in Protege 4.3 which uses the same API version. OLS is currently on OWL API version 3.5.2. 

This seems to be fixed in newer OWL API versions and renders fine in Protege 5. We are due to update the OWL API version used by OLS that will fix this, but this will take some time. 

Are you responsible for genepio? If so I was wondering if you could generate a version as part of the release that drops the `has component` property for loading into OLS. This would at least allow us to index the terminology and hierarchy for the time being.

**Comment by Public-Health-Bioinformatics** [comment]
I am the lead curator - so ok, I'll see about a special conversion of "has component exactly 1" to has component "some" - I think that would solve this without having to remove it.  Is it possible to have this special version on github that OLS polls, that is separate from the main github /genepio.owl file?

**Comment by simonjupp** [comment]
Great - if you give me the GitHub URL to the alternate version we can poll that instead for the time being until we update the OWL API in OLS

**Comment by Public-Health-Bioinformatics** [comment]
Here it is …

https://github.com/GenEpiO/genepio/blob/master/src/ontology/genepio-merged-cardfix.owl

All "x 'has component' exactly 1 xyz" are replaced with "x 'has component' max 1 xyz".

Thanks a lot!

D.

**Comment by simonjupp** [comment]
How does this look? https://www.ebi.ac.uk/ols/ontologies/genepio

**Comment by Public-Health-Bioinformatics** [comment]
Great, thanks Simon!  (The remaining top levels are a result of intentionally leaving classes where their own ontologies place them).

Consider this closed.
d.
