### ISSUE TITLE
can't obtain any result from the search query

### ISSUE THREAD

**Issue by grugna** [EBISPOT/OLS#200]
I tried different sintax for the search API query, but I always get no results. I looked into the code base and the query is a String, could you please provide me with a working example?

This some of the one I tried:
curl -X GET 'http://www.ebi.ac.uk/ols/api/search?q={"Spindle"}'
curl -X GET 'http://www.ebi.ac.uk/ols/api/search?q={Spindle}'
curl -X GET 'http://www.ebi.ac.uk/ols/api/search?q="Spindle"'
curl -X GET 'http://www.ebi.ac.uk/ols/api/search?q=Spindle'
...

**Comment by simonjupp** [comment]
You need to query over https or set curl to follow redirects. 

curl -X GET 'https://www.ebi.ac.uk/ols/api/search?q=Spindle'
or
curl -LX GET 'http://www.ebi.ac.uk/ols/api/search?q=Spindle'
