### ISSUE TITLE
rename EFO:0007540 to animal viral hepatitis

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#203]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007540

![image](https://user-images.githubusercontent.com/50745/38762030-8bc298e0-3f3c-11e8-8dde-a44c6e94fb7f.png)

The hierarchy doesn't make much sense until you realize that the intent is that the subclass is for non-human animals.

```
 is_a MESH:D014777 ! Virus Diseases [DEF: "A general term for diseases produced by viruses."]
   is_a MESH:D006524 ! Hepatitis, Viral, Animal ***  [DEF: "INFLAMMATION of the LIVER in animals due to viral infection."]
   is_a MESH:D006525 ! Hepatitis, Viral, Human ***  [DEF: "INFLAMMATION of the LIVER in humans due to infection by VIRUSES. There are several significant types of human viral hepatitis with infection caused by enteric-transmission (HEPATITIS A; HEPATITIS E) or blood transfusion (HEPATITIS B; HEPATITIS C; and HEPATITIS D)."]
```

The EFO definition_citation is for MESH:D006524, but the definition doesn't mention animals. I suggest changing the def and label

**Comment by simonjupp** [comment]
Moved to EFO tracker EBISPOT/efo#139
