### ISSUE TITLE
MESH xrefs borked

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#204]
E.g. https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_447

goes to
https://www.nlm.nih.gov/cgi/mesh/2015/MB_cgi?view=expanded&field=uid&term=D006457 [404]

contrast with id.org and
http://n2t.net/MESH:D006457

**Comment by cmungall** [comment]
hah, that's our fault, hold on...

**Comment by simonjupp** [comment]
I'll close this then, we'll be moving all xref id resolution to use OxO soon (which config from id.org )
