### ISSUE TITLE
odd xrefs in EFO diseases

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#206]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002506

EV definition citation
EV:0400132

what's this?

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0006719

NCI Metathesaurus definition citation
NCI_Metathesaurus:CL329978

this this a real ID? 

The NCI_Metathesaurus prefix is used 8 other times, look like UMLS IDs?

**Comment by cmungall** [comment]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1000791

"SNOWMED"

**Comment by zoependlington** [comment]
See ticket [#162](https://github.com/EBISPOT/efo/issues/162).
