### ISSUE TITLE
intracranial hemorrhage NOS

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#207]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000551

this has two xrefs to NCIT in EFO. The first is to a finding not a disease. The second is a mistake as it is to  [NCIT:C34463](http://purl.obolibrary.org/obo/NCIT_C34463) ! Chlamydial Infection

Also: do you really need the NOS on the end?

**Comment by zoependlington** [comment]
See [here](https://github.com/EBISPOT/efo/issues/161). Ticket completed.
