### ISSUE TITLE
where did ols-config-importer.jar go?

### ISSUE THREAD

**Issue by pelacables** [EBISPOT/OLS#211]
Sorry, i'm very new to this project and I'm not sure what it does, but I'm trying to build another Docker image that uses this code and it expects ols-config-importer.jar to be in 
```bash
ols-apps/ols-config-importer/target/ols-config-importer.jar
```

but I don't see this file anymore.... where did it go? 

TIA,
Arnau

**Comment by simonjupp** [comment]
This should get generated when you build with Maven. Btw, we have a base image for OLS on docker-hub now https://hub.docker.com/r/ebispot/ols/

**Comment by simonjupp** [comment]
I'm closing the issue, please re-open if this hasn't been resolved
