### ISSUE TITLE
Dependency neo4j-cypher-dsl appears to have vanished from http://repo.spring.io/milestone

### ISSUE THREAD

**Issue by Robbie1977** [EBISPOT/OLS#220]
```[ERROR] Failed to execute goal on project ols-neo4j: Could not resolve dependencies for project uk.ac.ebi.spot:ols-neo4j:jar:3.2.1-SNAPSHOT: Could not find artifact org.neo4j:neo4j-cypher-dsl:jar:2.0.1 in spring-milestones (http://repo.spring.io/milestone) -> [Help 1]```

**Comment by simonjupp** [comment]
Not noticed this and nothing has changed. I just tried a clean build and it seemed to work.

**Comment by Robbie1977** [comment]
@simonjupp did you clear your maven cache?

Files still not on repo:
![image](https://user-images.githubusercontent.com/4630768/45238117-0705b380-b2e1-11e8-8b92-f25167f0162e.png)

**Comment by Robbie1977** [comment]
Your docker version build should definitely fail as a quicker test
