### ISSUE TITLE
OLS crawling BioSamples to discover ontology terms being used

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#224]
Hi,

We have this outstanding ticket in our tracker, which seems to belong to yours instead.

Cheers,
Melanie 

As OLS, I want to crawl biosamples and discover all ontology terms in use. This should be done by supporting embedded JSON+LD inside the HTML.
Should all be in place and working, just need Simon/OLS to test and ensure it meets their requirements (UAT - User Acceptance Testing).

**Comment by udp** [comment]
Not really sure what's being asked here. They can open a new ticket if it's still relevant.

**Comment by mcourtot** [comment]
This was a request from Simon a long while back, where he/the OLS team wanted to get an overview of all ontology terms used in BSD. Agree on closing.
