### ISSUE TITLE
bug when searching for NCIT:6557

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#227]
when I search for NCIT:6557, I don't get the correct results:
![image](https://user-images.githubusercontent.com/6722114/46993658-2bfdfb00-d0c5-11e8-935f-8252b5972b74.png)

but when I search for the corresponding label 'Schwannomatosis', I do get the proper result:
![image](https://user-images.githubusercontent.com/6722114/46993644-1688d100-d0c5-11e8-92c1-1e136ce123cb.png)

I am using a Mac with Google Chrome.

**Comment by simonjupp** [comment]
Hi Nicole, 
The id starts with a C - NCIT:C6557. That should work.

**Comment by nicolevasilevsky** [comment]
My bad! Thanks @simonjupp!
