### ISSUE TITLE
Cannot index with ols-indexer

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#239]
Hello,

I'm trying to perform a local installation of OLS. However, when I execute the ols-indexer I get the following error:
```
ERROR main MongoOntologyIndexingService.indexOntologyDocument - Error indexing edam
ERROR main LoadingApplication$$EnhancerBySpringCGLIB$$101c8fcb.run - Application failed creating indexes for edam: Expected mime type application/octet-stream but got text/html.
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/ontology/select. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
; nested exception is org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSol                                                               rException: Expected mime type application/octet-stream but got text/html. <html                                                               >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/ontology/select. Reason:
<pre>    Not Found</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

It looks that the jetty server cannot access the solr resource, however, I can access Solr running at localhost:8983/solr without problems. The server is an Ubuntu 18.04. Tomcat is down while indexing, Solr version is 5.2.1 and mongo (v3.4.18) is up (no problems with ols-config-importer).

I've tried to set the `spring.data.solr.host` varible for the indexer set as 
`spring.data.solr.host=http://127.0.0.1:8983/solr` without success. Any ideas?

Thanks,
José Antonio

**Comment by henrietteharmse** [comment]
Hi Jose, 

Thank you reporting the issue. I am looking into this.

I am also running OLS on Ubuntu 18.04 without problems. I just want to know the following:

How do you start Solr? You need to specify the following: 
 -Dsolr.solr.home=$YOUR_OLS_HOME/ols-solr/src/main/solr-5-config -Dsolr.data.dir=$OLS_DATA_HOME/solr
where $YOUR_OLS_HOME points to the OLS source root directory and $OLS_DATA_HOME points to where the indexer is writing the data. This is by default ~/.ols/.

Thanks
Henriette

**Comment by neobernad** [comment]
Hello Henriette,

That works! Setting the variables `-Dsolr.solr.home`  and `Dsolr.data.dir` as you told, inside the script *bin/solr* fixed my problem.

Thank you so much,
José Antonio

**Comment by henrietteharmse** [comment]
Thank you for the feedback Jose. 

I am glad that resolved the issue. Feel free let us know if you encounter any other issues.

Keep well,
Henriette
