### ISSUE TITLE
OLS not checking language tags

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/OLS#241]
OLS assumes that terms only have one label, which is not the case with ontologies such as CLO (see https://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBFO_0000040). Needs to look at the language tags when there are multiple labels and choose english language labels.

**Comment by agbeltran** [comment]
I'm facing the same issue. 

When using OLS API to retrieve the label for ```http://purl.obolibrary.org/obo/CLO_0000031```, I'm getting the Chinese label and I would like to retrieve the English label (both are defined in the ontology, https://github.com/CLO-ontology/CLO/tree/master/src/ontology):

https://www.ebi.ac.uk/ols/api/ontologies/CLO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCLO_0000031

This also happens in the UI:
https://www.ebi.ac.uk/ols/ontologies/clo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCLO_0000031

**Comment by agbeltran** [comment]
Adding a screenshot 
![Screen Shot 2019-03-26 at 11 48 23](https://user-images.githubusercontent.com/1417033/54997599-00f8cb00-4fc4-11e9-8a28-358fc17047b8.png)
