### ISSUE TITLE
OLS Search "Exact match" not working

### ISSUE THREAD

**Issue by YasminAF** [EBISPOT/OLS#245]
In OLS https site, when searching the NCIT ontology on a particular HGNC id (eg. HGNC:487) the gene term is not the first hit on the resulting search (i.e. ANGPT4 Gene  NCIT:C106488) list. So when you select 'Exact match' on your search you get zero results - see screenshots attached

<img width="1014" alt="hgnc487_exactmatch" src="https://user-images.githubusercontent.com/16701632/53829235-9a116480-3f77-11e9-9881-24bdcfab40e3.png">
<img width="1027" alt="hgnc487_ols_search" src="https://user-images.githubusercontent.com/16701632/53829237-9a116480-3f77-11e9-8eab-eea8ac6557d2.png">

**Comment by henrietteharmse** [comment]
The reason why "exact match" seems to be not working when searching for HGNC:487 is because this term does not exist in OLS. However, partial matches like HGNC or 487 do exist in OLS. Or, as in the given example, numerous partial matches in the form of "NC" exist in OLS.
