### ISSUE TITLE
Create a neo4j instance without mvn clean package

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#248]
Hello,

I would like to create a neo4j database aside to the one that the OLS provides. I know I can create a standalone neo4j database with [this tutorial](https://github.com/EBISPOT/OLS/tree/master/ols-apps/ols-neo4j-app).
That method however requires to create the config file and then rebuild with maven, so that the `ols-neo4j-app.jar` can look for an `application-*.properties` file.
Is there anyway to provide the config file directly to the `ols-neo4j-app.jar` without having to rebuild?

Thanks,
José Antonio

**Comment by henrietteharmse** [comment]
Yes, that indeed possible. The tutorial states that you can run the `ols-neo4j-app` using 

`java -Xmx2g -jar -Dspring.profiles.active=uberon ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar`.

What you need to do is specify a classpath that includes the desired properties file, i.e.:

`java -cp "path_to_ols-neo4j-app.jar:path_to_your_properties" -Xmx2g -jar -Dspring.profiles.active=uberon ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar`

on Unix systems or 

`java -cp "path_to_ols-neo4j-app.jar;path_to_your_properties" -Xmx2g -jar -Dspring.profiles.active=uberon ols-apps/ols-neo4j-app/target/ols-neo4j-app.jar`

on Windows systems.

**Comment by neobernad** [comment]
It works by doing the method you stated, thanks!
Addionally, can I set a local path to an ontology file instead of an URL? I tried by changing the `location` variable in the configuration file but it did not work, so I do not know if there is an actual walkaround to this.

Thanks for your time as always,
José Antonio
