### ISSUE TITLE
Indexing big ontologies - OutOfMemoryError

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#249]
Hello,

I am trying to index a 404MB OBO ontology in a local OLS installation, but I am getting the following error:
```
Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /solr/ontology/select. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space
</pre>
<hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
; nested exception is org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /solr/ontology/select. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space
</pre>
<hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```
I know it is the typical Java memory error when the virtual machine runs out of heap memory, which is easily fixed by increasing it via `-Xmx` parameter. The command to run the indexer is: `java -Xmx100g -Dspring.data.solr.host=http://127.0.0.1:8983/solr -jar ols-indexer.jar`.
It seems weird to me that in order to index a 404MB file the whole process consumes more than 100GB of RAM. 
Considering that I do not have more spare memory for this server, have you guys faced this problem before or know a workaround to this issue?
I have thought about splitting the OBO file into small chunks, which I think it would solve the problem, but then I would need an additional configuration entry per each chunk.

Thanks,
José Antonio

**Comment by simonjupp** [comment]
You shouldn't need that much memory. Isn't that not the Solr server (also Java) running out of memory anyway? I'd restart Solr and give it at least 1 -2 gb of memory.

**Comment by neobernad** [comment]
Thanks @simonjupp!, I totally forgot Solr was also running on Java.
