### ISSUE TITLE
Adding SRAO to OLS

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/OLS#250]
Allyson Lister send an email to the ols-support helpdesk:

"Hi all,

Thanks for your help recently, as I've sent you a few emails over the past few months about OLS - I've used it a lot while building SRAO, an application ontology of research areas / subjects (https://github.com/FAIRsharing/subject-ontology). We've built it from lots of different sources, and have used OLS to help us find those sources. As work progresses on it, and we're ready to publicise it more, I'd love to get it indexed by OLS. What are your requirements etc for adding an ontology to OLS? 

SRAO is an application ontology, built for the purpose of being able to describe all research areas for FAIRsharing. As such, it draws it's main hierarchy from one resource, and then maps classes from multiple publicly-available ontologies to that hierarchy. None of the ontologies in OLS does this yet, at least not for the wide breadth of scope available in SRAO. It is, at its heart, an application ontology; we're trying very hard not to mint new IRIs etc, though we've had to do that in some cases. However, application ontologies are not the same as community-built ontologies, and therefore I'd like to know if / how we can add it to OLS. There has been some interest in it from outside groups already, and the ability to view it in OLS would be a great help to them.

Thanks very much,
Allyson"

**Comment by allysonlister** [comment]
(I should qualify my previous statement - of course there are other application ontologies in OLS, I was just referring to the cross-subject area nature of ours.) 

I am unsure whether or not SRAO is suitable for incorporation, but happy to investigate this with you. Thanks very much!

**Comment by henrietteharmse** [comment]
Hi Allyson, 

Once you are ready to publish your ontology on OLS, please fill out the attached file and we will update OLS accordingly. If you have any questions, please feel free to let me know. 

[SRAO ontology configuration.xlsx](https://github.com/EBISPOT/OLS/files/3116415/SRAO.ontology.configuration.xlsx)

Keep well,
Henriette

**Comment by allysonlister** [comment]
Dear Henriette,

Thanks very much, this is great! We'll fill out the form and get it back to you, most likely once we've completed our current point release.

Best wishes,
Allyson

--
Dr. Allyson Lister
Knowledge Engineer, FAIRsharing & ISA-Tools
https://www.eng.ox.ac.uk/people/allyson-lister/
ORCiD: 0000-0002-7702-4495
@allysonlister

Please note that I work part time, mainly Tuesdays, Wednesdays and Thursdays. If the matter is urgent, you may wish to email contact@fairsharing.org instead.

For more on FAIRsharing, please see https://doi.org/10.1038/s41587-019-0080-8


________________________________________

**Comment by henrietteharmse** [comment]
This ticket will be moved back to "In Process" when we get the go-ahead.

**Comment by allysonlister** [comment]
Good afternoon! Apologies for the delay, but we've updated SRAO and we are ready for the next step with OLS please.
[SRAO-ontology-configuration-OLS.xlsx](https://github.com/EBISPOT/OLS/files/3841670/SRAO-ontology-configuration-OLS.xlsx)
Attached is the metadata you asked for, and please let me know if you have any questions!

Thanks very much for all your help,

:) Allyson

**Comment by henrietteharmse** [comment]
I am a bit flooded at the moment, so it might take 2-3 weeks to get to it. I will move to 'Next' so that it is on my radar and that I get to it the moment I have a gap.

**Comment by allysonlister** [comment]
Apologies - I just noticed a URI typo in the SRAO xlsx file that I uploaded last week. Here is the updated file.
[SRAO-ontology-configuration-OLS.xlsx](https://github.com/EBISPOT/OLS/files/3875104/SRAO-ontology-configuration-OLS.xlsx)

Thanks! :) Allyson

**Comment by henrietteharmse** [comment]
SRAO is now available on OLS. See https://www.ebi.ac.uk/ols/ontologies/srao.

**Comment by allysonlister** [comment]
Thank you!
