### ISSUE TITLE
Add hyperlinks?

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#26]
http://www.ebi.ac.uk/ols/beta/search?q=head

What is the long list of ontologies on the right? I thought they were ontologies where I would find extra occurrences of my search term but they are not hyperlinks, so I'm not quite sure what to do with them?

**Comment by LLTommy** [comment]
Thank you for your feedback. I did some changes that hopefully address this problem. Available as soon as a new version of OLS goes live.

**Comment by simonjupp** [comment]
these are facets, they show how many hits you have in each ontology. when you click they should trigger a new search to see results restricted to the selected ontology

**Comment by matthiaskoenig** [comment]
Did not know that. Thanks for the information.
Some things in the UI were not so clear when I looked at it.

On Tue, Dec 8, 2015 at 5:54 PM, simonjupp <notifications@github.com> wrote:

> these are facets, they show how many hits you have in each ontology. when
> you click they should trigger a new search to see results restricted to the
> selected ontology
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EBISPOT/OLS/issues/26#issuecomment-162943653>.
>



-- 
--------------------------------------------------------------
Matthias König
Computational Systems Biochemistry
Institute of Biochemistry
Charité - Universitätsmedizin Berlin
http://www.charite.de/sysbio/people/koenig/
Tel: + 49 30 450528449
Tel: + 49 176 81168480
--------------------------------------------------------------

**Comment by LLTommy** [comment]
Again, not working yet but it will as soon as we push it into production. So I close this issue, thanks everybody for the feedback.
