### ISSUE TITLE
Add single cell atlas ontology to OLS

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#265]

**Comment by henrietteharmse** [comment]
@S2Ola: Please fill out the attached spreadsheet when you are ready for your ontology to be added to OLS. 
[SCA ontology configuration.xlsx](https://github.com/EBISPOT/OLS/files/3152439/SCA.ontology.configuration.xlsx)

**Comment by S2Ola** [comment]
No need to add this to OLS
