### ISSUE TITLE
MonDO term for monogenic diabetes (MONDO:0015967) missing in OLS

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#267]
Based on RT ticket https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=345545.

**Comment by paolaroncaglia** [comment]
@henrietteharmse
At the moment, the MONDO version in OLS is dated April 10 (see https://www.ebi.ac.uk/ols/ontologies/mondo), and in that version MONDO:0015967 was still obsolete. It can be retrieved by entering MONDO:0015967 in the search box, hitting return, and then selecting the checkbox for "Obsolete terms" under the search box. 
The new MONDO release should make it to OLS really soon - in fact I was expecting it to be there today, if not yesterday already. Not sure if the yesterday's glitches at the EBI delayed the process?
Thanks.

**Comment by zoependlington** [comment]
+1 for MONDO needing updating in OLS - we really need to test it in EFO too. I wonder why the v2019-04-29 release wasn't picked up by OLS? That definitely needs to be looked into because we should always have the most up-to-date versions in OLS.

**Comment by simonjupp** [comment]
This is now resolved

**Comment by paolaroncaglia** [comment]
@simonjupp @henrietteharmse 
Something else looks weird in the current MONDO release in OLS, please look at the 4 top terms:
<img width="234" alt="image" src="https://user-images.githubusercontent.com/4982516/58973110-7270a900-87bf-11e9-99d1-81309b1b3c74.png">
Thanks!

**Comment by simonjupp** [comment]
I think we need a ticket on the MONDO tracker as some classes are referring to obsoleted terms e.g MONDO:0014832

**Comment by paolaroncaglia** [comment]
Done (https://github.com/monarch-initiative/mondo/issues/726). Moving this ticket back to the "Done" queue.
