### ISSUE TITLE
Indexes (SOLR?) behave weirdly

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#269]
This points you a term that does not exist in the ontology:

https://www.ebi.ac.uk/ols/ontologies/plana/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000000

However, search for the term reveals it is not in the ontology (which is correct):

https://www.ebi.ac.uk/ols/search?q=processual+entity&groupField=iri&exact=on&start=0&ontology=plana

The version IRI OLS lists for PLANA is
http://purl.obolibrary.org/obo/plana/releases/2019-05-25/plana.owl

If you open this, no processual entity is found (which is correct).

My feeling is that whatever drives the the hierarchy view is out of sync.

**Comment by matentzn** [comment]
Another example: If you open in Protege:

http://purl.obolibrary.org/obo/hp.owl

you see that all classes are labelled. The hierarchy in OLS does not reflect that, but if you search for `GO_0000791` in the autocomplete field (a term rendered without label in the hierarchy), it shows up having a label. 

I would personally elevate this issue in urgency, as we dont know whether many of the problems we are having not seeing some terms etc come from the fact that the trees are not updated..

**Comment by daniwelter** [comment]
@matentzn I tested your instructions above and the only time you see a label for `GO_0000791` is in the search result, which I believe is driven by the full OLS search index - if the term therefore has a label in any ontology in OLS (eg in GO proper), the label will be available through there. If you click through to the term in HP, the label is gone again. 
I agree something weird is going in the label rendering in OLS - I even downloaded HP from OLS to check that the label is definitely present (it is!)- so this definitely needs addressing, but at least the error in the rendering behaviour is consistent.

**Comment by LLTommy** [comment]
Just want to add I am also interested in this issue - since if the search index is corrupted, I might have to throw away the result I was creating the last 24 hours via my OLS crawler @simonjupp

**Comment by matentzn** [comment]
I just double checked and it seems fixed! :)

**Comment by simonjupp** [comment]
@LLTommy it probably only mattered if you were hitting HP or Plana
