### ISSUE TITLE
MIRIAM conform ids missing in search results

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#27]
Dear OLS team,
great work on the redesign.

I am currently annotating a computational model (SBML) and using the OLS to find suitable terms.
Unfortunately, in the results list there are not the necessary ids for the Miriam annotation.

For instance:
Searching for liver
http://www.ebi.ac.uk/ols/beta/search?q=liver

In the results I want to use the BTO for annotation, which has the id rules
^BTO:\d{7}$
http://www.ebi.ac.uk/miriam/main/collections/MIR:00000111

In the results I only see
```
liver  
BTO
http://purl.obolibrary.org/obo/BTO_0000759
1: A large very vascular glandular organ of vertebrates that secretes bile and causes important changes in many of the substances cont
```
So I have to know/lookup the miriam id rules instead of just using the search result.
The result should look like this:
```
liver  
BTO:0000759
http://purl.obolibrary.org/obo/BTO_0000759
```
So one can copy and paste it in the annotations.

The best
Matthias

**Comment by simonjupp** [comment]
This makes sense, I'm planning to add a way to see more info for a term in the search results. This would show synonyms and will include the short id.

**Comment by matthiaskoenig** [comment]
Yes, maximize the information on the search results, i.e. information per pixel and remove unnecessary clutter from GUI.
For instance a nice searchable/filterable/sortable table with DataTable as result and columns id, ontology, description, ... would be much better than the search results right now.
Move the list of ontologies to the left under the search options, than you have a lots of space for such a table.
You than have space to show 20 or 50 results instead of only 10.

**Comment by matthiaskoenig** [comment]
Any update on this?
It should take 20 minutes to implement. One only has to display some additional fields in the search results.

**Comment by simonjupp** [comment]
There's a whole stack of improvements coming to the advanced search results which will resolve this issue. should be live for testing over next couple of weeks.

**Comment by matthiaskoenig** [comment]
Sounds great.
Close the issue when the system is live, so I get notified.

On Thu, Feb 18, 2016 at 11:27 AM, simonjupp <notifications@github.com>
wrote:

> There's a whole stack of improvements coming to the advanced search
> results which will resolve this issue. should be live for testing over next
> couple of weeks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EBISPOT/OLS/issues/27#issuecomment-185643397>.
>



-- 
Matthias König
Junior Group Leader LiSym - Systems Medicine of the Liver
Humboldt-University Berlin, Institute for Theoretical Biology
  https://www.livermetabolism.com
konigmatt@googlemail.com
Tel: +49 30 20938450
Tel: +49 176 81168480
