### ISSUE TITLE
Update OLS css to latest EBI stylesheets

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/OLS#278]
- [x] + icons are missing for opening and closing the tree  
- [x] Search bar should be aligned with the facet box   
- [x] Facets overflow not wrapping nicely 
- [x] Definitions not showing on EFO (that’s your config not using the correct description property)
Need to set ols-config.yaml 
synonym_property : http://www.geneontology.org/formats/oboInOwl#hasExactSynonym 
definition_property : http://purl.obolibrary.org/obo/IAO_0000115      
- [ ] Check snarf instance with different browsers (including windows) 
- [x] Checking font size and hyperlink styling
- [x] don't change font colour when hovering on previous / next links on search results page
- [x] fix elixir banner to be full width with white background similar to https://www.ebi.ac.uk/gxa/home
- [x] Fix autocomplete box on search facet - when adding additional ontology to facet you can't see the suggestions
- [x] Find out why foundation is throwing `foundation.js:10631 Uncaught TypeError: Cannot read property 'top' of undefined` on every page
- [x] When hovering on selectable facets the pointer is  not changing to finger. Background of facet should also be highlighted 
- [x] clicking on the count in facets doesn't select the facet 
- [x] selecting type facet doesn't seem to always work 
- [ ] If a term is both a individual and class type, the facet counts are wrong and the search results show the ontology name and say also in the same ontology
- [x] Get rid of shadowing around white "button" (which isn't really a button) in facet search
- [x] Add colour (and better alignment?) to "Term info" header on right-hand panel
- [x] Consistency of boxes on tree view page
- [x] Use distinct Foundation icon for mapping on tree view panel
- [x] Fix size of breadcrumbs on tree view page
- [ ] Terms in right-hand panel should be linked
- [ ] Fix autocomplete repeated redraws?
- [x] Order buttons alphabetically, reduce their horizontal spacing and fix vertical spacing
- [ ] Fix (e.g.) "MEDRA also in MEDRA" if both class and individual present: ignore if both

**Comment by warrenread** [comment]
Facets overflow issue is something to do with select2 (jQuery-based) library css classes—investigating. Definitions have been modified, and config importer re-run, but definitions are still not populating search results. Both issues need fixing and uploading to Github (whereupon they will deploy to snarf), before full cross-browser compatibility checks can be conducted.

**Comment by warrenread** [comment]
Alignment issue with breadcrumbs fixed, but labels are flowing into each other vertically while horizontally, they are spaced too widely. There is an issue with html auto-generating text nodes between inline elements, where stylistically, the space is not helpful.
