### ISSUE TITLE
Provide ontology information in search results 

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#28]
There should be information about the ontologies in the search results.
Provide a tooltip in the search results to the name of the ontolgy. I.e. on mouse-over over the blue box with the ontology id, like **BTO**, the full name of the ontology should be displayed, i.e. **Brenda Tissue Ontology**.
Right now one has to click on the result just to find out it is not a ontology of interest.

See http://www.ebi.ac.uk/ols/beta/index for list of names.

For instance 
http://www.ebi.ac.uk/ols/beta/search?q=liver
I have no idea, what EHDAA2, UBERON, ... are --> Make the names for the ontologies available

**Comment by LLTommy** [comment]
Done. Available as soon as we push it to production, probably in a couple of days.

**Comment by matthiaskoenig** [comment]
Great news. Thanks a lot.
