### ISSUE TITLE
Request to add MAXO to OLS

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#281]
Hey @simonjupp, on behalf of the [Medical Action Ontology](https://github.com/monarch-initiative/MAxO), I would like to inquire whether you would consider loading maxo.owl into OLS, despite the fact that we are currently [barred from OBO foundry](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/868). 

MAXO contains a rich set of curated xrefs to ontologies that are already in OLS (chebi, foodon, ncit); it roughly fits in the OBI, OGMS space, but is much more detailed. Our plan is to integrate it better with OBO ontologies over the next years. It is designed for a use case involving text mining from pubmed; it therefore contains a very rich set of synonyms that may be useful for groups that are using NCIT and similar.

@LCCarmody

**Comment by henrietteharmse** [comment]
Please can you fill out the attached spreadsheet for MACO to be configured in OLS.[https://app.zenhub.com/files/26123514/967b5b60-5ad6-4aeb-8c8a-a6cab8978499/download](https://app.zenhub.com/files/26123514/967b5b60-5ad6-4aeb-8c8a-a6cab8978499/download)

**Comment by matentzn** [comment]
All good its on now!
