### ISSUE TITLE
Mondo name is deprecated

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#282]
https://www.ebi.ac.uk/ols/ontologies/mondo

Mondo is no longer called Monarch Disease Ontology: it is called [Mondo Disease Ontology](http://obofoundry.org/ontology/mondo.html) (Mondo) 

If you could change the title, that would be great.

**Comment by henrietteharmse** [comment]
Mondo's title was changed on 23 May. I think we just need to reload the config so that OLS registers the change. I will do that when I am back.

**Comment by matentzn** [comment]
Thank you @henrietteharmse

**Comment by henrietteharmse** [comment]
This is a problem with the Mondo ontology and needs to be corrected in Mondo. I.e.: 
`<dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">MONDO: Monarch Disease Ontology</dc:title>`
needs to be changed in the ontology.

**Comment by matentzn** [comment]
Oh my god! I would have never thought.... Thanks :)
