### ISSUE TITLE
bad display and link of MONDO term pulmonary branch stenosis

### ISSUE THREAD

**Issue by fiendish** [EBISPOT/OLS#288]
MONDO has a potentially bad ID for "pulmonary branch stenosis" and I think this is screwing up the code display and reference link.

https://www.ebi.ac.uk/ols/search?q=pulmonary+branch+stenosis&ontology=mondo
shows:
<img width="788" alt="Screen Shot 2019-09-24 at 1 02 50 AM" src="https://user-images.githubusercontent.com/201996/65482429-15305e80-de67-11e9-93bb-1f4a2b27d4f7.png">

Note that the yellow code tag shows only `:0020420y` and not `MONDO:0020420y`.
Also note that the link shows `http://purl.obolibrary.org/obo/MONDO#_0020420y` but per http://www.ontobee.org/ontology/MONDO?iri=http://purl.obolibrary.org/obo/MONDO_0020420y it should be `http://purl.obolibrary.org/obo/MONDO_0020420y` without the `#`.

**Comment by udp** [comment]
This appears to be resolved.
