### ISSUE TITLE
New SWO release (1.7)

### ISSUE THREAD

**Issue by allysonlister** [EBISPOT/OLS#294]
Good morning! Last night I pushed a new SWO release to the location behind our purl (http://purl.obolibrary.org/obo/swo.owl). Currently, the purl points to https://raw.githubusercontent.com/allysonlister/swo/master/release/swo-inferred.owl

I was wondering when I could expect to see this update in OLS? Or, if there was a problem with the automated parsing of the swo file, please let me know. It ran just fine with Hermit last night, but there's always the possibility I missed something.

Thanks very much :) Allyson

**Comment by henrietteharmse** [comment]
It normally takes about 2 days for an update to reflect, sometimes a bit longer. We had a data release that completed this morning, but I think the update started running yesterday before the update to SWO was available. Hence, the reason why it is not updated in OLS as yet. 

It should be available by the weekend at the latest. I will keep on it and keep you posted.

**Comment by allysonlister** [comment]
Sounds great - thanks for letting me know :)

**Comment by henrietteharmse** [comment]
Hi Allyson,
 
The OLS data release did complete, but SWO was not updated. Currently I do not know why that is the case. I hope to have an idea by Monday when I will update you again. 

Keep well,
Henriette

**Comment by allysonlister** [comment]
Thanks for the update. Please let me know if I can help in any way. It's a big change from the last release, which might result in issues for you (but hopefully not!). Happy to help in any way.

thanks :) Allyson

**Comment by henrietteharmse** [comment]
There is bug in the OLS indexer that resulted in SWO not being indexed. Hence the reason for the updated version to not reflect on the OLS website. We will need to roll out an update to OLS to correct this.

**Comment by drmarkreuter** [comment]
ok, good to know it's 'work in progress'.

**Comment by henrietteharmse** [comment]
Version 1.7 of SWO is now available at https://www.ebi.ac.uk/ols/ontologies/swo.

**Comment by allysonlister** [comment]
Thanks very much - I really appreciate all of your help! 

Just FYI the title you have at that URL for SWO is the old one (which was in fact an accidental title that was mistakenly propagated by us from EDAM at the last release ;-) )

Please could you make sure that the title of the ontology at https://www.ebi.ac.uk/ols/ontologies/swo is that listed in the dc:title field, which is "SWO (The Software Ontology)"

**Comment by henrietteharmse** [comment]
OLS does pickup the title of the ontology from `dc:title`. However, in https://raw.githubusercontent.com/allysonlister/swo/master/release/swo-inferred.owl the title is specified in `terms:title` rather than `dc:title`. If that can be corrected then OLS will pick it up from there.

**Comment by allysonlister** [comment]
Oh dear - that's my fault - whoops! Thanks for pointing it out :) I'll let you know when it's done!

**Comment by allysonlister** [comment]
I've updated it to http://purl.org/dc/elements/1.1/title, please let me know if you have any issues with the updated files.

Thanks!

**Comment by allysonlister** [comment]
It all looks good - I'll close this ticket - thanks!
