### ISSUE TITLE
EFO not updated in OLS yet

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#295]
Hi,
The EFO version in OLS is not up to date, could you check please? Says 3.10.0, should be 3.11.0.
https://www.ebi.ac.uk/ols/ontologies/efo
Many thanks,
Paola

**Comment by henrietteharmse** [comment]
I have tried to force it to update on Monday and it did not update.  Hence the reason for setting the status to bug.

**Comment by henrietteharmse** [comment]
EFO is updated now.
