### ISSUE TITLE
Odd version info showing up for Mondo

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#298]
https://www.ebi.ac.uk/ols/ontologies/mondo

shows:

```
Version IRI: http://purl.obolibrary.org/obo/mondo/releases/2019-04-06/reasoned.owl.owl/mondo.owl
Ontology id: mondo
Version: 28-10-2019
Number of terms: 23498
Last loaded: Mon Oct 28 01:27:28 GMT 2019
```

This makes it look out of date, though I confirmed this is actually the correct release as https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0020420 was added in 2019-10-25

Specifically, ols says `http://purl.obolibrary.org/obo/mondo/releases/2019-04-06/reasoned.owl.owl/mondo.owl`

however:

```
curl -s -L $OBO/mondo.obo | grep ^data-version
data-version: releases/2019-10-25/reasoned.owl.owl
```

(OK, we need to fix that wack reasoned.owl.owl thing in the mondo release, but it's not clear why ols seems to have cached an old tag?)

Also OLS says `Version: 28-10-2019`, which actually seems to be a load date rather than any version that comes from mondo

**Comment by henrietteharmse** [comment]
Well that certainly is a bug. I will look into it shortly.

**Comment by henrietteharmse** [comment]
Currently this is fixed as far as can given that we are using an old version of the OWLAPI. Currently on OLS the version of Mondo will no be displayed.

Opening this in Protege 4.3, which uses that same version of the OWLAPI as used by OLS, the ontology version is also not displayed. 

This will be fixed when we upgrade the OWLAPI. Hence the reason for closing this ticket.
