### ISSUE TITLE
‘has_exact_synonym’ is not picked up for the plana ontology

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#299]
This ticket was initially logged in RT: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=376628

I noticed that ‘has_exact_synonym’ is not being displayed in the Term Info box in the OLS. For example `multicellular organism` has (http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0000468) an exact synonym, “has_exact_synonym: multi-cellular organism”, but this does not appear in the OLS page (https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000468). Is this done for a specific reason? I am wondering because we have many exact syns in our ontology (PLANA) that we would like to be displayed and will change the type of synonym if necessary.

**Comment by henrietteharmse** [comment]
This is due to a configuration issue. OLS does not make assumptions as to what annotation(s) ontology providers use to indicate synonyms. Instead it depends on the configuration of the different ontologies to determine the annotation properties used for indicating synonyms. In the case the plana ontology, this has not been configured.

**Comment by srobb1** [comment]
@henrietteharmse Thank you!

**Comment by henrietteharmse** [comment]
@srobb1 do you want to add annotation properties that can be used to indicate synonyms for plana?

**Comment by srobb1** [comment]
Yes I would. We use has_exact_synonym.

**Comment by henrietteharmse** [comment]
@srobb1 Can you please provide the complete IRI for has_exact_synonym that you use?

**Comment by srobb1** [comment]
@henrietteharmse Yes. Here it is: http://www.geneontology.org/formats/oboInOwl#hasExactSynonym

Thank you!!

**Comment by srobb1** [comment]
@henrietteharmse 
I am having another issue similar to this one. I have comments nested with my foaf_depiction. These comments are not appearing on the ols term page, nor are they appearing in the ols json file:

[Here is the json from the OLS term page](https://www.ebi.ac.uk/ols/api/ontologies/plana/terms?iri=http://purl.obolibrary.org/obo/PLANA_0000006)

Subset of term with nested comment:
```
   <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/PLANA_0000006"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/foaf_depiction"/>
        <owl:annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/plana/images/stage6.png"/>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Depicted by field contains hematoxylin and eosin staining section of a stage 6 embryo. Scale bar = 100um</rdfs:comment>
    </owl:Axiom>
```

Complete term:
```
    <!-- http://purl.obolibrary.org/obo/PLANA_0000006 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/PLANA_0000006">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000068"/>
        <rdfs:subClassOf>
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/PLANA_0007536"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/PLANA_0000116"/>
            </owl:Restriction>
        </rdfs:subClassOf>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A stage of Smed embryonic development defined by a unique gene expression signature and morphology, 7 - 9 days post-egg capsule deposition at 20˚C. Organogenesis and morphogenesis. Definitive organ formation. Temporary embryonic cell types degenerate. Embryo elongation.</obo:IAO_0000115>
        <obo:foaf_depiction rdf:resource="http://purl.obolibrary.org/obo/plana/images/stage6.png"/>
        <oboInOwl:created_by rdf:datatype="http://www.w3.org/2001/XMLSchema#string">https://orcid.org/0000-0003-2569-1939 | https://orcid.org/0000-0002-7535-4902</oboInOwl:created_by>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:28072387</oboInOwl:hasDbXref>
        <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></oboInOwl:hasExactSynonym>
        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Schmidtea_mediterranea_Developmental_Stages</oboInOwl:hasOBONamespace>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></rdfs:comment>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Stage 6</rdfs:label>
    </owl:Class>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/PLANA_0000006"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/IAO_0000115"/>
        <owl:annotatedTarget rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A stage of Smed embryonic development defined by a unique gene expression signature and morphology, 7 - 9 days post-egg capsule deposition at 20˚C. Organogenesis and morphogenesis. Definitive organ formation. Temporary embryonic cell types degenerate. Embryo elongation.</owl:annotatedTarget>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:28072387</oboInOwl:hasDbXref>
    </owl:Axiom>
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/PLANA_0000006"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/foaf_depiction"/>
        <owl:annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/plana/images/stage6.png"/>
        <rdfs:comment rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Depicted by field contains hematoxylin and eosin staining section of a stage 6 embryo. Scale bar = 100um</rdfs:comment>
    </owl:Axiom>
```
 
Can we get this field configured to display on the term page and in the json? Is there a configuration page I can make changes and submit a pull request? 

Thank you,
Sofia

**Comment by henrietteharmse** [comment]
@srobb1 
Can you please add the last comment as a different ticket? The original ticket has been completed.

**Comment by srobb1** [comment]
Done. Thank you! https://github.com/EBISPOT/OLS/issues/346
