### ISSUE TITLE
Why is the URI for a term used to search graph relations as opposed to the ID?

### ISSUE THREAD

**Issue by Relequestual** [EBISPOT/OLS#3]
I've managed to setup Solr and import the example HP Ontology OK. After looking at the resulting schema, I can see that I can search for parents, children, ancestors, and decendants, but only by using the URI as the search term, and not the ID (which is the URI plus a prefix of the ontology name in lower case form). Why is this the case? Surely it would make sense to do relational searches based on the ID?

On another note, I can get the decendants for a term, but I have no idea on the distance of those terms from the searched term. Having that data included would save on the number of required queries I need to make.

**Comment by simonjupp** [comment]
Resolved in person.
