### ISSUE TITLE
BTO: Add hierarchical properties to config

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#303]
These three properties should be shown hierarchically in OLS:

```
http://purl.obolibrary.org/obo/BFO_0000050
http://purl.obolibrary.org/obo/RO_0002202
http://purl.obolibrary.org/obo/bto#related_to
```

Note that this change will only become apparent after the next BTO release (@BRENDA-Enzymes).

**Comment by udp** [comment]
This is now in the prod config
