### ISSUE TITLE
Synonym display in UI is ambiguous

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#305]
Consider
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000565
and the list
leukemia, leukemias, blood (leukemia), Leukemias, General, Leukemia NOS (disorder), chronic leukemia, Blood (Leukemia), Leukaemia, disease, Leukemia, disease, chronic leukemia, disease (disorder), leukemias, general, Leukaemia, leukemia, disease, Leukaemia, NOS, leukemia (disease), leukemia, malignant, Leukemia, morphology (morphologic abnormality), Leukemias

As some of the synonyms labels contain commas, it's really hard to see which are the synonyms as they are delimited by commas themselves.

Reported by @fuqiX

**Comment by henrietteharmse** [comment]
This is an issue that will be addressed once the new UI changes are ready.

**Comment by mcourtot** [comment]
Beautiful, thanks!
