### ISSUE TITLE
Update preferred root config to make use IAO_0000700

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#306]
https://github.com/information-artifact-ontology/ontology-metadata/pull/45/files
http://purl.obolibrary.org/obo/IAO_0000700

**Comment by matentzn** [comment]
@henrietteharmse can you tell me exactly how the terms need to be annotated for OLS to pick this up? is it 

1) ontology hasPreferredRoot some TERM1
or 
2) Term1 isPreferredRoot value true?

It does not matter whether this already works or not, but if I can start implementing it everywhere, then we are ready when the feature is :)

**Comment by henrietteharmse** [comment]
@matentzn 
The short answer is (1).


The longer answer:
You can update .yaml file with a `preferrred_root_term` section. Here is an example from DUO:
 ```
   preferred_root_term:
      - http://purl.obolibrary.org/obo/DUO_0000001
      - http://purl.obolibrary.org/obo/DUO_0000017
      - http://purl.obolibrary.org/obo/OBI_0000066
```

Equivalently you can add the annotation properties to the ontology. Here is the equivalent for DUO.

```
<rdf:RDF` xmlns="http://purl.obolibrary.org/obo/duo.owl#"
     xml:base="http://purl.obolibrary.org/obo/duo.owl"
     xmlns:om="http://purl.obolibrary.org/obo/iao/ontology-metadata.owl">
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/duo.owl">
        <om:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/DUO_0000017"/>
        <om:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/OBI_0000066"/>
        <om:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/DUO_0000001"/>
    </owl:Ontology>
```

**Comment by matentzn** [comment]
This is perfect, thanks!

**Comment by matentzn** [comment]
I assume this works as well:

```
<rdf:RDF` xmlns="http://purl.obolibrary.org/obo/duo.owl#"
     xml:base="http://purl.obolibrary.org/obo/duo.owl"
     xmlns:obo="http://purl.obolibrary.org/obo/">
    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/duo.owl">
        <obo:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/DUO_0000017"/>
        <obo:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/OBI_0000066"/>
        <obo:IAO_0000700 rdf:resource="http://purl.obolibrary.org/obo/DUO_0000001"/>
    </owl:Ontology>
```

**Comment by henrietteharmse** [comment]
As long as it is valid OWL it should be fine.

**Comment by matentzn** [comment]
I mean your example assumed the wrong IAO iri:

`http://purl.obolibrary.org/obo/iao/ontology-metadata.owlIAO_0000700`
because of the way your `om:` namespace unsolves..

**Comment by henrietteharmse** [comment]
@matentzn It seems like OLS has an issue with importing IAO. See screenshot below from Protege 4.

![image.png](https://images.zenhubusercontent.com/5c4881904af1e15a770fadd4/400364c2-e1e0-4d6f-8af1-42e48921bbbd)

**Comment by henrietteharmse** [comment]
@matentzn The change to using IAO_0000700 has been applied to prod.

**Comment by matentzn** [comment]
This is amazing @henrietteharmse. Just to avoid trial and error endeavours, does the following ontology correctly state that TEST:001 is supposed to be the ROOT term?

```
Prefix(:=<http://purl.obolibrary.org/obo/test.owl#>)
Prefix(owl:=<http://www.w3.org/2002/07/owl#>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns#>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
Prefix(xsd:=<http://www.w3.org/2001/XMLSchema#>)
Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema#>)
Prefix(obo:=<http://purl.obolibrary.org/obo/>)

Ontology(<http://purl.obolibrary.org/obo/test.owl>
Annotation(obo:IAO_0000700 <http://purl.obolibrary.org/obo/TEST_001>)
)
```

**Comment by henrietteharmse** [comment]
Tested with this ontology:

[duo-preferred-roots.owl.txt](https://github.com/EBISPOT/OLS/files/4268019/duo-preferred-roots.owl.txt)

**Comment by matentzn** [comment]
I will test this soon! I will let you know if everything worked as expected!
