### ISSUE TITLE
Feature request: add ability to download ontologies

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#307]
I was trying to download EFO to see how the synonyms were captured in the OWL for #305  but couldn't find a way to download the OWL from OLS - there is only a JSON format download at https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000565

I'm not sure what would be the best way to do this in the UI - I'm not sure there is a point providing an OWL download of one term only? But then if you were to provide the download of the whole file alongside the JSON it'd be slightly inconsistent - one is term level the other full ontology.

**Comment by henrietteharmse** [comment]
You can go to https://www.ebi.ac.uk/ols/ontologies. There is a download option. See screenshot
![Ontology Download](https://user-images.githubusercontent.com/32327979/70036257-4f775400-15ac-11ea-8b8b-e397b6f7a054.png)

**Comment by simonjupp** [comment]
There's also a download button on the main ontology page https://www.ebi.ac.uk/ols/ontologies/efo.

**Comment by mcourtot** [comment]
thanks for the feedback! I guess I'm biased by biosamples where we put all the download options together in the top right corner, so I was expecting one under the JSON file icon. Seems like there are plenty of alternatives I just didn't find, so closing.
