### ISSUE TITLE
Old version of GenEpiO version on OLS

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#309]
Investigate why the version of GenEpiO is old.

See original ticket on RT: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=383145

**Comment by henrietteharmse** [comment]
This ontology currently loads from here: https://raw.githubusercontent.com/GenEpiO/genepio/master/src/ontology/genepio-merged-cardfix.owl. 

We should check whether loading from https://raw.githubusercontent.com/GenEpiO/genepio/master/genepio.owl is possible.

**Comment by matentzn** [comment]
I believe we should avoid at all costs do redirect OBO ontologies ourselves. The targets of the OBO purls change all the time - we will soon be out of date.. If you think the genepio resolves to the wrong file, its better to make a ticket here: https://github.com/GenEpiO/genepio/issues/

**Comment by henrietteharmse** [comment]
Their ontology purl is http://purl.obolibrary.org/obo/genepio.owl that resolves to https://raw.githubusercontent.com/GenEpiO/genepio/master/genepio.owl.

**Comment by matentzn** [comment]
If we are not using the purl, we definitely should! Always purl!

**Comment by henrietteharmse** [comment]
My sentiments exactly, though there are cases where we don't use the ontology purl because the ontology cannot be loaded as-is. This may be the case in this instance, though I rather suspect they provided us with a temporary location and simply forgot to notify us of the availability of the purl.

**Comment by matentzn** [comment]
This is what I suspect as well.. Maybe just change to the purl and see what happens :)

**Comment by udp** [comment]
Cannot upgrade GenEpiO as the current version does not load with our version of OWL API.  We need to update OWL API for this.

**Comment by matentzn** [comment]
What is the error messages for loading genepio with the old OWLAPI version? The serialisation formats should be backwards compatible..

**Comment by udp** [comment]
This is the error when loaded with Protege 4.2.0 (which uses the same version of OWLAPI used by OLS):

<img width="952" alt="Screenshot 2020-04-02 at 09 30 54" src="https://user-images.githubusercontent.com/454895/78256550-96d90700-74f0-11ea-97f3-b2b01d1a08f4.png">

The current version of Protege loads it without any issues.

**Comment by matentzn** [comment]
Hm. Ok!

**Comment by ddooley** [comment]
So, in the interests of getting GenEpiO to load regularly in OLS, I have tried to take all the axioms that were having an OWL API problem and moved them into a separate import file that isn't included with GenEpiO by default.

Can OLS try to load the latest GenEpiO via its recommended purl: http://purl.obolibrary.org/obo/genepio.owl

Thanks!

Damion

**Comment by henrietteharmse** [comment]
I have updated the OLS config to use the OBO configured location for GenEpiO, which points to http://purl.obolibrary.org/obo/genepio.owl. It is indexing currently and should be available by tomorrow.

For interest sake, an update of OLS has gone live just now to make use of OWL API version 5.1.14.

**Comment by henrietteharmse** [comment]
The latest version is available at: https://www.ebi.ac.uk/ols/ontologies/genepio

**Comment by ddooley** [comment]
Thanks Henriette!
