### ISSUE TITLE
Duplicated ontology

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#31]
It seems that the `FBcv` ontology is duplicated:
```sh
curl 'http://www.ebi.ac.uk/ols/beta/api/ontologies?page=0&size=143' -i -s | grep preferredPrefix  | grep FBcv
        "preferredPrefix" : "FBcv",
        "preferredPrefix" : "FBcv",
```

Also, is the order with which the responses are returned (for example the order of the ontologies above) always the same?

**Comment by simonjupp** [comment]
There is another ontology called dpo that uses the same preferred prefix. The namespace field is the unique id for the ontology. 

http://www.ebi.ac.uk/ols/beta/api/ontologies/dpo

dpo is failing to load at the moment which is why you can't see from the homepage.

**Comment by lgatto** [comment]
So I need will have to use the `config/namespace` field to create the unique ontology URL to send my queries to?

**Comment by simonjupp** [comment]
Yes, config/namespace will be the stable unique id for each ontology.

**Comment by lgatto** [comment]
Great, thanks. Closing this issue, as this is solved for me.
