### ISSUE TITLE
TXPO ontology did not load correctly

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#310]
This issue was reported on RT as https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=367791.

There are 2 issues here:

(1) TXPO is an ontology that has been added to the OBO foundry recently. When trying to load this ontology, OLS has detected a number of cyclic references while trying to find all related parents that resulted in a StackOverflowException. 

build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000080 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000057 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000057 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/BFO_0000051 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0002351 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0002501 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0002350 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0002501 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0002418 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0002273 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0002522 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0000419 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0002522 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0002523 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/BFO_0000051 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0001964 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000080 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000080 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000086 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0000202 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/BFO_0000051 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000057 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0000202 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/RO_0000086 is a subclass of itself
build	03-Oct-2019 21:06:18	Cycle detected where http://purl.obolibrary.org/obo/TXPO_0002523 is a subclass of itself
build	03-Oct-2019 21:06:18	Application startup failed
build	03-Oct-2019 21:06:18	java.lang.StackOverflowError: null
build	03-Oct-2019 21:06:18		at java.util.HashMap.hash(HashMap.java:338)
build	03-Oct-2019 21:06:18		at java.util.HashMap.put(HashMap.java:611)
build	03-Oct-2019 21:06:18		at java.util.HashSet.add(HashSet.java:219)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1385)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)
build	03-Oct-2019 21:06:18		at uk.ac.ebi.spot.ols.loader.AbstractOWLOntologyLoader.fillAllRelatedParents(AbstractOWLOntologyLoader.java:1418)

(2) This ran as job OLS-ROIP-JOB1-1149 on Bamboo. The OLS loading report on 4 Oct stated that TXPO failed due to a connection issue rather than a StackOverflowException. Connection issues are typically considered to be temporary problems that will sort itself out once the network connection has been restored. A StackOverflowException has to be dealt with in order to resolve it. OLS needs to report this correctly.

**Comment by matentzn** [comment]
The TXPO editors say we should check the latest version again:

https://github.com/txpo-ontology/TXPO/issues/1

Is it still cyclic?

**Comment by matentzn** [comment]
@txpo-ontology

**Comment by udp** [comment]
Caused by an error in the txpo annotation properties:

```
<!-- http://www.w3.org/2004/02/skos/core#altLabel -->
    <owl:AnnotationProperty rdf:about=“http://www.w3.org/2004/02/skos/core#altLabel”>
        <rdfs:subPropertyOf rdf:resource=“http://www.w3.org/2004/02/skos/core#altLabel”/>
    </owl:AnnotationProperty>
```

**Comment by txpo-ontology** [comment]
Thank you. I deleted the annotation property altLabel, and updated txpo.owl.
https://github.com/txpo-ontology/TXPO/blob/master/txpo.owl

**Comment by henrietteharmse** [comment]
Currently TXPO is still not updated on OLS. We will force an update on TXPO.

**Comment by txpo-ontology** [comment]
I uploaded the new TXPO ontology to Bioportal non cyclic version ( 04/12/2020, uploaded 04/14/2020).
https://github.com/txpo-ontology/TXPO/blob/master/txpo.owl
The sane version:
https://bioportal.bioontology.org/ontologies/TXPO .
TXPO has 9,407 terms. (You can see the ontology from the download or Bioportal site).

Ontobee can also view the hierarchy. For instance, 
http://www.ontobee.org/ontology/TXPO?iri=http://purl.obolibrary.org/obo/TXPO_0001087

However, in the OLS site, the number of all terms in TXPO is still zero.
Could you tell me how to solve it?
 Thanks ,

**Comment by henrietteharmse** [comment]
A forced update for TXPO is running currently which I believe will fix the issue. I just mentioned it here so that we keep track of this for in case TXPO is still not updated after the forced update.
