### ISSUE TITLE
EDAM.owl location

### ISSUE THREAD

**Issue by joncison** [EBISPOT/OLS#315]
Could you please update the EDAM entry in OLS so that it picks up the file from here:
https://github.com/edamontology/edamontology/blob/master/releases/EDAM.owl

Thanks !

**Comment by henrietteharmse** [comment]
This update fails on OLS because it points to the html page rather than the raw github content. I think the URL you really want is: https://raw.githubusercontent.com/edamontology/edamontology/master/releases/EDAM.owl.

**Comment by joncison** [comment]
sorry, yes!

**Comment by joncison** [comment]
Hi @henrietteharmse

I made a new release of EDAM yesterday afternoon but don't yet see the update in OLS.  Do I just need to wait a bit (but I thought it got updated overnight?)

Cheers

Jon

**Comment by udp** [comment]
Hi Jon,

It should indeed have updated overnight.  We did have some problems with the update process recently which means we need to force some ontologies to update to kick off the automatic updates again, so it's possible that edam was one of those.  I have forced an update, so the new version should appear in OLS soon.

Thanks!

James

**Comment by joncison** [comment]
Thanks for the fast reply James (@udp) - it's not updated yet ... it could be good to double-check that EDAM is being pulled from the right place (directly from GitHub at location Henriette indicates above) ?

**Comment by udp** [comment]
Apologies, I should have read the whole thread!  It does seem that we are still pulling it from `http://edamontology.org/EDAM.owl`.  I will have to wait until after the indexer has completed before I can fix this.

**Comment by joncison** [comment]
OK ... no worries and thanks .. just ping me here.
