### ISSUE TITLE
DUO not updated to latest version

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#319]
https://www.ebi.ac.uk/ols/ontologies/duo shows the version dated 2019-06-05.

A new release was pushed on 2020-02-03, https://github.com/EBISPOT/DUO/releases/tag/v2020-02-03

and reflected in the main PURL, http://purl.obolibrary.org/obo/duo.owl

Can you please check whether there was a problem on your side?

**Comment by henrietteharmse** [comment]
Latest version of DUO is now on OLS.

**Comment by mcourtot** [comment]
Hi @henrietteharmse - there seems to be an issue with the file loaded. While the versionIRI is correct the tree still reflects the old version. Specifcially the term consent code was relabled as 'data use limitation', the direct subclasses 'consent primary category' and 'consent secondary category' were deprecated etc.
The OWL file at https://raw.githubusercontent.com/EBISPOT/DUO/v2020-02-03/duo.owl seems correct, and the PURL http://purl.obolibrary.org/obo/duo.owl does redirect to that file.
Can you please help?


OWL excerpt below:

    

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/DUO_0000001">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/IAO_0000027"/>
        <obo:DUO_0000041 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">data use limitation</obo:DUO_0000041>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A data item that is used to indicate consent permissions for datasets and/or materials, and relates to the purposes for which datasets and/or material might be removed, stored or used.</obo:IAO_0000115>
        <obo:IAO_0000118 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">consent code</obo:IAO_0000118>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DUO:0000001</oboInOwl:id>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">data use limitation</rdfs:label>
    </owl:Class>
    


    

```
    <owl:Class rdf:about="http://purl.obolibrary.org/obo/DUO_0000002">
        <rdfs:subClassOf rdf:resource="http://www.geneontology.org/formats/oboInOwl#ObsoleteClass"/>
        <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A categorical data item indicating the primary category the consent code belongs to according to Dyke et al. 2016.</obo:IAO_0000115>
        <obo:IAO_0000231 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">This term was depreacted as it is not used to tag datasets but instead as patterns for DUO codes capture. This is an archive specific requirement, e.g. &quot;one code from a primary category and one or more from a second category&apos;
This is better done by Schemablocks and constraining the pattern of usage of DUO terms at each archive level.</obo:IAO_0000231>
        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DUO:0000002</oboInOwl:id>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">obsolete consent code primary category</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>
```

**Comment by henrietteharmse** [comment]
@mcourtot can you please check again?

**Comment by mcourtot** [comment]
looks great, thanks!
