### ISSUE TITLE
Page size 

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#32]
Is there a limit to the page size? Would there be any drawbacks in using relatively large page sizes (say 1e3, 1e4 or larger)?

**Comment by simonjupp** [comment]
There is no limit, but we may set one in the future. The only drawback is the size of the payload and we probably don't want to encourage people downloading the entire ontology in this way,

**Comment by lgatto** [comment]
Below, I have compared downloading all GO 44049 terms, using page sizes of 20, 100, 1000, 10000 and 44049 - 1000 seems to be a good size.

![rplot001](https://cloud.githubusercontent.com/assets/384198/12177199/d7532056-b562-11e5-80f0-10fc34b32db7.png)

For the record, I did 

```r
sapply(c(20, 100, 1000, 10000, 44049),
       function(ps) system.time(terms(go, pagesize = ps)))
```
