### ISSUE TITLE
Change ontology title for mondo

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#322]
https://www.ebi.ac.uk/ols/ontologies/mondo

This looks like an old title, should no longer have monarch in title

You can use either the obo metadata or the dc:title in the ontology..

**Comment by henrietteharmse** [comment]
There seems to be 2 problems here: 

(1) The OLS configurator is not updated with the new value from the obo configuration. 
The following configuration is found in MongoDB:` "title" : "MONDO: Monarch Disease Ontology"` even though the title is configured correctly in the obo configuration file and the ontology file. 

(2) Strictly speaking, if the title is set correctly in the ontology file, it should override whatever is found in the configuration. Even though the ontology file has the correct configuration, the indexer did not update MongoDB accordingly.

**Comment by henrietteharmse** [comment]
Done. See https://www.ebi.ac.uk/ols/ontologies/mondo
