### ISSUE TITLE
Anticipated downtime due to EMBL-EBI data centre migration?

### ISSUE THREAD

**Issue by jlchang** [EBISPOT/OLS#327]
Given the following notification:
>Due to the EMBL-EBI data centre being migrated to a new physical location, some of our services will be undergoing maintenance starting at 9:00 GMT on 2 March 2020 and planning to end at 17:00 GMT on 3 April 2020. EGA submission and distribution services should be considered at-risk between these dates.

Is there anticipated downtime for EBI OLS due to this work? If yes, please share the date(s) when downtime can be expected.

**Comment by henrietteharmse** [comment]
We do not expect downtime for OLS.
