### ISSUE TITLE
Search ontologies

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#33]
I would like to search the `MS` ontology for `electrospray ionization` to exactly match [`MS:1000073`](http://www.ebi.ac.uk/ols/beta/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000073). What `query` should I use to perform this search with 
```
GET /api/search?q={query}
```

**Comment by LLTommy** [comment]
You can get a JSON response from the server, if you insert "api" in the URL in front of /ontologies/ - so for your example http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000073 would return the exact same data as JSON. 

I am not entirely sure if this anwsers your question, so let me know.

**Comment by lgatto** [comment]
Sorry, I was not clear. 

This would be the url to search for `electrospray`:
```
http://www.ebi.ac.uk/ols/beta/api/search?q=MS&ontology=electrospray&rows=20
```
which would return 4 results.

This would be the url for `ionization`
```
"http://www.ebi.ac.uk/ols/beta/api/search?q=MS&ontology=ionization&rows=20"
```
that would return 59 results.

I would like to search for `electrospray ionization`, which should return only one response, namely`MS:1000073`.

**Comment by lgatto** [comment]
I have found the solution. I need to encode the space by `%20` and do an exact search:

```
"http://www.ebi.ac.uk/ols/beta/api/search?q=electrospray%20ionization&ontology=ms&exact=TRUE&rows=20"
```
