### ISSUE TITLE
Make OLS branding a tiny bit configurable

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#332]
We would like to be able to deploy OLS instances publicly for other projects. Now that @warrenread is working on design etc, it would be great if it was possible to stick a custom branding on OLS. This is important for EBI as well, as it should not seem that EBI is responsible for some trashy content that is deployed somewhere on the web (ontologies we do not endorse etc). Is there a way to ensure that whatever design is used, it can be configured that it 

1) does not seem the instance is maintained by the EBI (of course OLS the software can still be branded)
2) We can stick a custom logo in there to say: this OLS instance is provided to you by X (Monarch Initiative etc).

@dosumis @henrietteharmse @warrenread

**Comment by mcourtot** [comment]
If there was a way to have an overall CSS for logos, themes etc that would be great.

**Comment by udp** [comment]
We have implemented a set of new configuration options in the OLS:

    #ols.customisation.debrand=true
    #ols.customisation.logo=/img/custom_logo.png
    #ols.customisation.title=My OLS Instance
    #ols.customisation.org=My Organisation
    #ols.customisation.short-title=MYOLS

These are currently in the `ebi-rebranded-merge2` branch, which will be merged when the new user interface has been tested.

**Comment by matentzn** [comment]
This is SO AWESOME! :) Cheers man. I will start working on deploying our instance soon, and I am happy to be your tester for this feature.

**Comment by matentzn** [comment]
Ping me if you thing its ready for a test ride.

**Comment by matentzn** [comment]
It would be good if we could inject our own CSS as Melanie said. There are a lot of HTML elements in the OLS instance we really don't need for a custom installation, such as the entire `global-footer`, the navbar up top and some of the buttons scattered around.. A barebones version with just the main elements and configurable CSS would be a huge selling point!

**Comment by matentzn** [comment]
Man this looks pretty awesome. Two things:
1) There is now _no_ EBI branding.. That I would probably not recommend. Maybe a nice EBI logo linking to the primary old instance in the footer would be good.
2) I couldn't get the logo to work:

I have this in my config:

```
ols.customisation.logo=/opt/ols/logo-monarch.jpg
```

Which renders correctly to:

```
<img style="height:100px;" src="/opt/ols/logo-monarch.jpg">
```

But the logo does not show up:

![image](https://user-images.githubusercontent.com/7070631/78462432-75d40a00-76da-11ea-8f4f-6ec8d7818964.png)

Does the logo have to be copied to a particular location? Does it have to be `/img/`?

**Comment by udp** [comment]
@matentzn Yes, it needs to be copied to `/img/`.  Then you can set `ols.customisation.logo=/img/logo-monarch.jpg`.

**Comment by matentzn** [comment]
The final HTML says:

```
/opt/ols/web-custom/logo-monarch.jpg
```

As path to the image, /opt/ols is the OLS home directory and the logo-monarch.jpg is in it... Not sure why it still does not show up? Any idea?

**Comment by udp** [comment]
The HTML should be `/custom/logo-monarch.jpg`.   The URL path `/custom/` is mounted to the local path $OLS_HOME/web-custom, which in your case is `/opt/ols/web-custom`.

**Comment by udp** [comment]
So
    ols.customisation.logo=/custom/logo-monarch.jpg

**Comment by matentzn** [comment]
I just tried this with chrome dev tools.. Still cant find it.. Something else must be wrong then?

OLS dockerfile:

```
# This docker file builds a base image for laoding OLS data, this image itself does not run the OLS server or deal with loading data
# to see and example of a Dockerfile for loading ontologies and running a local OLS server checkout https://github.com/HumanCellAtlas/ontology/blob/master/Dockerfile

FROM alpine:3.7

ENV PACKAGES bash mongodb openjdk8
ENV TERM=linux

RUN apk update && apk upgrade && \
    apk add $PACKAGES --no-cache && \
    rm -rf /var/cache/apk/*

ENV OLS_HOME /opt/ols
ENV SOLR_VERSION 5.5.3

RUN mkdir -p ${OLS_HOME}

ADD ols-web/target/ols-boot.war  ${OLS_HOME}
ADD ols-apps/ols-config-importer/target/ols-config-importer.jar ${OLS_HOME}
ADD ols-apps/ols-loading-app/target/ols-indexer.jar ${OLS_HOME}
ADD ols-solr/src/main/solr-5-config ${OLS_HOME}/solr-5-config

## Prepare configuration files
ADD ols-web/src/main/resources/application.properties ${OLS_HOME}

### Install solr
RUN mkdir -p /data/db \
  && cd /opt \
  && wget http://archive.apache.org/dist/lucene/solr/${SOLR_VERSION}/solr-${SOLR_VERSION}.tgz \
  && tar xzf solr-${SOLR_VERSION}.tgz

```

Monarch Dockerfile

```
FROM ebispot/ols:3.3.3

ENV OLS_HOME /opt/ols
ENV JAVA_OPTS "-Xmx5g"
ENV SOLR_VERSION 5.5.3

ADD ols/ols-config.yaml ${OLS_HOME}
ADD ols/logo-monarch.jpg ${OLS_HOME}/web-custom/
#ADD ols/obo-config.yaml ${OLS_HOME}	

RUN mkdir ${OLS_HOME}/ontologies
ADD ontologies/*.owl ${OLS_HOME}/ontologies/
RUN ls -l ${OLS_HOME}/ontologies/

## Prepare configuration files
ADD ols/application.properties ${OLS_HOME}

## Start MongoDB and 
### Load configuration into MongoDB
RUN mongod --smallfiles --fork --logpath /var/log/mongodb.log \ 
    && cd ${OLS_HOME} \ 
    && java -jar ${OLS_HOME}/ols-config-importer.jar \
    && sleep 10

## Start MongoDB and SOLR
## Build/update the indexes
RUN mongod --smallfiles --fork --logpath /var/log/mongodb.log \
  && /opt/solr-${SOLR_VERSION}/bin/solr -Dsolr.solr.home=${OLS_HOME}/solr-5-config/ -Dsolr.data.dir=${OLS_HOME} \  
  && java ${JAVA_OPTS} -Dobo.db.xrefs=https://raw.githubusercontent.com/geneontology/go-site/a94d68f4e57264db2ff3692866a680c3fb9dda9d/metadata/db-xrefs.yaml -Dols.home=${OLS_HOME} -jar ${OLS_HOME}/ols-indexer.jar  

## Expose the tomcat port 
EXPOSE 8080

CMD cd ${OLS_HOME} \
    && mongod --smallfiles --fork --logpath /var/log/mongodb.log \
    && /opt/solr-${SOLR_VERSION}/bin/solr -Dsolr.solr.home=${OLS_HOME}/solr-5-config/ -Dsolr.data.dir=${OLS_HOME} \
    && java -jar -Dols.home=${OLS_HOME} ols-boot.war
```

application config:

```
spring.data.solr.host  http://localhost:8983/solr
ols.solr.search.core ontology
ols.solr.suggest.core autosuggest
spring.data.mongodb.database ols

obo.db.xrefs https://raw.githubusercontent.com/geneontology/go-site/a94d68f4e57264db2ff3692866a680c3fb9dda9d/metadata/db-xrefs.yaml


ols.home /opt/ols
ols.obofoundry.ontology.config file:/opt/ols/obo-config.yaml
ols.ontology.config file:/opt/ols/ols-config.yaml
ols.customisation.debrand=true
ols.customisation.logo=/opt/ols/web-custom/logo-monarch.jpg
ols.customisation.title=Monarch Initiative OLS Instance
ols.customisation.org=Monarch Initiative
ols.customisation.short-title=MOOLS
```

Any idea?

**Comment by udp** [comment]
ols.customisation.logo=/opt/ols/web-custom/logo-monarch.jpg

change this to


    ols.customisation.logo=/custom/logo-monarch.jpg

and don't move the file

**Comment by matentzn** [comment]
Yeah I tried this with chrome dev tools, that should work, right? (rebuild takes 1 hour, that's why I am testing like this)

**Comment by matentzn** [comment]
![image](https://user-images.githubusercontent.com/7070631/80643471-cdaf2800-8a70-11ea-850b-4ff34678dfd7.png)

**Comment by udp** [comment]
Ah I see.  Yes that should work.  I'll investigate!

**Comment by matentzn** [comment]
we are sure this fix is on 3.x-dev, right?

**Comment by udp** [comment]
I thought it was - give me 10 mins to check some things
