### ISSUE TITLE
Issues with updating OLS on dockerhub

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#336]
I am trying to get OLS ready for [dockerhub](https://hub.docker.com/r/ebispot/ols/tags) again. So far I have encountered two issues. After building OLS with `mvn clean package`, I run a docker build. The resulting image has two problems:
1)  Running `ols-indexer.jar` produces zero output (warnings, errors etc), so I wouldn't know why its not building custom OLS images based on the main OLS image. It just gets stuck, for example when an ontology fails to load because of a cycle.
2) I cant run custom OLS container because of the following warning: `no main manifest attribute, in ols-boot.war`. Not sure why that is.

I am using [this makefile](https://github.com/EBISPOT/OLS/pull/335) to make the docker docker build.

**Comment by henrietteharmse** [comment]
(1) You need to change ols-apps/ols-loading-app/src/main/resources/logback-spring.xml for your logging requirements.
(2) Are you deploying the .war file to Tomcat? Sounds like you are trying to run it directly.

**Comment by matentzn** [comment]
(1) Ok, so I have to actually build a different version of OLS for different logging requirements? I guess that is okay for docker.
(2) This is the code that worked two years ago:

```
CMD cd ${OLS_HOME} \
    && mongod --smallfiles --fork --logpath /var/log/mongodb.log \
    && /opt/solr-${SOLR_VERSION}/bin/solr -Dsolr.solr.home=${OLS_HOME}/solr-5-config/ -Dsolr.data.dir=${OLS_HOME} \
    && java -jar -Dols.home=${OLS_HOME} ols-boot.war
```

How should this be done correctly :P Thanks @henrietteharmse

**Comment by henrietteharmse** [comment]
Can you point me to the version where this worked?

**Comment by matentzn** [comment]
I guess there are a few, but this is one that works:
https://github.com/obophenotype/ABA_Uberon/blob/master/Dockerfile

Based on this base image:
https://github.com/EBISPOT/OLS/blob/master/Dockerfile
