### ISSUE TITLE
Mondo property_value concatenates exactMatch, seeAlso annotations into a single block.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#337]
For an example see https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0024265. 

On the righthand side info box.

![image](https://user-images.githubusercontent.com/32327979/78232054-a09c4380-74cb-11ea-95ab-f3f6a0435472.png)

**Comment by udp** [comment]
This is a problem with any ontology loaded from OBO, and as with #309 cannot be fixed without updating to the latest version of OWL API.

**Comment by udp** [comment]
This seems resolved in the new UI?

**Comment by udp** [comment]
I forgot we had pushed the new OWL API to production. That's why this is now fixed. :-)
