### ISSUE TITLE
New OLS design: Preferred roots select panel overlaps with terms

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#343]
See [here](https://monarch-sandbox.cgrb.oregonstate.edu/ontologies/upheno2/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FXPO_0100969&viewMode=PreferredRoots&siblings=false) for this example:

![image](https://user-images.githubusercontent.com/7070631/78534627-672d4600-77f3-11ea-8b19-d2903e1e2a7c.png)

**Comment by matentzn** [comment]
Maybe a checkbox would be enough here anyways, and the "show siblings" should probably also be a checkbox, so something very compact like:

- [ ] Preferred roots
- [ ] Show all siblings

**Comment by henrietteharmse** [comment]
The tree overlaps with the view selection box on the right-hand. This includes the "Graph view", "Reset tree" and "Show all sibling" buttons. 

I don't think a checkbox is not really option here as preferred roots need to still be extended with slims.

An option is perhaps to move the view selection box to be above the Term Information box.

**Comment by matentzn** [comment]
Ah yeah.. Ok! Maybe just having these controls having a solid white background and the terms disappearing behind the controls? I wouldn't move the controls to where Term view is.. Maybe just find a way to make the selection box a bit more thing (buttons underneath each other) and then having white background instead of transparent.

**Comment by udp** [comment]
I made the buttons vertical and added a solid white background as suggested.

![Screenshot 2020-04-22 at 12.51.40.png](https://images.zenhubusercontent.com/5e6f70074847cb074a5fdc0f/d7fcce4f-3fe6-4412-86a9-f786122dd6ea)

**Comment by matentzn** [comment]
How hard would it be to make that menu collapsible?

**Comment by udp** [comment]
Yes, I can do that.

**Comment by matentzn** [comment]
Awesome!
