### ISSUE TITLE
Enable switching on/off downloading of an ontology

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#344]
Currently all ontologies are downloadable from OLS. However, due to licensing issues this may not be ideal for some ontologies. For this reason we need to make whether an ontology is downloadable configurable. The default should be that ontologies are downloadable.

**Comment by udp** [comment]
Code changes complete in both the new and old UI.  PR opened for old UI.

**Comment by matentzn** [comment]
Nice one.

**Comment by henrietteharmse** [comment]
There is still an issue here. For some reason some ontologies the download link is not showing even though this is not configured in the .yaml config file. See for example BCGO, EO.

**Comment by udp** [comment]
This seems resolved now.
