### ISSUE TITLE
Loading SNOMED CT

### ISSUE THREAD

**Issue by brayanrodbajo** [EBISPOT/OLS#347]
Hi. 
Can I load SNOMED CT Ontology in my local deployment of OLS?
Thanks in advance.
Best.

**Comment by matentzn** [comment]
You need to register with SNOMED to obtain their raw terminology, then translate it into OWL (they have a toolkit for that in some github repo), and then you can load it into OLS just as any other ontology! Which part of this process is a problem?

**Comment by LLTommy** [comment]
Let me also mention that SNOMED is not an ontology per se so funny things might happen and you also have to check their license which might restrict what you can do with it. (Localhost most likley is ok but don't expect to be able to use SNOMED for any public project)

**Comment by henrietteharmse** [comment]
Thanks @matentzn  @LLTommy
