### ISSUE TITLE
Term query

### ISSUE THREAD

**Issue by lgatto** [EBISPOT/OLS#35]
I construct the URL to query a term as follow:

```
http://www.ebi.ac.uk/ols/beta/api/ontologies/{ontology_prefix}
```

and add the iri of the term, replacing the `:` by a `_`

```
http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252F{term_id}
```

For example, for `GO:0098791` from `GO`, I get

```
http://www.ebi.ac.uk/ols/beta/api/ontologies/GO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0098791
```

which works as expected.

If I do the same for `Orphanet:168347` from `ORDO`, I get

```
http://www.ebi.ac.uk/ols/beta/api/ontologies/ORDO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOrphanet_168347
```

which fails

![2016-01-03-115713_786x349_scrot](https://cloud.githubusercontent.com/assets/384198/12078636/b28c76b8-b211-11e5-9384-31a2e735629e.png)

Any idea why this is?

**Comment by simonjupp** [comment]
Orphaned uses a different base URI. e.g. http://www.ebi.ac.uk/ols/beta/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_C003

The base URI for Orphanet terms http://www.orpha.net/ORDO/

```
http://www.ebi.ac.uk/ols/beta/api/ontologies/ORDO/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_168347
```

**Comment by lgatto** [comment]
Thanks! I assume I can find this out by looking at the Ontology `baseUris` field.

**Comment by simonjupp** [comment]
Yes, but you have to be careful as the base URI isn't always guaranteed to be there. For OBO ontologies it is fairly predictable, but this is something we have to try and work out when we parse the ontology. Also note this is a multivalve field, as some ontologies contain multiple baseUris. 

If you have a GO term like GO:0098743, then 'GO' is the namespace with the URI of http://purl.obolibrary.org/obo/GO_.

**Comment by lgatto** [comment]
Thanks for this clarification. I have checked and currently, the 143 ontologies have unique uri fields. Is there any place where such 'unexpected' cases would be reported?
