### ISSUE TITLE
Bottom of Tree view hidden behind Term info box

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#354]
Hi,

Not sure if this has been reported already. In OLS, terms that are deep in classification/ontology trees are hidden behind the Term info box. See e.g. [NCBITaxon:9606 (Homo sapiens)](https://www.ebi.ac.uk/ols/ontologies/ncbitaxon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_9606) 

In such cases, it'd be helpful to have an option to minimise or hide the Term info box (and, possibly, the Term relations box). Thanks.

**Comment by udp** [comment]
Thanks, I'm currently looking into some of these visual issues.  I'll also be pushing the new UI up to the test server shortly so everyone can have a look.

**Comment by paolaroncaglia** [comment]
Thanks @udp . I'll add that the issue above is especially evident when the Term info box is rich with details.

**Comment by udp** [comment]
![Screenshot 2020-04-22 at 13.09.39.png](https://images.zenhubusercontent.com/5e6f70074847cb074a5fdc0f/5c9bf54c-febb-4ff4-952c-b56eda3636d2)

I've made the term information and term relations boxes collapsible in the new UI.

**Comment by rombaum** [comment]
@udp will that really solve the problem of @paolaroncaglia ? I think the most important thing is to add to the CSS class '.tabs-content' the argument 'overflow: auto;'. 

You can have a look for that [here](https://semanticlookup.zbmed.de/ols/ontologies/ncbitaxon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_9606).

You could also change your window size(e.g. ctrl+shift+m) and the tree would be accessible. I hope this helps.

**Comment by bamboo-ols** [comment]
@rombaum Yes, I will also set the overflow option so the tree is scrollable.

**Comment by udp** [comment]
@rombaum Yes, I will also set the overflow option so the tree is scrollable.
