### ISSUE TITLE
Deleting an ontology

### ISSUE THREAD

**Issue by neobernad** [EBISPOT/OLS#355]
Hi all,

Considering that I have local OLS instance. How could I delete a certain ontology? I saw this merge  https://github.com/EBISPOT/OLS/issues/171 for 2 years ago, but I could not figure much more.

Thanks,
José Antonio

**Comment by rombaum** [comment]
You must use the argument -d when you executes the ols-indexer.jar. 

e.g.
`java -jar ols-indexer.jar -d uberon`

**Comment by neobernad** [comment]
Hello @rombaum 
That was easier than expected, thank you so much! 👍
