### ISSUE TITLE
New OLS shows wrong version and ontology IRIs

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#365]
Example:
https://www.ebi.ac.uk/ols/ontologies/mp

![image](https://user-images.githubusercontent.com/7070631/82435507-102aba00-9a9d-11ea-9620-c2fb0d2ec3de.png)

I think this is true for quite a few ontologies (I checked mp, clyh, amphx).

**Comment by udp** [comment]
This is fixed now!
