### ISSUE TITLE
Page title in browser's tab

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#368]
Hi,

In the beautiful new OLS, when looking at an ontology class, the URL is displayed in the browser's tab.
I'm nearly sure that in the old OLS, the browser's tab displayed the ontology class label. Which was really helpful as you all know how many tabs OLS users like to keep open. :-)

Thanks,
Paola

**Comment by udp** [comment]
Thanks Paola, this will be fixed in the next update!

**Comment by udp** [comment]
Should be fixed now.

**Comment by paolaroncaglia** [comment]
@udp it is, very helpful, thanks!
