### ISSUE TITLE
Missing terms in OWL file for BAo

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#370]
This request was logged via RT: https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=421334

I am trying to update our BAO taxon files using the owl file from the OLS (https://www.ebi.ac.uk/ols/ontologies/bao/download), but there are a number of missing terms (eg BAO_0003115), even though they are present on the OLS website (https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0003115&viewMode=All&siblings=false
)

These terms do not also appear to be present in http://www.bioassayontology.org/bao/bao_complete.owl either.

**Comment by udp** [comment]
I don't think there is an issue here.  The OWL file we serve is the same as the upstream bao_complete.owl.  It contains owl:imports, which ultimately lead to the definition of the mentioned BAO_0003115 in bao_vocabulary_result.owl.
