### ISSUE TITLE
Failure on Maven build of OLS due to stale URL in ols-neo4j

### ISSUE THREAD

**Issue by taylordm** [EBISPOT/OLS#371]
On building OLS-neo4j, bad gateway error from m2.neo4j.org

System: MacOS
/usr/local/homebrew/Cellar/openjdk/13.0.2+8_2: 631 files, 314.9MB
/usr/local/homebrew/Cellar/maven/3.6.3_1: 87 files, 10.7MB, built in 3 seconds

Relevant output:

[ERROR] Failed to execute goal on project ols-neo4j: Could not resolve dependencies for project uk.ac.ebi.spot:ols-neo4j:jar:3.2.1-SNAPSHOT: Failed to collect dependencies at org.springframework.data:spring-data-neo4j:jar:3.4.5.RELEASE -> org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Failed to read artifact descriptor for org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Could not transfer artifact org.neo4j:neo4j-cypher-dsl:pom:2.0.1 from/to maven-neo4j (https://m2.neo4j.org/content/repositories/releases/): Transfer failed for https://m2.neo4j.org/content/repositories/releases/org/neo4j/neo4j-cypher-dsl/2.0.1/neo4j-cypher-dsl-2.0.1.pom 502 Bad Gateway -> 

More information and full output here:
[OLS_maven_github_build_failure.txt](https://github.com/EBISPOT/OLS/files/4689000/OLS_maven_github_build_failure.txt)

**Comment by udp** [comment]
Hi, this is covered in the README:

> To build OLS, in the root directory of OLS, run: mvn clean package. Currently this will fail with the following error:
> 
> `[ERROR] Failed to execute goal on project ols-neo4j: Could not resolve dependencies for project uk.ac.ebi.spot:ols-neo4j:jar:3.2.1-SNAPSHOT: Failed to collect dependencies at org.springframework.data:spring-data-neo4j:jar:3.4.5.RELEASE -> org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Failed to read artifact descriptor for org.neo4j:neo4j-cypher-dsl:jar:2.0.1: Could not transfer artifact org.neo4j:neo4j-cypher-dsl:pom:2.0.1 from/to maven-neo4j (https://m2.neo4j.org/content/repositories/releases/): Failed to transfer file https://m2.neo4j.org/content/repositories/releases/org/neo4j/neo4j-cypher-dsl/2.0.1/neo4j-cypher-dsl-2.0.1.pom with status code 502 -> [Help 1]`
> 
> To correct this, copy the contents of the `build-fix` directory into your Maven repository under `~/m2/repository`.
>
> Run mvn clean package again. OLS should now build successfully.

**Comment by taylordm** [comment]
Thank you.
