### ISSUE TITLE
Empty dbxrefs

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#372]
The database cross-references in the Term information panels are empty. See e.g. http://www.ebi.ac.uk/efo/EFO_0005741
That term in EFO has 3 x-refs to ICD9 alone (ICD9:079.0, ICD9:136.8 and ICD9:136.9), plus others.
Same for other terms in EFO. Haven't tried other ontologies yet. 
Thanks!

**Comment by udp** [comment]
Thanks, these should be listed now.

**Comment by paolaroncaglia** [comment]
@udp thanks, they are indeed!
