### ISSUE TITLE
Problem with CL display-almost infinient repeating tree view

### ISSUE THREAD

**Issue by cerivs** [EBISPOT/OLS#376]
Tried to look up pericyte took forever to load and then has almost infinite odd looking tree.  Not sure if it is a parsing problem or if other weirdness is happening.  
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000669&viewMode=All&siblings=false
![image](https://user-images.githubusercontent.com/2602957/83687962-75a09f80-a5a1-11ea-9e19-ecdad6300195.png)

**Comment by henrietteharmse** [comment]
This issue has been resolved.
