### ISSUE TITLE
Loading UBERON causes "slowing down" error

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#378]
Hi,

If I try to load any term in UBERON, it hangs and I get a warning “A web page is slowing down your browser etc”. Doesn’t happen with ontologies with larger number of classes like GO, EFO, MONDO. Been going on for a couple of days. 

Thanks in advance for looking into it!

**Comment by henrietteharmse** [comment]
This has been resolved. Thanks to @udp.
