### ISSUE TITLE
Seemingly duplicated terms

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#379]
I might be missing something in the new OLS interface: some terms appear "duplicated"; see e.g. GO:0097189. Thanks.

**Comment by udp** [comment]
This issue should now be resolved.

**Comment by paolaroncaglia** [comment]
@udp 

> This issue should now be resolved.

I checked a couple of terms I had noted, and yes, all seems well! 
Should I come across any other, I'll open a new ticket, but hopefully there will be no need. Thanks.
