### ISSUE TITLE
missing synonyms in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#383]
Some of the synonyms for the Mondo term MONDO:0100130 adult acute respiratory distress syndrome are not displayed in OLS

See related ticket: https://github.com/monarch-initiative/mondo/issues/1712

These exact synonyms are missing in the display:
"adult respiratory distress syndrome" 
"adult respiratory distress syndrome"
"adult ARDS"

They were in the last Mondo release:
![image](https://user-images.githubusercontent.com/6722114/84805330-ee97f200-afb8-11ea-85cb-9cf087a562d7.png)

cc @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky . It'd be good to check if this is an isolated case or not. Could you please spot-check maybe another couple of Mondo terms added in your last release, and see if all of the synonyms you have are in OLS or not?
Thanks!

**Comment by udp** [comment]
Hi, thanks for the report.  I think there is a general issue with OLS only showing one synonym of the set.  I will investigate tomorrow.

**Comment by udp** [comment]
This should be resolved now.

**Comment by paolaroncaglia** [comment]
@udp 
cc @nicolevasilevsky 
Yes this seems resolved now, thanks both!
