### ISSUE TITLE
suggested mongodb install for ols broken?

### ISSUE THREAD

**Issue by turbomam** [EBISPOT/OLS#384]
I'm thinking about [building my own ols server](https://www.ebi.ac.uk/ols/docs/installation-guide). Have many mere mortals been able to do it?

CUrrent problem: I haven't been able to install mongodb following the homebrew instructions. (Installing all of the other dependencies by homebrew did work nicely.)

Could this have something to do with their increasingly commercial focus?

```Bash
(base) host:~ user$ brew install mongodb
Error: No available formula with the name "mongodb" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I have found some [mongodb via homebrew tap instructions](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/)... do you have any sense of whether this installation approach would be compatible with ols?

**Comment by udp** [comment]
Hi, on Mac it's probably easier to download the binaries for MongoDB and run it manually: http://downloads.mongodb.org/osx/mongodb-osx-x86_64-2.7.8.tgz

Have you considered deploying OLS using Docker instead?  There are instructions [in the README](https://github.com/EBISPOT/OLS#deploying-with-docker).

**Comment by henrietteharmse** [comment]
I will really suggest using docker rather than trying to set it up yourself.

**Comment by turbomam** [comment]
Great! I didn't notice that there was a Docker container. Thanks. Will try soon.
