### ISSUE TITLE
HANCESTRO reload issue

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/OLS#385]
It looks like HANCESTRO was reloaded in April this year despite there not being a new release, and the object properties appear to have been borked a bit in the process. Not urgent but I wanted to flag this here. I'm probably going to do a patch release with a few fixes sometime in July so a reload can probably wait until then.

**Comment by udp** [comment]
Thanks. Would you like us to try to reload it now, or to wait until your next update?

**Comment by daniwelter** [comment]
Waiting for the update is fine, thanks.

**Comment by daniwelter** [comment]
Revisiting this issue - HANCESTRO had a new release yesterday, which loaded fine into OLS but the object properties are now completely absent from the properties tab. Could you please find out why?

**Comment by udp** [comment]
Hi, are you referring to the axiom "hasAncestryStatus some admixed ancestry"? Maybe I'm not looking in the correct place but I don't think that is actually present in the owl file we load at `https://raw.githubusercontent.com/EBISPOT/ancestro/master/hancestro_inferred.owl`.

**Comment by daniwelter** [comment]
That would explain it. Is there a way of loading from the un-inferred file and reasoning over the ontology at loading time?

**Comment by daniwelter** [comment]
Actually, I think I know where our build process is going wrong. I'm going to fix this in a new release next week. I'm going to leave this issue open until then but I expect this will be resolved after our next release.

**Comment by udp** [comment]
We normally load the purl specified by the [OBO foundry config](https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/_config.yml), but we can override in the OLS config to load from elsewhere - I can do this for HANCESTRO if necessary. We do normally reason over every ontology at load time.

**Comment by udp** [comment]
For HANCESTRO, the OBO config points to `http://purl.obolibrary.org/obo/hancestro.owl` which redirects to `https://raw.githubusercontent.com/EBISPOT/ancestro/master/hancestro_inferred.owl`.

**Comment by daniwelter** [comment]
No, leave it as it is, I'm going to fix the inferred version of the ontology. Thanks for your help 👍

**Comment by udp** [comment]
No problem! Let me know if you need anything else.

**Comment by daniwelter** [comment]
I did a release this week and can confirm that this is now resolved.
