### ISSUE TITLE
truncated definition for Orphanet:795

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#386]
The definition for Orphanet:795 Rare form of salmonellosis is cut off in the display in OLS:

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_795

**Comment by udp** [comment]
Hi, this is actually not an OLS issue: the definition is truncated in the upstream OWL file that we index:

http://www.orpha.net/ontology/orphanet.owl

**Comment by nicolevasilevsky** [comment]
Ah - okay! Do you know where I should report this issue? I'll close this issue here. Thanks!

**Comment by nicolevasilevsky** [comment]
Oh, I see you already reported it in the proper place - thank you!
