### ISSUE TITLE
Difficulty finding "The...." ontologies

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#387]
I couldn't find DUO in OLS, as it is listed as "The data use ontology" and I was looking under "D"

I was trying to figure out where the title was coming from:
- it is not in the yaml file https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/duo.yml
- the obofoundry table lists the title as "The data use ontology" but then sorts by acronym, so it ends up at the 'right' place, http://www.obofoundry.org

On the OLS page https://www.ebi.ac.uk/ols/ontologies I can only display up to 100 entries, so a search didn't return anything for "duo" either.

Proposal:
- Have an option "All" in addition to the others to chose the number of entries to display at https://www.ebi.ac.uk/ols/ontologies
- "ignore" the, an, etc when ordering ontologies alphabetically
- order by acronym

**Comment by henrietteharmse** [comment]
Hey @mcourtot 

(1) The name is picked up from [here](https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/_config.yml): 
![image](https://user-images.githubusercontent.com/32327979/87767705-f2ff3700-c812-11ea-9cc0-b2a17841581c.png)

(2) An "All" already exists for https://www.ebi.ac.uk/ols/ontologies. 
![image](https://user-images.githubusercontent.com/32327979/87768181-aa944900-c813-11ea-87ca-631f458ea5d4.png)

(3) In the Search box on the right-hand of https://www.ebi.ac.uk/ols/ontologies you can search by "duo", which will search by acronym.

Does that perhaps meet your needs sufficiently?

**Comment by mcourtot** [comment]
Thanks for the prompt response!
(1) I'll go and update the name then :)
(2) Apologies, I had completely missed this in my view. 
(3) I think I would still recommend that "the" "an" etc by ignored for the purpose of ordering in the overall table. I didn't try to find using duo, I tried with "data use" and that didn't bring anything up. 

I think the latter points are up for your team to decide - I'll update the title in my case and this should solve my sorting issue.

Thanks again!
