### ISSUE TITLE
Issue with display of an HP term (HP:0033006 Diffuse alveolar damage)

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#389]
Hi,

I need to import an HP term in EFO, and noticed that it doesn't display properly in OLS.
The term is HP:0033006 Diffuse alveolar damage. It was created relatively recently. It's definitely in http://purl.obolibrary.org/obo/hp.owl (see Protege screenshot attached), but OLS throws an error if I search for it (see OLS screenshot attached). 
Not sure if it's an OLS issue, but other random HP terms look fine in OLS. If it's a problem with the latest HP release, there may be other, recent HP terms with the same issue. 
Pinging @matentzn as I think he helped with HP:0033006 (it was added for the COVOC project).

Thanks,
Paola 

<img width="1440" alt="Screen Shot 2020-07-21 at 15 17 25" src="https://user-images.githubusercontent.com/4982516/88059800-a6469380-cb65-11ea-9dc5-65207d9b1ff2.png">
<img width="927" alt="Screen Shot 2020-07-21 at 15 18 00" src="https://user-images.githubusercontent.com/4982516/88059816-a9da1a80-cb65-11ea-9297-6f50140d1765.png">

**Comment by matentzn** [comment]
Yeah thats true! Weirdly, the index has the term in it!

![image](https://user-images.githubusercontent.com/7070631/88231773-0aa44880-cc75-11ea-9c66-d95dd9acc3df.png)

**Comment by udp** [comment]
Thanks - definitely an OLS issue as we are throwing an error. I will check it out.

**Comment by udp** [comment]
I forced a reindex of HP and it seems to be fixed now:

https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0033006
