### ISSUE TITLE
Add mouseover showing IRI of terms

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#39]
It would be great to be able to see the IRI of related classes on mouseover - for example in this case I'd like to know whether "striated muscle" is coming in from UBERON or elsewhere.

![screen shot 2016-01-15 at 09 15 52](https://cloud.githubusercontent.com/assets/2214135/12349586/b6300a72-bb68-11e5-9209-a40b986789b9.png)

**Comment by LLTommy** [comment]
Fixed in dev, will be available when we release the next version, so I close this issue.
