### ISSUE TITLE
Obsolete term from Orphanet reported as not obsolete by OLS (Orphanet:51013)

### ISSUE THREAD

**Issue by tskir** [EBISPOT/OLS#391]
**Request:** https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_51013

**Response (excerpt):**
```json
      "label" : "OBSOLETE: Melanoma-pancreatic cancer syndrome",
      "annotation" : {
        "reason_for_obsolescence" : [ "use http://www.orpha.net/ORDO/Orphanet_404560 with label: Familial atypical multiple mole melanoma syndrome" ]
      },
      "is_obsolete" : false,
      "term_replaced_by" : null,
```

<details>
  <summary><b>Show full response</b></summary>

```json
{
  "_embedded" : {
    "terms" : [ {
      "iri" : "http://www.orpha.net/ORDO/Orphanet_51013",
      "label" : "OBSOLETE: Melanoma-pancreatic cancer syndrome",
      "description" : null,
      "annotation" : {
        "reason_for_obsolescence" : [ "use http://www.orpha.net/ORDO/Orphanet_404560 with label: Familial atypical multiple mole melanoma syndrome" ]
      },
      "synonyms" : null,
      "ontology_name" : "ordo",
      "ontology_prefix" : "ORDO",
      "ontology_iri" : "http://www.orpha.net/ontology/ORDO_en_3.0.owl",
      "is_obsolete" : false,
      "term_replaced_by" : null,
      "is_defining_ontology" : true,
      "has_children" : false,
      "is_root" : false,
      "short_form" : "Orphanet_51013",
      "obo_id" : "Orphanet:51013",
      "in_subset" : null,
      "obo_definition_citation" : null,
      "obo_xref" : null,
      "obo_synonym" : null,
      "is_preferred_root" : false,
      "_links" : {
        "self" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013"
        },
        "parents" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/parents"
        },
        "ancestors" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/ancestors"
        },
        "hierarchicalParents" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/hierarchicalParents"
        },
        "hierarchicalAncestors" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/hierarchicalAncestors"
        },
        "jstree" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/jstree"
        },
        "graph" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_51013/graph"
        }
      }
    } ]
  },
  "_links" : {
    "self" : {
      "href" : "https://www.ebi.ac.uk/ols/api/ontologies/ordo/terms?iri=http://www.orpha.net/ORDO/Orphanet_51013"
    }
  },
  "page" : {
    "size" : 0,
    "totalElements" : 1,
    "totalPages" : 1,
    "number" : 0
  }
}
```
</details>

**The issue:** even though the term has the word “obsolete" in its label and the `reason_for_obsolescence` annotation, it is not marked as obsolete in the response (`"is_obsolete" : false`), and the `term_replaced_by` points to nothing.

This was discovered by @joj0s in the process of developing the [trait to ontology curation module](https://github.com/EBIvariation/trait-curation/). Note that we didn't run a systematic search for such cases, this is something we stumbled upon by chance. There may be other similar situations.

**Comment by udp** [comment]
The problem here is that ORDO does not define that the terms are actually obsolete:

    <owl:Class rdf:about="http://www.orpha.net/ORDO/ObsoleteClass">
        <efo:definition xml:lang="en">ORPHA number no more in use. Deprecated entities are part of them. They are clinical entities thought to be unique in the past but now considered, thanks to the evolution of the knowledge, part of another clinical entity.</efo:definition>
        <rdfs:label xml:lang="en">obsolete class</rdfs:label>
    </owl:Class>

    <owl:Class rdf:about="http://www.orpha.net/ORDO/Orphanet_51013">
        <rdfs:subClassOf rdf:resource="http://www.orpha.net/ORDO/ObsoleteClass"/>
        <efo:reason_for_obsolescence xml:lang="en">use http://www.orpha.net/ORDO/Orphanet_404560 with label: Familial atypical multiple mole melanoma syndrome</efo:reason_for_obsolescence>
        <rdfs:label xml:lang="en">OBSOLETE: Melanoma-pancreatic cancer syndrome</rdfs:label>
    </owl:Class>
    

We can special case `http://www.orpha.net/ORDO/ObsoleteClass` and/or `efo:reason_for_obsolescence`, but it would be better if ORDO set `owl:deprecated` on these terms.

**Comment by matentzn** [comment]
Maybe this can be coordinated with @Orphanet (Mark). I tried to look at the ORDO pipelines but they are in private repos..

**Comment by henrietteharmse** [comment]
@udp See if we can open a ticket on Orphanet and then add the link to the Orphanet ticket here.
