### ISSUE TITLE
Not all synonyms seem to be searched?

### ISSUE THREAD

**Issue by rickbeeloo** [EBISPOT/OLS#397]
We used the web service and searched for  "domestic cattle" ([exact search URL](https://www.ebi.ac.uk/ols/search?q=domestic+cattle&groupField=iri&start=0&ontology=ncbitaxon)), however, this did not return the [expected NCBITaxon Bos Taurus entry](https://www.ebi.ac.uk/ols/ontologies/ncbitaxon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCBITaxon_9913) while this entry has "Domestic cattle" in the "has exact synonym" metadata as well as under "common name":
![image](https://user-images.githubusercontent.com/19516376/90129756-8459be80-dd69-11ea-8c66-e1cd9e9d39bf.png)

When we search for "domestic cattle" without limiting the search to NCBITtaxon alone ([search url](https://www.ebi.ac.uk/ols/search?q=Domestic+cattle))  we do find cross-references from other ontologies to the NCBItaxon entry, such as this one from MIRNAO:
![image](https://user-images.githubusercontent.com/19516376/90129835-a81d0480-dd69-11ea-9d6c-ff02881a53e4.png)
With the corresponding entry:
![image](https://user-images.githubusercontent.com/19516376/90129873-b9661100-dd69-11ea-8df7-5f5092804d66.png)

Unlike for the NCBItaxon entry there now appears a synonym list at the top of the entry "**Synonyms**: Domestic cow, Bovine, Cattle, Domestic cattle, cow". This list apparently allows us to find the NCBItaxon entry indirectly via MIRNAO, but the absence of this list for NCBItaxon prevents us from directly detecting it.  Therefore we wonder why the "has exact synonyms" are not searched/regarded as synonyms for NCBItaxon? and whether there is a way to still search this or obtain the NCBItaxon entry directly in any other way?

Thank you in advance!

**Comment by henrietteharmse** [comment]
Checking "Exact match" seems to return the results you desire. See https://www.ebi.ac.uk/ols/search?q=Bos+taurus&groupField=iri&exact=on&start=0&ontology=ncbitaxon.

**Comment by rickbeeloo** [comment]
Aah indeed, thank you!. Mind explaining why it only works with "exact match" checked?

**Comment by henrietteharmse** [comment]
Underlying Solr is using various heuristics to guess the most appropriate result and rank them accordingly. "Exact match" ignores the heuristics to some extent, not completely though. 

MIRNAO seems to work without "Exact match" mainly because it only has 5 results whereas NCBITaxon returns 109 results.
