### ISSUE TITLE
Support for searches over narrowSynonym e.g. in "Advanced search"

### ISSUE THREAD

**Issue by joncison** [EBISPOT/OLS#40]
Hi Simon

EDAM makes heavy use of "narrow" synonyms and these are also used a lot for annotation in bio.tools.  Neither OLS or BioPortal supports searches over them - and this is causing us a major headache!  Any chance of providing an option (small toggle or whatever) to support searches over "narrow" synonyms?  This would be a massive usability improvement for us.  I'll gladly refactor EDAM if we can define these in a more convenient way to support this feature (currently we just use <oboInOwl:hasNarrowSynonym>).

I can also find a developer to help implement this - in case that would be useful ??

**Comment by simonjupp** [comment]
I currently index oboInOwl:hasExactSynonym for EDAM, I can also configure it to index  oboInOwl:hasNarrowSynonym too. I'll give this a go and let you know so you can test it out.

**Comment by joncison** [comment]
Awesome!  :)  Any chance you can indicate in the UI that they are "narrow" or "exact"?  This would be the cherry on the cake ...  I'll then test it out.  I suspect it will invoke a big cleanup of EDAM synyonms, but that's a good thing ...

**Comment by simonjupp** [comment]
Hi Jon, 
Try OLS now, narrower synonyms indexed in autocomplete search for EDAM. Not in the display yet as it's a bit tricker, all synonyms just get bundled together as "synonym". We may look to change that in the future. 

Note your other annotation properties are still searched (like broader) in the advanced search, just not for autocomplete. Also, when using the search API you can restrict search to specific fields of you choice, which we might expose via the UI soon.

**Comment by joncison** [comment]
Thanks mate - the fast action really appreciated.  We will play at the Debian Med sprint this week and get back.
