### ISSUE TITLE
Issue loading GECKO

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#400]
hi - we just added GECKO to the Foundry and it should have been loaded overnight. The entry has been created - https://www.ebi.ac.uk/ols/ontologies/gecko - but no terms have been loaded. 
Can you please look into this? Let us know if we need to modify anything on our side.

cc @matentzn @beckyjackson @jamesaoverton

**Comment by henrietteharmse** [comment]
The data release failed last night. @udp is looking into it.

**Comment by mcourtot** [comment]
This now seems to be loaded but for license info #404 so closing.
