### ISSUE TITLE
License info not shown on GECKO

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#404]
https://www.ebi.ac.uk/ols/ontologies/gecko

doesn't show the cc-by license info, which is in the OWL file, https://raw.githubusercontent.com/IHCC-cohorts/GECKO/master/gecko.owl

```
xmlns:terms="http://purl.org/dc/terms/"
<terms:license rdf:resource="https://creativecommons.org/licenses/by/4.0/"/>
```

**Comment by udp** [comment]
Thanks, I've lined up a fix for this which should make it through into production soon.

**Comment by udp** [comment]
Sorry, closed this by mistake! We should be pushing the fix through today.

**Comment by mcourtot** [comment]
Wonderful, just checked (back from holidays) and all looks good, thanks!
