### ISSUE TITLE
illegal character in attribute names

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/OLS#41]
cypher queries fail when filtering on properties (attributes) with '-' in the name.

e.g. MATCH (n:Class:GO) where n.label = 'synaptic transmission' and n.annotation-in_subset = 'goslim_synapse' RETURN n

=> error: in_subset not defined (line 1, column 77 (offset: 76))

This is a problem for generic translation of all OBO annotation properties -> node properties as these follow the pattern 
fu -\> annotation-fu

**Comment by simonjupp** [comment]
You need to use back ticks but also not that the value in this index is an array of strings. So you would need to do 

MATCH (n:Class:GO) where n.label = 'synaptic transmission' and n.`annotation-in_subset` = ['goslim_synapse'] RETURN n

But this only woks when you know the exact value of the array, so this wouldn't work if the term was in multiple slims. 

However, I think this would work 

MATCH (n:Class:GO) where n.label = 'synaptic transmission' and  'goslim_synapse' in n.`annotation-in_subset` RETURN n

I am thinking to create a dedicated index for slims, so each node would be labeled with the slim name. Are you just using this to query slim annotation or do you have other types of annotation you want to query on?

**Comment by dosumis** [comment]
Ta. Didn't think to try backticks to escape.   Now working.  Just using to generate some figures.  No plans to use live so index not a priority for me.  Might be useful as a way to provide general functionality on OLS for pulling slims for ontologies (e.g. GO) where they are widely used by community.  

> Are you just using this to query slim annotation or do you have other types of annotations you want to query on?

No plans to query on any node property apart from short_form and label.  Using SOLR for lexical queries.
