### ISSUE TITLE
Submit the Ontology for Nutritional Epidemiology (ONE) to be included in OLS

### ISSUE THREAD

**Issue by cyang0128** [EBISPOT/OLS#418]
Dear, 

we are a research group from Ghent University, Belgium. We joint the European Nutritional Phenotype Assessment and Data Sharing Initiative (ENPADASI) (http://www.enpadasi.eu/), and lead the development of the Ontology for Nutritional Epidemiology (ONE). We are willing to share the ONE in OLS, therefore sending this request to include the ONE in OLS.

The ONE was developed according to authoritative guidance for nutritional epidemiology. The development and applications of the ONE has been published by the journal "Advances in Nutrition" (2019 impact factor: 7.265) and presented during the IEEE big data conference:

Yang, C.; Hawwash, D.; De Baets, B.; Bouwman, J.; Lachat, C. (2020) Perspective: Towards automated tracking of content and evidence appraisal of nutrition research. Advances in Nutrition. https://doi.org/10.1093/advances/nmaa057

Yang, C.; Ambayo, H.; De Baets, B.; Kolsteren, P.; Thanintorn, N.; Hawwash, D.; Bouwman, J.; Bronselaer, A.; Pattyn, F.; Lachat, C. (2019) An Ontology to Standardize Research Output of Nutritional Epidemiology: From Paper-Based Standards to Linked Content. Nutrients, 11, 1300. https://doi.org/10.3390/nu11061300

Yang, C., De Baets, B., & Lachat, C. (2019). From DIKW pyramid to graph database: a tool for machine processing of nutritional epidemiologic research data. In 2019 IEEE International Conference on Big Data (Big Data) (pp. 5202–5205). Los Angeles, CA, USA: IEEE. https://doi.org/10.1109/bigdata47090.2019.9006469

Could you please let us know how you would review the ontology and the materials required? Thanks a lot. Regards.

**Comment by matentzn** [comment]
Hey @cyang0128 - once your ontology is accepted at OBO (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1261), it will automatically appear on OLS!

**Comment by cyang0128** [comment]
@matentzn thanks for the information!

**Comment by henrietteharmse** [comment]
As this is already in progress via OBO, I am closing this issue. If ONE needs to be added to OLS directly rather than via OBO, this issue can be re-opened.
