### ISSUE TITLE
foaf_depiction not resolving to image

### ISSUE THREAD

**Issue by srobb1** [EBISPOT/OLS#419]
Hello,

Our foaf_depiction urls used to resolve to an image. This is no longer happening. Is there a better term we should be using to make sure this happens?

![Screen Shot 2020-09-22 at 12 33 55 PM](https://user-images.githubusercontent.com/1072991/93923006-fd84f380-fccf-11ea-859a-a3ae3d5eebe3.png)

https://www.ebi.ac.uk/ols/ontologies/plana/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPLANA_0000418

Thank you,
Sofia

**Comment by udp** [comment]
Thanks, I will investigate!

**Comment by dosumis** [comment]
I'd really like this fixed soon too.  Was planning to use it in teaching today only to discover it's no longer working.

**Comment by udp** [comment]
I've lined up a fix for this which should be deployed later today/tomorrow after the current indexer run has finished.

**Comment by udp** [comment]
Hi, this issue is now resolved.

<img width="1684" alt="Screenshot 2020-10-01 at 16 29 19" src="https://user-images.githubusercontent.com/454895/94830221-4725ba80-0403-11eb-8254-754ffad84cba.png">

**Comment by srobb1** [comment]
Excellent!! Thank you!
