### ISSUE TITLE
Mondo can now be loaded from mondo.owl

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#423]
The mondo.owl (http://purl.obolibrary.org/obo/mondo/mondo.owl) is now without this huge grid of equivalent classes and should be loaded as the default Mondo.

**Comment by henrietteharmse** [comment]
Oh that is wonderful news! I was actually looking into this to see whether is a way to load Mondo from .owl file.

**Comment by matentzn** [comment]
Finger crossed :)

**Comment by matentzn** [comment]
It seems it worked! Right?
