### ISSUE TITLE
OLS search box MONDO unresponsive 

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/OLS#424]
eg: https://www.ebi.ac.uk/ols/search?q=MONDO%3A0005260&ontology=mondo

**Comment by lcdaugherty** [comment]
The  search box is still not rendering a result- I am using safari Version 14.0 (15610.1.28.1.9, 15610)
<img width="1254" alt="ols" src="https://user-images.githubusercontent.com/14925172/95724870-d0908480-0c6e-11eb-9e7d-f350eed8fa72.png">

**Comment by henrietteharmse** [comment]
@lcdaugherty This issue has been resolved.
