### ISSUE TITLE
Remove an ontology from OLS

### ISSUE THREAD

**Issue by jiaola** [EBISPOT/OLS#428]
Hello! I'm a newbie to OLS. I set up a local OLS by running the dockerized containers with docker-compose. I was able to load some ontologies. 

Is there any way to unload an ontology in OLS? The ontology has been imported with the ebispot/ols-config-importer, and the terms are indexed with ebispot/ols-indexer. 

Before the ontology was indexed, I could simply remove it from the mongo db. But after the indexing, I'm not certain how to remove the ontology terms and the configuration cleanly. 

Thanks!

**Comment by udp** [comment]
Hi! You should be able to use the `-d` switch to the indexer. For example, to remove `efo`:

    docker run --net=host -v ols-neo4j-data:/mnt/neo4j -v ols-downloads:/mnt/downloads ebispot/ols-indexer:stable \
        -d efo

**Comment by jiaola** [comment]
It works as described. Thank you!

**Comment by matentzn** [comment]
@jiaola Hey, I am trying to create an overview of existing OntoTools installations - Is yours by any chance public?

**Comment by jiaola** [comment]
@matentzn  Not yet. I'm still working on it. But I'll let you know as soon as it is.

**Comment by matentzn** [comment]
Thank you very much :)

**Comment by matentzn** [comment]
BTW, this _might_ be interesting: https://github.com/monarch-ebi-dev/ontotools-docker-config
