### ISSUE TITLE
exactMatch and closeMatch have they been removed?

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/OLS#431]
Just wanted to check - is there a reason why exactMatch and closeMatch are no longer being displayed? 
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008728

I can still see them here but I assume this is an older version?https://ontology.dev.data.humancellatlas.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0008728
Thanks

**Comment by matentzn** [comment]
see also #425 

It is the same issue I think?

**Comment by lcdaugherty** [comment]
@matentzn yes this is same issue.  Sorry I did not spot it!

**Comment by matentzn** [comment]
No worries @lcdaugherty .. I will just close this one here then so that @henrietteharmse can prioritise the other one. Thanks for clarifying and reporting!
