### ISSUE TITLE
Add the REPRODUCE-ME ontology to OLS

### ISSUE THREAD

**Issue by Sheeba-Samuel** [EBISPOT/OLS#435]
Dear OLS Team,

it would be great if the REPRODUCE-ME could be added as Ontology to the http://www.ebi.ac.uk/ols/ service.

The REPRODUCE-ME ontology is an extension of the PROV-O and the P-Plan ontology to describe a complete path of a scientific experiment. It expresses the REPRODUCE-ME Data Model using the OWL2 Web Ontology Language (OWL2). It provides a set of classes and properties to represent a scientific experiment including its computational and non-computational steps to track the provenance of results. It describes a complete path of a scientific experiment taking into focus the use-case of biological imaging and microscopy experiments. It describes an experiment and its data, agents, activities, plans, steps, variables, instruments, materials, and settings required for its reproducibility. 

Documentation of ontology: https://w3id.org/reproduceme/

Availability of ontology in OWL format: https://github.com/Sheeba-Samuel/REPRODUCE-ME/blob/master/reproduce-me.owl

BioPortal: (http://bioportal.bioontology.org/ontologies/REPRODUCE-ME)

Publication on the  REPRODUCE-ME ontology: https://doi.org/10.22032/dbt.40396

I am looking forward to hearing your thoughts. Please let me know if you need more information from my side.

Thanks & Regards,
Sheeba Samuel
(https://w3id.org/reproduceme/research)

**Comment by udp** [comment]
Hello,

Please could you complete the attached form? If you are unsure about any of the fields just leave them blank.

thanks!

[New OLS ontology request-4.xlsx](https://github.com/EBISPOT/OLS/files/5458847/New.OLS.ontology.request-4.xlsx)

**Comment by Sheeba-Samuel** [comment]
Hello James McLaughlin,

Thanks for your reply.
Please find attached the filled form.
[New.OLS.ontology.request-4.xlsx](https://github.com/EBISPOT/OLS/files/5464557/New.OLS.ontology.request-4.xlsx)

Thanks & Regards,
Sheeba Samuel

**Comment by henrietteharmse** [comment]
This ontology is now available at: https://www.ebi.ac.uk/ols/ontologies/reproduceme
