### ISSUE TITLE
make it transparent what the ontology source is

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#439]
Sometimes OLS loads the .obo version because it's perceived to be simpler? E.g. cl.obo not cl.owl?

This should be more transparent and on the OBO side we need to coordinate with our metadata registration such that ontology headers and product types are more informative and everything is clearer

Ideally the producers of ontologies would have more say in which version is loaded - maybe could be indicated in the obo metadata (but the default should always be $idspace.owl)

Would be great is OLS could shift views via toggle but that should be other request...

**Comment by matentzn** [comment]
I totally agree. We should expose the "mirror from" uri field, saying exactly where the ontology was downloaded from. In my experience, we only ever switch to OBO format if it is somehow lossy and that was needed for some reason (Mondo was switched back to OWL afaik).

**Comment by henrietteharmse** [comment]
We can look in to doing that. 

By default we load the .owl file. It is only when the .owl file does not load that we will consider loading the .obo file. Though, loading of the .obo file only happens in consultation with the ontology provider and is only done when the ontology provider cannot provide a .owl file that we can load.

For OBO ontologies we read the `ontology_purl` key from the [OBO config](https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/_config.yml). For OBO ontologies we may have an override in the general OLS config, but again, this only happens in consultation with the ontology provider.  

For cl `ontology_purl` points to `http://purl.obolibrary.org/obo/cl.owl`. Hence, as far as I can tell we are loading the .owl file. I am very interested in knowing why you think we are loading the .obo for cl. I am concerned that it may be a symptom of something else going wrong somewhere.

**Comment by cmungall** [comment]
My mistake re: CL, I thought cl.owl had more axioms...
