### ISSUE TITLE
Clearer representation of imported terms

### ISSUE THREAD

**Issue by jmcmurry** [EBISPOT/OLS#44]
One of the recommended searches for terms is GO:0098743; however this gets you to a page with 108,611 hits the basis of which is fuzzy. The top hit is the native GO one, followed by a bunch of imports (HP, MP etc).
 
This ranking is as it should be, but not optimally clear. May I suggest...

This | Rather than this
------------------|--------------------
<img width="764" alt="screen shot 2016-02-11 at 11 49 33 am" src="https://cloud.githubusercontent.com/assets/3658863/12988448/a66c56ba-d0b5-11e5-9e40-6d33c21a9792.png"> | <img width="767" alt="screen shot 2016-02-11 at 11 41 02 am" src="https://cloud.githubusercontent.com/assets/3658863/12988221/8bcbd0ca-d0b4-11e5-9f85-d7c4fa271a25.png">

**Comment by jmcmurry** [comment]
ps. Maybe there's a good reason for this, but it isn't clear to me why this would be a result in the same search.

<img width="266" alt="screen shot 2016-02-11 at 11 54 10 am" src="https://cloud.githubusercontent.com/assets/3658863/12988589/474e66d6-d0b6-11e5-9e12-8719909e5c0e.png">

**Comment by simonjupp** [comment]
You can group by id using the filter on the left that basically does what you showed. We may move to having that as the default. 

As for the number of results, we tokenise searches on : so when you search for an id like GO:0098743, you also do a search for GO. There's some good reasons for doing this plus there's also some fuzzy matching going that will get ids that look similar. You can always select "exact" match if you want just the ids that match. I'm less concerned about the number of results being large so long as the most relevant are at the top.
