### ISSUE TITLE
Docker indexer did not work

### ISSUE THREAD

**Issue by rombaum** [EBISPOT/OLS#440]
Hi @udp 

What was the reason for commenting this line out in the commit f786478? 

https://github.com/EBISPOT/OLS/blob/b304c49c72714891c45577344bea77e425bd0b32/docker-compose.yml#L11

I was trying to start OLS via using docker-compose. When the line is commented out I will receive an indexing error when I run:

`docker run --net=host -v ols-neo4j-data:/mnt/neo4j -v ols-downloads:/mnt/downloads ebispot/ols-indexer:stable`

And I think that should be clear, because there will be no configuration for solr, when the indexer tries to save the data.

I also did not see the connection between the [container](https://hub.docker.com/layers/ebispot/ols-solr/latest/images/sha256-71ffe6b8a9b0e08e2ca5aaa6565868201d12059317bb9cb414b5b0f2ad88baaf?context=explore) at the docker hub or the [docker compose file](https://github.com/EBISPOT/OLS/blob/f786478b987a63c2522b0c74a50af312af5d87a3/docker-compose.yml) and the [Dockerfile](https://github.com/EBISPOT/OLS/blob/f786478b987a63c2522b0c74a50af312af5d87a3/solr/Dockerfile) in the solr directory. Did I miss something or is the connection missing? And that is the reason why it does not work?

I think this problem will only appear when you start with a fresh version of the docker container. Because afterwards when restarting the indexer the directory should exists. Maybe that could be the reason that the missing connection was not found in the past. By the way it was hard to find the error because with using the flag -d there were no log information by starting the containers via:

`docker-compose up -d solr mongo`

Best,

Roman

**Comment by matentzn** [comment]
This is no official response, but in the meantime you could check this:
https://github.com/monarch-ebi-dev/ontotools-docker-config

I tried to consolidate the docker-compose setup of the ontotools there, maybe it helps.

**Comment by rombaum** [comment]
@matentzn that looks very interesting for me. Thanks for the link. I will have a look into this.

Just to make that clear. My version of the OLS works locally but for that I removed the comment from line 11. And if there is someone else also struggling. I decided to write this down as an issue.

**Comment by matentzn** [comment]
Yeah! Thanks for the issue 👍 

Just FYI: we are trying to get a sense of who is using custom OLS builds [here](https://github.com/EBISPOT/ontotools-docker-config/blob/master/docs/custom_ontotools_users.md). It would be of great help if you made a ticket there briefly describing your own project(s) and scope.

**Comment by udp** [comment]
Thanks - I don't recall why this was commented out, but I think it was a mistake. I have uncommented it in the 3.x-dev branch.
