### ISSUE TITLE
Bug in displayed PRO hierarchy when term logically defined with cardinality

### ISSUE THREAD

**Issue by nataled** [EBISPOT/OLS#442]
I've noticed an issue in the default displayed hierarchy when viewing PRO:
https://www.ebi.ac.uk/ols/ontologies/pr

For this ticket, ignore the 'activity' terms that are connected directly under 'Thing', as these are due to how they are given in PRO (and will be dealt with there). Here are some examples that illustrate the problem:

phospho CD28 homodimer
osteocalcin peptide, fully carboyxylated form
secretory dimeric IgA1 immunoglobulin complex (human)
collagen alpha-1(V) chain, signal peptide removed 3-hydroxy-proline and 4-hydroxy-proline form (human)

In each case mentioned, the term appears as if it is under 'Thing' even though the logical definition gives an actual parent (for example, as indicated under 'Equivalent to' in the 'Term Relations' section, 'phospho CD28 homodimer' should be a child of 'protein-containing complex'). In each case, the logical definition also includes a cardinality restraint. I have verified that ALL such PRO terms are displayed this way, and ONLY such PRO terms are displayed this way. I have also checked other resources such as BioPortal and OntoBee; the behavior is unique to OLS.

**Comment by henrietteharmse** [comment]
This does look like it may be a bug. We will need to investigate. I tried to have a look into it now and it crashed my computer twice when I tried to download the ontology. It seems like we have some challenges to figure out what is happening here.

**Comment by nataled** [comment]
I'm not sure what specifically is needed for your tests, but I've created a small version of PRO specifically for this purpose. Here is the file location: https://proteininformationresource.org/staff/nataled/OLS_test.owl

Please let me know if changes are needed.

**Comment by henrietteharmse** [comment]
A minimal representative example! That will certainly help! Thank you!

**Comment by henrietteharmse** [comment]
This has been resolved.
