### ISSUE TITLE
Definition provenance is not always shown

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#444]
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002050

Shows:

"A melancholy feeling of sadness and despair. [ ]"

but there is an axiom annotation with source 

OBO:
def: "A melancholy feeling of sadness and despair." [NCIT:C2982]

**Comment by henrietteharmse** [comment]
This has been fixed now.
