### ISSUE TITLE
Error with config/version not updating

### ISSUE THREAD

**Issue by markmcdowall** [EBISPOT/OLS#446]
Hi,

When looking at the version of PRIDE that is available in OLS, the latest version of PRIDE seems to have been loaded at 2020-09-25, but the `config/version` described via the REST API still references an older version (`05-11-2019`):

https://www.ebi.ac.uk/ols/api/ontologies?page=2&size=100

```
{
      "ontologyId" : "pride",
      "loaded" : "2020-09-25T03:21:11.082+0000",
      "updated" : "2020-12-02T23:35:58.842+0000",
      "status" : "LOADED",
      "message" : "",
      "version" : null,
      "fileHash" : "d94da5bda5d098bb752a42ff51d67cf8fbf360dd",
      "loadAttempts" : 0,
      "numberOfTerms" : 3705,
      "numberOfProperties" : 56,
      "numberOfIndividuals" : 0,
      "config" : {
        "id" : "http://purl.obolibrary.org/obo/pride_cv.obo",
        "versionIri" : null,
        "title" : "PRIDE Controlled Vocabulary",
        "namespace" : "pride",
        "preferredPrefix" : "PRIDE",
        "description" : "The PRIDE PRoteomics IDEntifications (PRIDE) database is a centralized, standards compliant, public data repository for proteomics data, including protein and peptide identifications, post-translational modifications and supporting spectral evidence.",
        "homepage" : "https://github.com/PRIDE-Utilities/pride-ontology",
        "version" : "05-11-2019",
        "mailingList" : "https://github.com/PRIDE-Utilities/pride-ontology/issues",
        "creators" : [ ],
        "annotations" : {
          "date" : [ "06:03:2012 11:34" ],
          "saved-by" : [ "jg" ],
          "default-namespace" : [ "PRIDE" ],
          "has_obo_format_version" : [ "1.2" ],
          "auto-generated-by" : [ "OBO-Edit 2.3" ],
          "comment" : [ "I would set treat-xrefs-as-equivalent but there are some weird xrefs that would break that behaviour (PRIDE:PRIDE, value-type:xsd:string, ...)" ]
        },
        "fileLocation" : "https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride_cv.obo",
        "reasonerType" : "NONE",
        "oboSlims" : false,
        "labelProperty" : "http://www.w3.org/2000/01/rdf-schema#label",
        "definitionProperties" : [ "http://purl.obolibrary.org/obo/def" ],
        "synonymProperties" : [ "http://www.geneontology.org/formats/oboInOWL#hasExactSynonym" ],
        "hierarchicalProperties" : [ "http://purl.obolibrary.org/obo/pride_cv.obo#part_of" ],
        "baseUris" : [ "http://purl.obolibrary.org/obo/PRIDE_" ],
        "hiddenProperties" : [ ],
        "preferredRootTerms" : [ ],
        "allowDownload" : true,
        "internalMetadataProperties" : [ ],
        "skos" : false
      },
      "_links" : {
        "self" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/pride"
        },
        "terms" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/pride/terms"
        },
        "properties" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/pride/properties"
        },
        "individuals" : {
          "href" : "https://www.ebi.ac.uk/ols/api/ontologies/pride/individuals"
        }
      }
    }
```

**Comment by udp** [comment]
Hi Mark - thanks for reporting. We had a couple of issues with our last indexer run, but they are now resolved and it's running again today, so PRIDE should be updated to the latest version by tomorrow.

**Comment by udp** [comment]
I think the issue is actually that we have at some point saved an old version number from the OBO, but as the OBO file does not currently contain a version, the old version is persisted in the OLS database. We will change this behaviour to remove the old version number if no version number is present during an indexer run.

**Comment by markmcdowall** [comment]
Was looking at the PRotein ontology and there appeas to be the same issue.

https://www.ebi.ac.uk/ols/ontologies/pr

<img width="405" alt="Screenshot 2021-03-01 at 10 59 08" src="https://user-images.githubusercontent.com/462902/109488212-27abc000-7a7d-11eb-98d3-52d348b58884.png">

The linked version of pr.owl is for version 62.0, but the `version` value in the box and when using the REST API lists it as `02-10-2019`

**Comment by markmcdowall** [comment]
It looks like there is a similar issue with ChEBI as well. The listed `version` is `01-01-2020`, but the ChEBI version `196` is from `01-03-2021`:

<img width="400" alt="Screenshot 2021-03-01 at 12 06 52" src="https://user-images.githubusercontent.com/462902/109495036-9f321d00-7a86-11eb-9a38-5fd3545dabf6.png">

**Comment by udp** [comment]
This should now be resolved, in that versions are no longer returned for these ontologies as they are not provided in the upstream ontology files.
