### ISSUE TITLE
Add new prominent term request link 

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#449]
It would be great if we could add a request term link just next to "Ontology Homepage"

![image](https://user-images.githubusercontent.com/7070631/102355961-80061200-3fa4-11eb-9118-8b15e6120ab1.png)

This should simply redirect to the issue tracker of the ontology; the issue tracker URL can be found consistently in the OBO metadata under "tracker". The button could be labelled: "Request terms".

**Comment by henrietteharmse** [comment]
This is something that we are likely to add as part of the manual curation app development.

**Comment by matentzn** [comment]
Very interesting!
