### ISSUE TITLE
GO displays a huge list of direct children of root terms in spite of more specific classification

### ISSUE THREAD

**Issue by balhoff** [EBISPOT/OLS#450]
At https://www.ebi.ac.uk/ols/ontologies/go 'biological_process' shows more than 8000 direct children. However in the pre-classified version of the ontology at `http://purl.obolibrary.org/obo/go.owl`, 'biological_process' has ~30 direct children.

It seems like OLS is injecting SubClassOf relations for operands in equivalent class expressions.

For example, [negative regulation of B cell proliferation](http://purl.obolibrary.org/obo/GO_0030889) has a logical definition:

`'negative regulation of B cell proliferation' EquivalentTo biological_process and ('negatively regulates' some 'B cell proliferation')`

The published ontology asserts only these SubClassOf relations:
- `'negative regulation of B cell activation'`
- `'regulation of B cell proliferation'`
- `'negative regulation of lymphocyte proliferation'`
- `'negatively regulates' some 'B cell proliferation'`

The OLS web UI adds a direct relation to 'biological_process'. Can this be disabled?

Thank you!

**Comment by cmungall** [comment]
IMO:

I don't think OLS should inject any axioms that are not present in the released ontology.

When building the tree display and the graph display, OLS should only use the asserted axioms of the form:

 1. A SubClassOf B
 2. A SubClassOf R some B

i.e. the relational graph or existential graph (see [this blog](https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/) for motivation)

where A and B are named classes, and where R is in the set of hierarchy-driving object properties (which I think is currently hardcoded to BFO_0000050, but should be user-defined?)

I think this should be universal rather than per ontology. Ontologies can have complete control over 1 and 2.

**Comment by cmungall** [comment]
this is a big issue for other ontologies too, e.g. Mondo. Compare the view in OLS which has lots of random things floating to the root with the correct view in ontobee

I can't emphasize enough: as an ontology producer it is incredibly important for me to control how the ontology looks, and for browsers not to inject axioms into the ontology where I don't intend them

**Comment by henrietteharmse** [comment]
If I look at "biological process" of GO in OLS I 30 direct children rather 8000:
![image](https://user-images.githubusercontent.com/32327979/112119807-a051f800-8bb5-11eb-8ca6-d631e49e1301.png)

which seems to match what is shown in Protege.
![image](https://user-images.githubusercontent.com/32327979/112120173-e8711a80-8bb5-11eb-9268-ae07f22439c0.png)

What am I missing here?

**Comment by matentzn** [comment]
Protege is also using the structural reasoner - so it's again wrong. The only correct way is using the existential graph - if there is an A subclass B, add a link A--isa-->B, if there is an A subclass R some B, add an A--R-->B. The structural reasoner does more things, and wrong things. All of this will be solved by your latest push to rapid indexing!

**Comment by matentzn** [comment]
@henrietteharmse seems GO has changed its definitions; look instead at the "biological regulation" branch, which has thousands of children in Protege and OLS, while it only has three in actuality:

![image](https://user-images.githubusercontent.com/7070631/112127522-713f8480-8bbd-11eb-8c84-42dbf12f0ffc.png)


![image](https://user-images.githubusercontent.com/7070631/112127486-65ec5900-8bbd-11eb-916d-e3de02abb928.png)

**Comment by balhoff** [comment]
> seems GO has changed its definitions; look instead at the "biological regulation" branch, which has thousands of children in Protege and OLS, while it only has three in actuality

@matentzn this is right, we changed the genus of all these expressions. The problem still exists there.

**Comment by henrietteharmse** [comment]
@balhoff @cmungall Both Mondo and Go has been updated.

**Comment by balhoff** [comment]
Thanks @henrietteharmse, looks good!
