### ISSUE TITLE
How hard would it be to allow other "terminology types"

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#460]
This is just an enquiry, not a ticket to action. So it can be closed when the question is answered.

How hard would it be to allow other terminology types alongside ontologies in the OLS data model?

For example, we would like to visually (and search-wise!) distinguish:
1. Data dictionaries
2. Application ontologies
3. Domain ontologies (aka ontologies)
4. Controlled Vocabularies

In separate sections. What are the steps that would need to be done to make this possible? How much work would this be? @mcourtot @dosumis fyi

**Comment by henrietteharmse** [comment]
A visual distinction of representation is potentially viable. However, restricting search based on terminology type is an extensive effort. From a development perspective this requires changes to each layer of the OLS indexer as well as the OLS website. 
Rolling out this on the main EBI site is also likely to be challenging as it it will require every ontology in OLS to be re-indexed. Currently we estimate a complete re-index of the OLS indexes will take 3-4 weeks.

**Comment by jonquet** [comment]
Maybe just an additionnal note to mention two metadata vocabularies that can be used to store this information: 

omv:isOfType = The nature of the content of the ontology, with instance values : Application Ontology
Domain Ontology, Task Ontology, Upper Level Ontology, Vocabulary

omv:hasFormalityLevel = Level of formality of the ontology

We can also cite instances values in NKOS: 
http://wiki.dublincore.org/index.php/NKOS_Vocabularies#KOS_Types_Vocabulary
Classification scheme, Event, Schema, Gazetteer, Glossary, Semantic network, Taxonomy, Terminology, Thesaurus, Vocabulary, Dictionnary, Subject heading scheme, Synonym ring, Name authority list, Ontology
