### ISSUE TITLE
Ontology property description not showing

### ISSUE THREAD

**Issue by hrshdhgd** [EBISPOT/OLS#461]
I am new to configuring the OLS so pardon me if this is a naive question. I edited the `ols-config.yaml` to add a `definition_property:` to reflect `skos:definition` as shown below:

![Screen Shot 2021-02-05 at 8 34 09 PM](https://user-images.githubusercontent.com/5247075/107106496-95076080-67f1-11eb-9f19-fe8e23ebefe8.png)

Now after deployment when I search for a particular property `outLWSpikeNAQM`, it shows me the property information as shown below:

<img width="990" alt="Screen Shot 2021-02-05 at 8 38 38 PM" src="https://user-images.githubusercontent.com/5247075/107106645-2d9de080-67f2-11eb-884e-d2d7179908e8.png">

But when I click on the item to visit the property page, the 'Property information' is blank. Am I missing something?

<img width="1268" alt="Screen Shot 2021-02-05 at 8 39 27 PM" src="https://user-images.githubusercontent.com/5247075/107106664-41e1dd80-67f2-11eb-9567-50f688db9e85.png">

**Comment by henrietteharmse** [comment]
Can you please provide a small minimal ontology and related configuration illustrating the problem? This will help us to investigate this further.

**Comment by hrshdhgd** [comment]
Sure, the owl file for the ontology could be found [here](https://raw.githubusercontent.com/hrshdhgd/metadata_converter/master/target/neon/neon.owl) and the config setup in the `ols-config.yaml` could be found [here](https://github.com/hrshdhgd/metadata_converter/blob/master/ontotools-docker-config-master/config/ols-config/ols-config.yaml). Please let me know if you need anything else.

**Comment by henrietteharmse** [comment]
Can you please provide a **minimal** ontology illustrating the problem rather that the full ontology?

**Comment by hrshdhgd** [comment]
Sorry about that. Here's the minimal ontology.
[neon-min.owl.zip](https://github.com/EBISPOT/OLS/files/5959109/neon-min.owl.zip)

**Comment by udp** [comment]
Hi, thanks for the example - this should be fixed now!

**Comment by matentzn** [comment]
Are you sure this is fixed? seems like nothing has been merged into master since December 8!

**Comment by matentzn** [comment]
Done now closing again! Thanks!

**Comment by hrshdhgd** [comment]
Hello, 

The original issue seems to be fixed! Thank you for that.

I noticed another issue that the description shows up in the center of the page as shown below:
<img width="1322" alt="Screen Shot 2021-02-25 at 11 33 54 AM" src="https://user-images.githubusercontent.com/5247075/109193149-b064ec00-775d-11eb-8206-9bdcdcc144e6.png">

But not in here along with property Information. Does that get it from somewhere else? If, so could you please kindly direct me in the direction to make that happen?

![Screen Shot 2021-02-25 at 11 38 34 AM](https://user-images.githubusercontent.com/5247075/109193488-046fd080-775e-11eb-803b-103f48421540.png)

**Comment by matentzn** [comment]
what is the property used in you ontology for the definition? IAO:0000115?

**Comment by hrshdhgd** [comment]
No , it is SKOS definition (http://www.w3.org/2004/02/skos/core#definition)

**Comment by matentzn** [comment]
Thats probably why. @udp can you somehow configure the definition property in OLS

**Comment by matentzn** [comment]
@hrshdhgd try https://github.com/EBISPOT/OLS-Config/blob/310f76b0acd23d6ad8d2333afc506de517e228ba/ols-config-importer/ols-ontologies.yaml#L11

**Comment by hrshdhgd** [comment]
Here's my config:
<img width="897" alt="Screen Shot 2021-02-25 at 5 19 24 PM" src="https://user-images.githubusercontent.com/5247075/109232267-a78c0e80-778d-11eb-9fd7-66071367152d.png">

and here's the page:
![Screen Shot 2021-02-25 at 5 19 16 PM](https://user-images.githubusercontent.com/5247075/109232276-abb82c00-778d-11eb-8a95-9ce2657f1f69.png)

No change.

**Comment by matentzn** [comment]
But didnt you just say that your `definition_property` is http://www.w3.org/2004/02/skos/core#definition? It still seems IAO_0000115..

**Comment by hrshdhgd** [comment]
I just changed it
