### ISSUE TITLE
Adding Orthology Ontology (ORTH)

### ISSUE THREAD

**Issue by tarcisiotmf** [EBISPOT/OLS#468]
Dear Henriette Harmse,

Following up my previous email, please see in attachment the filled spreadsheet OLS ontology request.
[ORTH - OLS ontology request.xlsx](https://github.com/EBISPOT/OLS/files/6107954/ORTH.-.OLS.ontology.request.xlsx)

Thank you for your attention.

Best regards,
Tarcisio

**Comment by udp** [comment]
Hello,

ORTH is now live in OLS: https://www.ebi.ac.uk/ols/ontologies/orth

thanks,

James
