### ISSUE TITLE
Add CryEM Ontology

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/OLS#469]
Here is the email requesting that CryEM be added:

We took into account your recommendations and now we manage the PURL system with our own website (http://scipion.i2pc.es/).

Therefore, if you search for http://scipion.i2pc.es/ontology/cryoem you can check that it redirects to https://github.com/I2PC/cryoem, as well as http://scipion.i2pc.es/ontology/cryoem.owl redirects to https://raw.githubusercontent.com/I2PC/cryoem/master/cryoem.owl or http://scipion.i2pc.es/ontology/releases/2021-03-09/cryoem.owl points to https://raw.githubusercontent.com/I2PC/cryoem/v2021-03-09/cryoem.owl.

Also, since we would like to use OLS as our default ontology browser (and for that reason I've attached the spreadsheet you sent to us several weeks ago), when you look for any term you are redirected to the entry site that would exist for that term if our ontology is finally added to OLS (i.e http://scipion.i2pc.es/ontology/CRYOEM_0000001 points to https://www.ebi.ac.uk/ols/ontologies/cryoem/terms?iri=http://scipion.i2pc.es/ontology/CRYOEM_0000001).

[New OLS ontology request_filled.xlsx](https://github.com/EBISPOT/OLS/files/6114059/New.OLS.ontology.request_filled.xlsx)

**Comment by henrietteharmse** [comment]
CryEM is available at https://www.ebi.ac.uk/ols/ontologies/cryoem

**Comment by sanlopez** [comment]
Great! Thanks a lot for your help, Henriette
