### ISSUE TITLE
www.ebi.ac.uk/ontology-lookup/ results in error

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#47]
I just tried to find the OLS.

Top google result and many other pages refer to 
www.ebi.ac.uk/ontology-lookup/
which just results in an error on ebi.
Please provide a redirect. Otherwise all people coming from google are lost.

www.ebi.ac.uk/ols/
also results in errors and should redirect to 
www.ebi.ac.uk/ols/beta

Was quit difficult to get to the actual page of the OLS.

**Comment by LLTommy** [comment]
Thank you for reporting. The address www.ebi.ac.uk/ontology-lookup/ as well as www.ebi.ac.uk/ols/ usually take you to the old OLS and are correct - it's just that some of our servers go through maintenance today and are unavailable for the next couple hours. So these links should work in the afternoon. However, we suggest to use www.ebi.ac.uk/ols/beta anyway and you should not experience problems there.

**Comment by simonjupp** [comment]
Closing issue as was temporary outage
