### ISSUE TITLE
SCDO needs updating

### ISSUE THREAD

**Issue by scdodev** [EBISPOT/OLS#475]
Hi
The SCDO was updated on 15th April 2021. It now has an OBO purl. The updated owl file can be found here: https://github.com/scdodev/scdo-ontology/blob/master/scdo.owl
Please can we request that the version on OLS be updated, including the metadata records (if you have not already done so).
We have publications in review that refer to this resource as well as a SickleInAfrica Consortium Meeting next week in which the SCDO updates will be mentioned.
It would be much appreciated if these updates in OLS could be done as soon as possible.

Kind regards,
Jade Hotchkiss (SCDO curator)

**Comment by udp** [comment]
Hello,

OLS imports SCDO from the OBO foundry. Therefore, if you update the purl with the OBO foundry, it will update in OLS automatically.

**Comment by scdodev** [comment]
Thanks so much!

**Comment by scdodev** [comment]
Hi. The SCDO is still not updated in OLS. Not sure if there's a different problem?

**Comment by henrietteharmse** [comment]
Thanks for letting us know. We will force it to update the moment the current update is complete.

**Comment by matentzn** [comment]
@henrietteharmse as you know, the issue here was my fault, thanks to you and @udp for diagnosing it. The issue has now been fixed in https://github.com/scdodev/scdo-ontology/pull/14/files

So if you can try to reload SCDO, that would be great :)

**Comment by henrietteharmse** [comment]
No worries. I will follow up on this.

**Comment by henrietteharmse** [comment]
Ok, latest SCDO has been picked as part of the scheduled data release last night a got to OLS prod just now. 

![image](https://user-images.githubusercontent.com/32327979/117469708-f1436300-af4d-11eb-842a-550a37483326.png)

**Comment by matentzn** [comment]
Awesome! Thank you :)
