### ISSUE TITLE
un-loading/ removing loaded ontologies

### ISSUE THREAD

**Issue by rpandey19** [EBISPOT/OLS#478]
I have successfully following the process of 'Deploying with docker' and loaded couple of ontologies.
What's the process if I want to un-load / remove any of the loaded ontologies?
Tried removing from the config but that didn't work.

**Comment by udp** [comment]
Hi, you can use the -d option to the indexer to delete an ontology from OLS. e.g. to delete efo:

    docker run --net=host -v ols-neo4j-data:/mnt/neo4j -v ols-downloads:/mnt/downloads ebispot/ols-indexer:stable -d efo

**Comment by rpandey19** [comment]
it worked. Thanks
