### ISSUE TITLE
Remove tabs (tree & metadata) when showing individual terms

### ISSUE THREAD

**Issue by matthiaskoenig** [EBISPOT/OLS#48]
For instance

http://www.ebi.ac.uk/ols/beta/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0031966

Just write the term metadata on top of the tree or next to it. The two tabs are completely unnecessary and just hide the information. I always have to click between the two (bad UI design). 
When clicking on an individual term I am interested in the metadata, but it is always hidden in the tab.

**Comment by simonjupp** [comment]
There's some ui enhancements coming over the next couple weeks where this is one issue that will be addressed. Thanks for feedback
