### ISSUE TITLE
OLS points to old ONS ontology version 

### ISSUE THREAD

**Issue by FrancescoVit** [EBISPOT/OLS#485]
For ONS ontology (https://www.ebi.ac.uk/ols/ontologies/ons) the OLS is pointing to an old (almost 1 year) version of the ontology, and not to the most recent one (Last loaded: Wed Jul 15 10:33:27 BST 2020).
 
Latest version is found at [https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/ons.owl](url) while OLS point to https://raw.githubusercontent.com/enpadasi/Ontology-for-Nutritional-Studies/master/src/ontology/ons_release_v1.0.owl a version which was now moved to another folder.

How could I fix this?

**Comment by matentzn** [comment]
Hey @FrancescoVit - OLS and ontobee do not know where your ontology _actually_ is  - they will use http://purl.obolibrary.org/obo/ons.owl to get it [(config](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ons.yml)). You should generally give at least 10 days for changes to your ontologies to trickle through to OLS, ontobee and others. (I am not part of the OLS team, I just saw your question to Chris somewhere else and thought I would answer them both here).

**Comment by udp** [comment]
This seems fixed, please reopen if not
