### ISSUE TITLE
Ontology not updating

### ISSUE THREAD

**Issue by helenp** [EBISPOT/OLS#486]
Grabbed from twitter - Egon Willighagen <egon.willighagen@gmail.com> reports that the eNanomapper ontology is failing  - latest GUI version is 2018. Please investigate.

**Comment by matentzn** [comment]
Seems like a broken purl configured? 
http://purl.enanomapper.net/onto/enanomapper.owl

This seems to be the correct one:
http://enanomapper.github.io/ontologies/enanomapper.owl

According to https://www.enanomapper.net/ontology

**Comment by helenp** [comment]
Yep, that looks like it. Egon will confirm the URL shortly. Need better docs on 'change yr URL and yr ontology will be frozen in time like Miss Havisham'.

**Comment by matentzn** [comment]
I think someone misunderstood the meaning of the term "purl" :D

**Comment by helenp** [comment]
EBO changed all the purls at one point. Best not to go there.

**Comment by egonw** [comment]
@matentzn, right... problem with temporary funded project is the divorce at the end of the project... the new URL is this: http://enanomapper.github.io/ontologies/enanomapper.owl

**Comment by egonw** [comment]
PS, checking where in this repo to change it. Sorry I did not know/remember this repo.

**Comment by egonw** [comment]
found it! making a PR

**Comment by matentzn** [comment]
Dont worry the OLS team will do that - the config is not public any more.. :) Thanks @egonw

**Comment by matentzn** [comment]
Or at least not kept up to date :D anyways, don't worry.

**Comment by udp** [comment]
Yes it is: http://github.com/EBISPOT/OLS-Config

**Comment by egonw** [comment]
https://github.com/EBISPOT/OLS-Config/pull/5

**Comment by udp** [comment]
This is merged now, so it should be resolved!

**Comment by egonw** [comment]
Thanks, yes, I saw the 7.2 release online, thanks!
