### ISSUE TITLE
Search tool is not finding or navigating to specific terms

### ISSUE THREAD

**Issue by vmt25** [EBISPOT/OLS#490]
As per subject.
I tried searching specific ontologies with known terms and even tried the example terms 'diabetes' and 'GO:0098743'.
All attempts, even clicking on the example hyperlinks, takes me to a 'No results' page.

**Comment by M-casado** [comment]
Same problem here, using any term or ontology leads to the ``No Results!`` message. 
<img width="801" alt="Screenshot 2021-07-08 164702" src="https://user-images.githubusercontent.com/77288380/124952427-216db780-e00c-11eb-8223-933409b23b5b.png">

**Comment by cmrn-rhi** [comment]
Also experiencing this issue.

**Comment by udp** [comment]
Thanks, this is resolved now.
