### ISSUE TITLE
Question about the description field of the select api call

### ISSUE THREAD

**Issue by HowardLander** [EBISPOT/OLS#492]
Hi all:

We are making a call like the following URL: 

https://server.:xxxx/api/select?q=StudyInstrument&ontology=neurobridges_ontology

But there is no description field in the response coming back, even though the documentation for that call says that description is one of the default field set to be returned.  Our ontology uses rdfs:comment for what would be the description.  Is there a way to tell the API to use that attribute for the description field?  Alternatively, what attribute would normally be mapped to the description field?

I hope the question is well formed. All comments and suggestions are welcome.

Thanks
Howard

**Comment by henrietteharmse** [comment]
@HowardLander You can add a fieldList with the list of fields you are interested. neurobridges_ontology is not available on the EBI OLS instance, hence here is an example using efo:

https://www.ebi.ac.uk/ols/api/select?q=heart&ontology=efo&fieldList=description

OR 

You can use /search which will return a list of fields if no fieldList is specified.
https://www.ebi.ac.uk/ols/api/search?q=heart&ontology=efo

**Comment by HowardLander** [comment]
@henrietteharmse  Thanks for the response.  I think that is exactly what our portal team has done.  BTW, we have our own instance of the EBI OLS server running that has only our ontology.  It is working well.  I think this issue can now be closed.
