### ISSUE TITLE
new Mondo terms not visible in OLS

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#496]
I recently added some new terms to Mondo that were available in the [v2021-08-02 release](https://github.com/monarch-initiative/mondo/releases/tag/v2021-08-02) that are not visible in OLS, such as:

- MONDO:0100259 peroxisome biogenesis disorder due to PEX1 defect
- MONDO:0100260 peroxisome biogenesis disorder due to PEX2 defect
- MONDO:0100261 peroxisome biogenesis disorder due to PEX3 defect
- MONDO:0100262 peroxisome biogenesis disorder due to PEX5 defect

In this same release, we obsoleted several terms, which are still visible in the OLS hierarchy but if I click on them, the primary label is obsolete [disease name]. I believe that obsoleted terms are normally removed from the hierarchy, yes?

For example, Heimler syndrome was obsoleted, along with it's children, and I still see it in the hierarchy [here](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019234), but if I click on that term, it is labeled as obsolete, see [here](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100229&viewMode=PreferredRoots&siblings=false).

Thank you!

cc @Mohan-Shruthi and @matentzn

**Comment by udp** [comment]
Hi, thanks for reporting this. We do have an issue with our data release at the moment which means the API servers are lagging behind the main production servers, which would explain this inconsistent behaviour. I am looking into it and will let you know.

**Comment by nicolevasilevsky** [comment]
Thanks so much @udp!
