### ISSUE TITLE
Cannot see some ECO terms in OLS

### ISSUE THREAD

**Issue by nsuvarnaiari** [EBISPOT/OLS#499]
Hi Team, 

I am from ECO (Evidence and Conclusion Ontology) team and trying to search for some ECO terms in OLS released on 08/12/2021. Can see the terms listed in the search results but when I click on them, they are not displayed in the tree. 
Eg: turbidity measurement evidence (ECO:0006263)

Error:
Cause unknown (no exception details available)

Could you please let us know if the error is in our release file or at your end?

Thanks,
Suvvi

**Comment by udp** [comment]
Hi Suvvi, thanks for letting us know, this is fixed now!

**Comment by nsuvarnaiari** [comment]
Thanks James!
