### ISSUE TITLE
Latest CL release not in OLS yet

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#500]
Morning,
The Cell Ontology (CL) was [last released on September 9th](https://github.com/obophenotype/cell-ontology/releases/tag/v2021-09-09), but it [hasn't been loaded in OLS yet](https://www.ebi.ac.uk/ols/ontologies/cl). 
Thank you in advance,
Paola

**Comment by udp** [comment]
Thanks Paola. Our data release has been slow recently but it should hopefully come through tomorrow.

**Comment by henrietteharmse** [comment]
It is updated now!

**Comment by paolaroncaglia** [comment]
Thanks @udp and @henrietteharmse .
