### ISSUE TITLE
Update OBI

### ISSUE THREAD

**Issue by jamesaoverton** [EBISPOT/OLS#504]
OBI version 2021-08-18 was released on 2021-08-23 and is available at the standard IRI <http://purl.obolibrary.org/obo/obi.owl>. OLS still has the previous version 2021-04-06 <https://www.ebi.ac.uk/ols/ontologies/obi>. Other portals have the new version of OBI loaded, so I don't believe there are any problems with the file.

Could you please look into this for us? Thanks!

**Comment by henrietteharmse** [comment]
OBI has been updated
