### ISSUE TITLE
OLS does not handle individuals well

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#506]
https://www.ebi.ac.uk/ols/ontologies/envo/individuals?iri=https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FQ2306597

 - banner gone
 - no visual distinction between subclass and instance of in browser
 - incomplete (anonymous type assertions not shown)

See also https://github.com/EnvironmentOntology/envo/issues/1219

**Comment by henrietteharmse** [comment]
Thanks to Josh for doing an excellent job in fixing this!

![image](https://user-images.githubusercontent.com/32327979/148790683-b0abdd9d-d567-4976-9d4e-db890234bf64.png)

**Comment by cmungall** [comment]
thanks!!!
