### ISSUE TITLE
PSI-MS not updated 

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#509]
Dear @henrietteharmse 

The following ontology PSI-MS https://www.ebi.ac.uk/ols/ontologies/ms hasn't been updated in a long time: 

Version in Web: 21-11-2019
Current Version: 24:09:2021 00:00 (https://github.com/HUPO-PSI/psi-ms-CV/blob/f5edf2072ca7e6f74b747ddc268b40b2cd087f66/psi-ms.obo#L3)

The Ontology is under active update here: https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo

Best REgards 
Yasset

**Comment by henrietteharmse** [comment]
@ypriverol 

The MS ontology has last been loaded on 27 Oct 2021. 
![image](https://user-images.githubusercontent.com/32327979/140503958-fb939cc5-733e-45bc-af62-829dd9dd7ad4.png)

The issue is that OBO configuration states that the ontology_purl for MS is http://purl.obolibrary.org/obo/ms.owl.

See [MS OBO config](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_config.yml#L3912)

If you can get that updated to point to the new URL, OLS will be able to pick it up from there.

**Comment by matentzn** [comment]
(FYI the MS purl was updated on the 27 October, so now it points to the hopefully right URL):

https://wheregoes.com/trace/202110247350/

**Comment by henrietteharmse** [comment]
@matentzn Thanks that is helpful.
@ypriverol  MS is in fact up to date on OLS based on the version number: 4.1.62

**Comment by ypriverol** [comment]
The url of the project that gets updated every week is https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo This is the formal HUPO-PSI project.

**Comment by matentzn** [comment]
This is not an OLS issue though, you need to take this up with the OBO foundry: for the OBO Foundry, the OWL version of the ontology is the only thing that matters, so when you update the OBO file, you need to update the OWL file as well..

**Comment by ypriverol** [comment]
Can you help us to make this automatically?

**Comment by matentzn** [comment]
Of course. This is for example how APO does it:
https://github.com/obophenotype/ascomycete-phenotype-ontology/blob/master/.github/workflows/release.yml

using GitHub actions.. Whenever the OBO gets updated, the OWL gets updated automatically.

**Comment by ypriverol** [comment]
I will leave this open until we solve it, if that ok for you.

**Comment by matentzn** [comment]
You could move this to the PSI MS tracker and tag me in it, just so that @henrietteharmse don't stumble over this ticket here thinking they need to address it, I am happy to help you over there.

**Comment by henrietteharmse** [comment]
@ypriverol Please can you use the .owl file rather than .obo file? Currently OLS is using https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.owl.

**Comment by cmungall** [comment]
There is already an issue on the MS tracker: https://github.com/HUPO-PSI/psi-ms-CV/issues/26
