### ISSUE TITLE
Some widgets don't work when accessing via HTTPS

### ISSUE THREAD

**Issue by tburdett** [EBISPOT/OLS#51]
Reported by Gautier Koscielny:

> One minor thing I wanted to report, I’ve just noticed that the widget is not working under https
> 
> http://www.ebi.ac.uk/ols/beta/ontologies/efo/terms/graph?iri=http://www.ebi.ac.uk/efo/EFO_0005762
> https://www.ebi.ac.uk/ols/beta/ontologies/efo/terms/graph?iri=http://www.ebi.ac.uk/efo/EFO_0005762

Investigating this, it appears that the API includes the port number in the _self link when using HTTPS which is not present when using HTTP.  See, for example:
    https://www.ebi.ac.uk/ols/beta/api/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005762

Looks like a server side problem to me

**Comment by simonjupp** [comment]
Seem related to https://jira.spring.io/browse/SPR-11872
