### ISSUE TITLE
NCIt not updated

### ISSUE THREAD

**Issue by janelomax** [EBISPOT/OLS#515]
OLS hasn't updated to the latest NCIt, it's on `http://purl.obolibrary.org/obo/ncit/releases/2021-05-25/ncit.owl`

[https://www.ebi.ac.uk/ols/ontologies/ncit](https://www.ebi.ac.uk/ols/ontologies/ncit)

But looks like the latest is August:

[https://stars.renci.org/var/NCIt/releases/](https://stars.renci.org/var/NCIt/releases/)

**Comment by udp** [comment]
Thanks, I will force an update.
