### ISSUE TITLE
Include ChEBI version number

### ISSUE THREAD

**Issue by ehatton** [EBISPOT/OLS#519]
Hi OLS team, currently the version field shows `null` for the [ChEBI](https://www.ebi.ac.uk/ols/api/ontologies/chebi) ontology.

It would be really useful if you could cite the official ChEBI version e.g. `205` for the current release.

**Comment by henrietteharmse** [comment]
Yes, this is because CHEBI does not provide `owl:versionInfo`  in their ontology. You can open an issue with CHEBI at: https://github.com/ebi-chebi/ChEBI/issues.

**Comment by ehatton** [comment]
Ah I see. thank you! I'll contact ChEBI then.
