### ISSUE TITLE
API doubts

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#52]
Hi @simonjupp :
  I'm extending our ols-client java library to been able to use the new OLS. One of the functionality we 
  more use in the past was retrieve a term if we have the ontologyName and the term. It would be nice 
  if you have an entry point in the API like:  
    http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms/MS_1001767 
 
 I like the current implementation but it is quite confusing: 
 http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1001767

**Comment by simonjupp** [comment]
The URI is the only true unique id which is why the APIs uses URIs by default. If you want to use a short name or OBO id then you can also use 

http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms?short_name=MS_1001767
http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms?obo_id=MS:1001767

**Comment by ypriverol** [comment]
Great, Thanks @simonjupp
