### ISSUE TITLE
Children functionality in the API

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#53]
Hi @simonjupp :
 I would like to retrieve for an specific OBO ID all the children terms. It can be using step increase like:
   1 : all direct children
   2 : all direct children and the corresponding children

Regards 
Yasset

**Comment by LLTommy** [comment]
Hey ypriverol,
In your json reply of your webservice call, there is a field with the key "children" that provides a link.  If you do a second webservice call fetching this data, you get the children terms of your term. With this approach you can get children as well as children of children and in theory, can crawl the whole ontology if necessay.

e.g.: the json for the request 'cell aggregation' (http://www.ebi.ac.uk/ols/beta/api/ontologies/go/terms?iri=http://purl.obolibrary.org/obo/GO_0098743) gives you the link leading to a json containing 'cartilage condensation' (it's only child). If you want to crawl into the other direct, up the tree, find the parent link.

I think this should anwser your question, I can provide example code in python/javascript if you need more help - which I actually don't expect. On a side note I mention that we plan to release additional endpoints that give you the 'path to root' - if that is something you are looking for. Also, the ontology visualisation on the OLS homepage can help a lot to understand the structure of an ontology, if you want to check your results manually. 

Cheers.

**Comment by simonjupp** [comment]
There is also a "descendants" link on a term gets you all the direct children, and all the children's children. The "ancestors" link works in the other direction for parent terms.

**Comment by ypriverol** [comment]
Ok @LLTommy @simonjupp I will give a shot and let you know. BTW here the ols-client that we have before for the ols-dialog:
  ols-client: https://github.com/PRIDE-Utilities/ols-client
  ols-dialog: https://github.com/PRIDE-Toolsuite/ols-dialog
Regards 
Yasset

**Comment by ypriverol** [comment]
@simonjupp @LLTommy It is not clear for me if you have some king of pagination for the children, I can find a single example with pagination for the children. I can asume that the children URL will always contains all the children terms?

**Comment by simonjupp** [comment]
All resource results are paginated. The default per page is 20, but you can
set higher limits.

See http://www.ebi.ac.uk/ols/beta/docs/api#overview-pagination

As this is HATEOAS you also get the links for next page which you should
follow rather than constructing URLs manually  e.g.

http://www.ebi.ac.uk/ols/beta/api/ontologies/go/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0043226/descendants

**Comment by ypriverol** [comment]
Thanks @simonjupp .. let me check here.

**Comment by ypriverol** [comment]
I will close this issue, problem solve +1
