### ISSUE TITLE
About annotations details

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#54]
@simonjupp for the annotation details in PSI-MOD:
 I always get an object like this: 
   
```json
database_cross_reference: [
"DiffFormula:",
"MassMono:",
"Formula:",
"TermSpec:",
"MassAvg:",
"DiffAvg:",
"DiffMono:",
"Origin:",
"Source:"
]
```
See example (http://www.ebi.ac.uk/ols/beta/api/ontologies/mod/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMOD_00816) where I can retrieve those values?

**Comment by simonjupp** [comment]
This is actually bug that we are currently fixing. We only noticed recently that for some ontologies we are not handling database cross refs properly. I'll let you know when this is fixed and how this will look like in the API ASAP

**Comment by ypriverol** [comment]
@simonjupp I understand but can you point me what would be the general representation. Are your planning to put there a link or the actual value? Can you sent me an working example?

**Comment by ypriverol** [comment]
@simonjupp we are happy with the current implementation. I will close the issue. In ols-client is already supported the dev version.
