### ISSUE TITLE
CHMO has incorrect metadata

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#542]
OLS shows:

Ontology IRI:  http://purl.obolibrary.org/obo/chmo.owl
Version IRI:  http://purl.obolibrary.org/obo/chmo/releases/2014-11-20/chmo.owl
Ontology ID: chmo
Version: 14-11-2019
Number of terms: 3084
Last loaded: Thu Jun 17 03:17:23 BST 2021

license
http://creativecommons.org/licenses/by/4.0/

saved-by
batchelorc

has obo format version
1.2

Problems:

 * How can it have Version of 14-11-2019 and a versionIRI of 2014-11-20?
     - I suspect this is something to do with CHMO not including a versionIRI in its header and OLS caching old version?
     - The actual last release would 2019-11-14 (note OBO dates should **ALWAYS** be ISO 8601)
     - No idea where 2014-11-20, but this gives a mistaken impression CHMO has not been updated in > 7 years
 * the 'has obo format version' field is not in chmo.owl
     - I suspect that maybe OLS has a pointer to the obo format version and this gets injected in the conversion?
 * same with saved-by

It would be wonderful if OLS could add more metadata about provenance of the load to make debugging this kind of thing easier

**Comment by henrietteharmse** [comment]
@cmungall  The version issue is fixed as far as I can see.

As for `has obo format version` comes from  http://purl.obolibrary.org/obo/chmo.owl. 

```
        <oboInOwl:hasOBOFormatVersion rdf:datatype="http://www.w3.org/2001/XMLSchema#string">1.2</oboInOwl:hasOBOFormatVersion>
```
and 

```
    <owl:AnnotationProperty rdf:about="http://www.geneontology.org/formats/oboInOwl#hasOBOFormatVersion">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">has_obo_format_version</rdfs:label>
    </owl:AnnotationProperty>
```
`saved-by` comes from 

```
<oboInOwl:saved-by rdf:datatype="http://www.w3.org/2001/XMLSchema#string">batchelorc</oboInOwl:saved-by>

```
also in  http://purl.obolibrary.org/obo/chmo.owl.
