### ISSUE TITLE
How to execute ols-indexer.jar at Tomcat runtime ?

### ISSUE THREAD

**Issue by chenkun19960427** [EBISPOT/OLS#543]
Hi,

I successfully ran OLS locally .

But I found that ols-Indexer. jar could not be executed at Tomcat runtime . Error message :
```
Caused by: java.io.IOException: Unable to lock org.neo4j.io.fs.StoreFileChannel@2e93ff6b
	at org.neo4j.io.fs.FileLock.wrapFileChannelLock(FileLock.java:41)
	at org.neo4j.io.fs.FileLock.getOsSpecificFileLock(FileLock.java:99)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.tryLock(DefaultFileSystemAbstraction.java:85)
	at org.neo4j.kernel.StoreLocker.checkLock(StoreLocker.java:74)
	... 136 common frames omitted
```

MongoDB - olsadmin - FAILED - message:
```
Error starting org.neo4j.kernel.EmbeddedGraphDatabase, OLS_HOME/neo4j
```

I noticed a sentence in the document https://www.ebi.ac.uk/ols/docs/installation-guide:
```
In contrast to that, the local tomcat server has to be down before running the ols-indexer.jar
```

Does that mean I have to restart Tomcat every time I update the index ?

Best Regards

**Comment by serjoshua** [comment]
hi @chenkun19960427, 

To answer your question, yes unfortunately. The local tomcat server running with OLS is using the same index files as Solr and Neo4J, it is then mandatory to shutdown the tomcat before running the indexer.

**Comment by chenkun19960427** [comment]
Hi, @serjoshua 

Thank you very much for your reply !

I'm going to write a timer to shut down Tomcat periodically and then execute the ols-indexer.jar .

Happy New Year !

Best Regards
