### ISSUE TITLE
Term endpoint broken? Moved permanently?

### ISSUE THREAD

**Issue by turbomam** [EBISPOT/OLS#546]
The sample query for the Term endpoint seems to be broken

```shell
curl \
    -L 'http://www.ebi.ac.uk/ols/api/ontologies/go/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0043226' \
    -i -H 'Accept: application/json'
```

> HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Date: Wed, 26 Jan 2022 23:28:42 GMT
Location: https://www.ebi.ac.uk/ols/api/ontologies/go/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0043226
Connection: Keep-Alive
Content-Length: 0

> HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=UTF-8
Strict-Transport-Security: max-age=0
Date: Wed, 26 Jan 2022 23:28:42 GMT
X-Application-Context: application:8080
Transfer-Encoding: chunked
Content-Language: en-US

**Comment by serjoshua** [comment]
Hi @turbomam, thanks for reporting. This has been resolved. Let us know if you are still experiencing the issue.

**Comment by turbomam** [comment]
I agree, the Terms endpoint works again now.

Thanks!
