### ISSUE TITLE
Evidence and Conclusion Ontology (ECO) not updated since Dec, 2021

### ISSUE THREAD

**Issue by nsuvarnaiari** [EBISPOT/OLS#549]
Hi OLS Team,

I have noticed that OLS does not display the latest ontology (Jan release - https://github.com/evidenceontology/evidenceontology). Could you take a look and let me know if there is any issue with the ontology?

Thanks,
Suvvi

**Comment by nsuvarnaiari** [comment]
Thanks so much for a super quick reply James.

Suvvi

**Comment by henrietteharmse** [comment]
@nsuvarnaiari ECO has been updated in OLS!

**Comment by nsuvarnaiari** [comment]
Thanks @henrietteharmse !
