### ISSUE TITLE
Search looks like exact match rather than contains

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#55]
@simonjupp  I was expecting for this search query: 
    http://www.ebi.ac.uk/ols/beta/api/search?q=modi&queryFields=label
lot of results because basically every term that contains "*modi*" should be reported. In contrast, the output is only three terms. Can you check this.

**Comment by ypriverol** [comment]
@simonjupp 
  Related with the search API. Can you check the header of the search json. I'm trying to parse it and I'm 
  receiving and error like no content-type.

**Comment by LLTommy** [comment]
The search engine does support different types of search queries - they are solr based. For example if I add a wildcard to your query ( http://www.ebi.ac.uk/ols/beta/api/search?q=modi*&queryFields=label) I get 1753 results and for two wild cards http://www.ebi.ac.uk/ols/beta/api/search?q=*modi*&queryFields=label I get 5100. 

About the content-type question: Are we talking about firefox here?

**Comment by ypriverol** [comment]
@LLTommy Thanks for the clarification, the problem is that you have something called exact a s parameter. Then, I was expecting a different behaviour (like @simonjupp explain me). I guess the exact is for UpperCase?. 

About the content-type is for my RestClient. The header of the search pages results (json) is different than the other pages.

**Comment by LLTommy** [comment]
Ok, we are aware of the problem with the header type. Firefox is the only browser that complains about the content type, the other browser don't seem to care so we saw this as low priority. However, since your java (or whatever) client is also complaining, we have a good reason now to take care of this header thing and we will.

**Comment by ypriverol** [comment]
@LLTommy Can you give to this high-priority because our RestClient is not responding when we do search. 

BTW: @LLTommy @simonjupp would be nice if you use a kind of tagging system for the issues, to been able to found if you are working on this or not. Also the type of priority for each issue.

**Comment by simonjupp** [comment]
@ypriverol The default search endpoint does not support edge ngrams. You generally wouldn't want this either. In the default search a search for "liver" would find both "liver" and "liver disease". If you specify the exact parameter it will only return "liver". All searches are case insensitive. 

If you want edge ngram searching, for things like autocomplete, you should use either a wildcard * as @LLTommy suggested, or you might want to use our dedicated "select" endpoint for these kinds of searches. it is specifically tuned for autocomplete

e.g. http://www.ebi.ac.uk/ols/beta/api/select?q=modi&ontology=mod

**Comment by simonjupp** [comment]
The content type is easily fixable and I'll have something to test later today.

**Comment by ypriverol** [comment]
Great, Thanks @LLTommy and @simonjupp. I got the idea. Let me know when the content type is ready, then we can test

**Comment by LLTommy** [comment]
You should be able to test the correct content/type header now.

**Comment by ypriverol** [comment]
Production? or DEv?

**Comment by ypriverol** [comment]
Content-type fixed. 

+1

**Comment by ypriverol** [comment]
@simonjupp and @LLTommy I'm trying to run this query: 

http://www.ebi.ac.uk/ols/beta/api/search?q=*test*&queryFields=label,synonyms&rows=100&start=0&ontology=bto

**not results at all.**

if we run this:

http://www.ebi.ac.uk/ols/beta/api/search?q=*testis*&queryFields=label,synonyms&rows=100&start=0&ontology=bto

related with this issue: https://github.com/PRIDE-Utilities/ols-client/issues/3

**Comment by LLTommy** [comment]
You get no results at all, because you should use synonym instead of synonym*s*. So if I use http://www.ebi.ac.uk/ols/beta/api/search?q=*test*&queryFields=label,synonym&rows=100&start=0&ontology=bto I do get results.

**Comment by LLTommy** [comment]
I think all issues mentioned in here are solved, so I close this.
