### ISSUE TITLE
Links from Term Info redirect wrong

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/OLS#551]
related https://github.com/monarch-initiative/mondo/issues/4479

If you go here https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http://purl.obolibrary.org/obo/MONDO_0016525

and hover over any of the exactMatch URLs they redirect to https://www.ebi.ac.uk/ols/ontologies/mondo/$1 instead of whatever the link says.. Should either resolve internally in OLS or go out (probably going out is saver?).

![image](https://user-images.githubusercontent.com/7070631/153914981-651eeaaf-5758-4ee9-a12a-205de4791b40.png)

**Comment by jamesamcl** [comment]
Thanks Nico, I will investigate!

**Comment by henrietteharmse** [comment]
Seems to be working as far as I can see.
