### ISSUE TITLE
OLS webpage documentation broken link

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/OLS#556]
The link to which one is redirected when clicking on its **Documentation** tab, ``https://www.ebi.ac.uk/ols/docs``, appears to be broken. The landing URL is ``https://www.ebi.ac.uk/ols/docs/index``, which appears to be empty (see image below). Tried with both Google Chrome and Microsoft Edge web browsers. 

![image](https://user-images.githubusercontent.com/77288380/154490706-952ed448-40cf-434f-8f99-57543a0b058c.png)

**Comment by henrietteharmse** [comment]
Thanks for reporting this! We are aware of this and will have a fix for it in next week.
