### ISSUE TITLE
Wrong CURIE linked to "dye role"

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/OLS#559]
The ``dye role`` term, currently [``CHEBI:37960``](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37960), corresponds to ``cyanine dye`` in the Chemical Entities of Biological Interest (ChEBI) ontology. I think this corresponds to a specific dye using the ``dye role``, which in ChEBI corresponds to [``CHEBI:37958``](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37958) (the correct CURIE). 
![image](https://user-images.githubusercontent.com/77288380/154742913-722585ac-5e5e-4838-9329-477351e0901d.png)

**Comment by henrietteharmse** [comment]
OLS does not change any information of any of its ontologies. Please open this as an issue with EFO.

**Comment by M-casado** [comment]
> OLS does not change any information of any of its ontologies. Please open this as an issue with EFO.

Understood, thank you.
