### ISSUE TITLE
Name of one of the Ontology [MFOMD]

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#56]
@simonjupp this is the name of the MFOMD ontology: 
   **The Mental Disease Ontology was first described in the publication 'Foundations for a realist ontology of mental disease' (Barry Smith and Werner Ceusters) which is available at http://www.jbiomedsem.com/content/1/1/10 .**

This looks more like the description than a title and is breaking all of our tools. If is the right name please let us know to change our interfaces. See the web-page in OLS: http://www.ebi.ac.uk/ols/beta/ontologies/mfomd

Regards 
Yasset

PD: This ontology was not included in the previous ols.

**Comment by LLTommy** [comment]
I am afraid, this is the name they provide in their file and that is why OLS picks it up - we all agree that this is not looking nice. Anyway, if I remember correctly we told them about it and asked them to change their title in their file, didn't we? @simonjupp I don't know right now what's the best way to go for you.

**Comment by ypriverol** [comment]
I will update my Desktop client anyways. Thanks

**Comment by simonjupp** [comment]
reported in jannahastings/mental-functioning-ontology#3

**Comment by ypriverol** [comment]
I will close the issue. I also changed my client side for future inconsistencies.
