### ISSUE TITLE
Difference of obo-config.yaml and ols-config.yaml

### ISSUE THREAD

**Issue by giraygi** [EBISPOT/OLS#560]
@udp @henrietteharmse 
We will appreciate if there was a guidance in OLS documentation about when to use obo-config.yaml  and when to use ols-config.yaml while adding an ontology to a particular terminology service based on OLS. We are also curious about technical differences of these two files such as their interfaces or the way they store information. So far, we observed some of our third party applications in TIB do not handle  obo-config and ols-config based configurations with the same behaviour.

Thank you very much for your replies or updates in documentation in advance.
All the Best,

**Comment by henrietteharmse** [comment]
This is described under Configurations at https://www.ebi.ac.uk/ols/docs/installation-guide.
OLS will load obo-config first, ols-config second. Any ols-config will override obo-config.

**Comment by giraygi** [comment]
> This is described under Configurations at https://www.ebi.ac.uk/ols/docs/installation-guide. OLS will load obo-config first, ols-config second. Any ols-config will override obo-config.

@henrietteharmse 

Thank you very much for the reply. We were able to identify the difference last week. Ontologies in obo-config.yaml are assigned an automatic "http://purl.obolibrary.org/obo/" based base_uri whereas ontologies in ols-config.yaml are not assigned an automatic base_uri. It is rather required to manually assign base_uri values for each non-obo ontology in ols-config.yaml.
