### ISSUE TITLE
OLS UI creates invalid hyperlinks from annotations of terms

### ISSUE THREAD

**Issue by jonrkarr** [EBISPOT/OLS#569]
For example, in https://www.ebi.ac.uk/ols/ontologies/kisao/terms?iri=http%3A%2F%2Fwww.biomodels.net%2Fkisao%2FKISAO%23KISAO_0000496, the OLS UI shows a hyperlink for `http://identifiers.org/biomodels.kisao/KISAO_0000019]` rather than `http://identifiers.org/biomodels.kisao/KISAO_0000019`.

This was noticed by [Fengkai Zhang](https://www.linkedin.com/in/fengkai-zhang-8aba2018).

**Comment by serjoshua** [comment]
Hello Jonathan,

We are already looking into it. Thank you for raising this issue.

**Comment by serjoshua** [comment]
Hi Jonathan,

Apologies if it took us months to get back to you regarding this issue. The reason for this is that the approach to display class/term information was streamlined. At the same time, we had a huge release to handle locale language (multilang) for ontologies.

As for the URLs in annotation _values_ of some classes (in this case KISAO:0000496), initially, our templates automatically format them to be displayed as a hyperlink, which is not the intention thus creating a broken link. We corrected it and currently, we display annotation _values_ as unformatted text. Annotation _keys_, on the other hand, are still displayed as hyperlinks.

Hope this helps. Regards.
