### ISSUE TITLE
Submitting new ontology

### ISSUE THREAD

**Issue by Dalalghamdi** [EBISPOT/OLS#571]
I am working on an application ontology, **Next Generation Bio-banking Ontology (NGBO)** https://github.com/Dalalghamdi/NGBO. NGBO integrates omics contextual data with bio-banking data. New terms introduced by NGBO are when possible submitted to the appropriate OBO foundry domain ontology when possible. The ontology mainly captures:
Analytical wet bench processes used to generate data.
The bioinformatics process analyzes, interprets, and reports results and data management processes. 
I used Basic Formal Ontology (BFO) as a top-level ontology and followed the Open Biological and Biomedical Ontologies (OBO) Foundry principles. Would you kindly let me know what is the requirement for submitting the ontology to OLS?

Thanks,
Dalia

**Comment by serjoshua** [comment]
Hello Dalia,

You can download and fill out this [spreadsheet](https://github.com/EBISPOT/OLS/blob/main/documentation/uptake/New%20OLS%20ontology%20request.xlsx). The important fields are ontology_purl and preferredPrefix. As for NGBO, there are no ontologies with that shorthand yet. So, it is good.

Please do share to us the updated spreadsheet once you are done. Thanks.

**Comment by Dalalghamdi** [comment]
Hi @serjoshua,
Please find the sheet here, 
[New OLS ontology request.xlsx](https://github.com/EBISPOT/OLS/files/8329480/New.OLS.ontology.request.xlsx)
am  just not sure if I filled in Base_uri - URI - Ontology purl correctly
looking forward to hearing back from you. 
Thanks,
Dalia

**Comment by serjoshua** [comment]
Hello Dalia,

First, we think that the ontology_purl you provided is not a valid one. The URL redirects to http://ontologies.berkeleybop.org/. It does not resolve to a valid OWL file.

Also, you need to make sure you added your ontology to the OBO Foundry if you are going to use the OBO base URI.

Regards.

**Comment by Dalalghamdi** [comment]
Hi @serjoshua this is a quite old request. The ontology was approved by the OBO foundry about few weeks ago and the metadata  is now completed. I was advice to follow up here if the NGBO wasn't up in OLS by the end of Jan. Is there anything I should do here? Thank you so much

**Comment by henrietteharmse** [comment]
Hi Dalia,

Currently OLS 3 is no longer being updated. We are in the process of rolling OLS 4 out. This has been communicated on ols-announce@ebi.ac.uk (for which you can subscribe by sending an email to [ols-announce-join@ebi.ac.uk](https://github.com/EBISPOT/OLS/issues/571)), as well as on Twitter (@EBIOLS) of which complete details can seen [here](https://github.com/EBISPOT/ols4/wiki/OLS-4-Executive-overview).

For your ontology, see [https://www.ebi.ac.uk/ols4/ontologies/ngbo/](https://www.ebi.ac.uk/ols4/ontologies/ngbo/). 

If you notice any issues, please open an issue against OLS 4 [here](https://github.com/EBISPOT/ols4/issues).

Keep well,

**Comment by Dalalghamdi** [comment]
Great!!! Thank you so much @henrietteharmse for all the information OLS 4 looks great! Sure, I will open one if there was any issue

**Comment by Dalalghamdi** [comment]
Hi, @henrietteharmse, I can't view NGBO on OLS anymore, https://www.ebi.ac.uk/ols4/ontologies/ngbo, not sure why but I haven't done any editing since it was accepted yet. Other ontologies are loading just fine.
