### ISSUE TITLE
Not children for a term

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#58]
@simonjupp  this term (http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms?obo_id=MS:1000458) has a children url however if I click in the children link, then I can't find chield nodes: http://www.ebi.ac.uk/ols/beta/api/ontologies/ms/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMS_1000458/children

Interesting in the web page I saw the children: 

http://www.ebi.ac.uk/ols/beta/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000458

Regards

**Comment by simonjupp** [comment]
It doesn't have children, it has parts, a different relationship. Although we noticed that the response says has_children : true. 

part_of is a special kind of hierarchical relationship. We will add a new link in the response to get "hierarchical_children", which will include parts. I'll get this to dev asap so you can test.

**Comment by ypriverol** [comment]
@simonjupp then in the future if I want all the children without taking into account the type of the relation then i should use hierarchical_children.

**Comment by simonjupp** [comment]
yes, children link will be be true children (just is-a)

hierarchical_children will be all children (including is-a and part of and others)

**Comment by simonjupp** [comment]
I'll also add hierarchical_parent for completeness

**Comment by ypriverol** [comment]
@simonjupp I just tested the dev environment and it works perfectly. I will close this issue.
