### ISSUE TITLE
Please update UBERON version in OLS

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/OLS#584]
cc @matentzn and @shawntanzk (see below)

Dear OLS team,
The current version of UBERON in OLS is 2021-11-28, but there have been a couple of releases since (2022-02-21 and 2022-04-05).
I'm aware of potential memory issues with frequent releases, but Uberon is quite a "key" ontology to many OLS users, and it'd be great if it could be updated please. Unless you'd like to liaise with @matentzn and/or @shawntanzk on a near-future version to use for the update, as I know they're planning to "have one release per week for the next 4 weeks at least to straighten out the new release pipeline"?

Thank you all,
Paola

**Comment by shawntanzk** [comment]
> as I know they're planning to "have one release per week for the next 4 weeks at least to straighten out the new release pipeline"?

Yeah this is a hopeful thing, but due to certain blockers, weekly release won't be a thing for a bit until we fix stuff.
