### ISSUE TITLE
Thing object can't be retrieve

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#59]
@simonjupp If I retrieve all the terms for a given ontology one of the terms is: Thing with obo_id null. Of course if I try to retrieve the actual term it throws an exception but in general all the objects that you retrieve should be accessible.

**Comment by simonjupp** [comment]
It is accessible, just not by an OBO id. It doesn't make sense for OWL thing to have an OBO id. You can still access via short_form or IRI.

**Comment by simonjupp** [comment]
If you are looping through terms you should really be fowling the "self" link to access individual term pages. That's the proper REST way

**Comment by ypriverol** [comment]
@simonjupp for GUI porpoise the "new id" can be the short_form

**Comment by simonjupp** [comment]
Safest bet is if you want to use OBO id for GUI, then fall back to short_form is OBO is null. short_form will never be null.

**Comment by ypriverol** [comment]
OK. I need to see because some of our tools and users like the obo id. do you think OBO ID will deprecated in the future?

**Comment by simonjupp** [comment]
No, just not all ontologies in OLS will have an OBO id, just the OBO ones :)

**Comment by ypriverol** [comment]
OK. I have a clear idea now. thanks @simonjupp
