### ISSUE TITLE
Add CCF Ontology to OLS

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/OLS#590]
Hi OLS Team,

We want to add CCF ontology. We would like to ensure the use of many preferred roots. Here is the [spreadsheet filled](https://github.com/EBISPOT/OLS/files/8573118/New.OLS.ontology.request.xlsx). Please, let us know if anything is not correct.

cc @dosumis @johardi

**Comment by serjoshua** [comment]
Hi @anitacaron,

I just want to share that CCF ontology is now available in OLS: https://www.ebi.ac.uk/ols/ontologies/ccf.

Let us know if you have any questions.

**Comment by serjoshua** [comment]
I am re-opening because of an issue regarding preferred roots. I will keep you posted @anitacaron.
