### ISSUE TITLE
Clicking on obsolete terms takes user to error page

### ISSUE THREAD

**Issue by ghost** [EBISPOT/OLS#593]
To replicate issue:

Search for an obsolete term in OLS, e.g., UBERON_0002003 'obsolete peripheral nerve'. Alternatively, simply navigate to the PURL: http://purl.obolibrary.org/obo/UBERON_0002003

User then sees an error screen:
![Screenshot 2022-05-16 at 17 45 41](https://user-images.githubusercontent.com/95643797/168643841-c6d9f32e-88c0-4821-a74c-fa81bee3079e.png)

**Comment by jamesamcl** [comment]
Thanks, I've lined up a fix for this and will get it pushed out today.

**Comment by jamesamcl** [comment]
This should be fixed now!
