### ISSUE TITLE
To different version of the same object in PSI-MS

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#60]
@simonjupp this term in the old ontology looks like:
   http://www.ebi.ac.uk/ontology-lookup/?termId=MS:1001723
in the new ols the term looks like 
   http://www.ebi.ac.uk/ols/beta/api/ontologies/MS/terms?obo_id=MS:1001723
is not even annotated as **OBSOLETE** even when in the old version has this in the definition of the term.

**Comment by simonjupp** [comment]
Issue reported with OBO foundry OBOFoundry/OBOFoundry.github.io#229

**Comment by ypriverol** [comment]
Thanks @simonjupp
