### ISSUE TITLE
404 error for previously known good query

### ISSUE THREAD

**Issue by jlchang** [EBISPOT/OLS#602]
I'm getting a 404 for a query that previously worked - is OLS having issues?

This is what I'm seeing when I try the following command:

> curl -i -H 'Accept: application/json' -L 'https://www.ebi.ac.uk/ols/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITaxon_9606' 

HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Strict-Transport-Security: max-age=0
Date: Thu, 26 May 2022 12:26:37 GMT
Content-Language: en
Content-Length: 1151

<html><head><title>Apache Tomcat/7.0.55 - Error report</title><style></style> </head><body><h1>HTTP Status 404 - /ols/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITaxon_9606</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>/ols/api/ontologies/ncbitaxon/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCBITaxon_9606</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.55</h3></body></html>

**Comment by jamesamcl** [comment]
Thanks, this should be resolved now.

**Comment by jlchang** [comment]
Thank you!
