### ISSUE TITLE
Delay in web display of OLS loading/searching

### ISSUE THREAD

**Issue by kanems** [EBISPOT/OLS#603]
I have noticed on and off for the past few days that the Search function for my favorite ontology on OLS (Mondo) is really slow. It runs the spinning search screen shown below for sometimes a few seconds and then I refresh or search again and it works instantly. Today it is just churning away and not returning any result:
![image](https://user-images.githubusercontent.com/71083858/170507811-51934031-2d36-4603-ae88-a9be5b5edd76.png)
I was able to pull up a link to another term within the Mondo view and edit the URL to get to my term of interest, but then expanding the view of the tree is also really slow, for example the term with the spinning icon took close to a minute to load and there are only 8 items under this branch of the hierarchy, this seems unusually slow. Terms with fewer children are running faster to load, but still longer than usual.
![image](https://user-images.githubusercontent.com/71083858/170508444-5de85cbe-396a-43e0-b7ec-5bda0c7cde9b.png)

**Comment by jamesamcl** [comment]
There was an issue with our deployment which is hopefully resolved now.

**Comment by kanems** [comment]
It seems to be responding much more quickly now. Thanks!
