### ISSUE TITLE
hierarchical display of part-ofs disappeared from CL

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#604]
https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000117&lang=en&viewMode=PreferredRoots&siblings=false

we used to have part-ofs in the tree

**Comment by cmungall** [comment]
part-ofs show up for uberon fine:

https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002389

**Comment by henrietteharmse** [comment]
Hi Chris,
This is because you have `Preferred root terms` selected. If you select `All terms` you will see the following:
![image](https://user-images.githubusercontent.com/32327979/174293643-913c50a4-33db-4b90-9325-63a72bdd6354.png)

**Comment by matentzn** [comment]
Why does preferred roots keep part of from being rendered in the tree?

**Comment by henrietteharmse** [comment]
In this case `central nervous system` is not accessible from the preferred roots, hence it is not rendered.

**Comment by matentzn** [comment]
Ah ok.. yeah that is probably another reason why Uberon on CL should be integrated together! Thanks for the explanation.
