### ISSUE TITLE
HANCESTRO reload

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/OLS#605]
Could I please request a reload of HANCESTRO in OLS? I did a new release a couple of weeks ago to fix some property and assertion snaffoos and it's now been picked up everywhere (Ontobee, OBOFoundry, AberOWL) except OLS.

Any way I can ensure that new releases are picked up automatically in the future?

**Comment by serjoshua** [comment]
We've had some challenges due to data center migration but it should update automatically. It is updated now. Please verify on your end. Thanks.
