### ISSUE TITLE
Modification for ontology description

### ISSUE THREAD

**Issue by baiddd** [EBISPOT/OLS#607]
Hi,
I am still new to the ontology field, is it possible to add a short [description](https://github.com/EBISPOT/OLS-Config/blob/cdf51bf587057832d6e753dfc0d0b9f7b6878d99/ols-ontologies.yaml#L970) for [SHARELOC ontology](https://www.ebi.ac.uk/ols/ontologies/shareloc) as following? 
```
ShareLoc defines terms to annotate data sets from single molecule localization microscopy, including but not limited to: imaging technique, biological structures or molecules of interest, cell types, experimental condition, labeling method, fixation protocol, etc. 
```
Best regards,
Jiachuan

**Comment by henrietteharmse** [comment]
This needs to be updated in your ontology .owl file. In [Shareloc](https://github.com/imodpasteur/ShareLoc.XYZ/blob/ontology/shareloc.owl#L9) you need to replace `<Ontology/>` with for example

```
<owl:Ontology rdf:about="https://raw.githubusercontent.com/imodpasteur/ShareLoc.XYZ/ontology/shareloc.owl">
<dc:description rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
ShareLoc defines terms to annotate data sets from single molecule localization microscopy, including but not limited to: imaging technique, biological structures or molecules of interest, cell types, experimental condition, labeling method, fixation protocol, etc.
</dc:description>
<dc:title rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Shareloc</dc:title>
</owl:Ontology>
```

**Comment by baiddd** [comment]
Thank you so much, [new *.owl file](https://github.com/imodpasteur/ShareLoc.XYZ/blob/c6a45ac800fcc2bf6523c2a058692c31e8a1e555/shareloc.owl#L10) is done
