### ISSUE TITLE
PLease add title to ncbitaxon

### ISSUE THREAD

**Issue by selvaebi** [EBISPOT/OLS#608]
the NCBITAXON has config->title as null, can you please add a title to it.

**Comment by matentzn** [comment]
Can you lobby ncbitaxon to fix their metadata instead? Helps more people than if OLS hard codes the title ;)

http://dashboard.obofoundry.org/dashboard/ncbitaxon/robot_report.html

https://github.com/obophenotype/ncbitaxon/issues
