### ISSUE TITLE
Bug when load/reload specific term 

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/OLS#611]
Two branches were deleted in the new EFO release but still sometimes show.

To reproduce:
- Go to https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002770&lang=en&viewMode=All&siblings=false
- Refresh the page to see it changing from the previous release to the new one and vice-versa.

New release:
<img width="856" alt="Screen Shot 2022-06-22 at 11 25 35 AM" src="https://user-images.githubusercontent.com/2208124/175026242-1ed0ba52-94b2-4e60-bf01-df5cacfcd08c.png">

Previous release:
![Screenshot 2022-06-22 at 13 15 32](https://user-images.githubusercontent.com/2208124/175026647-a16a149c-ae1c-411b-a77a-80340662b4d6.png)

**Comment by serjoshua** [comment]
Hi Anita,

This has been resolved. One of our instances apparently was not updated properly. The load balancer intermittently points to that instance causing the discrepancy. Please verify on your end. Thanks.
