### ISSUE TITLE
Missing type field on obo_synonym

### ISSUE THREAD

**Issue by EliotRagueneau** [EBISPOT/OLS#614]
Hi, 
I'm a developer in IntAct team, and in our release pipeline, we use the obo_synonym type of this [endpoint based on MI ontology](https://www.ebi.ac.uk/ols/api/ontologies/mi/terms?obo_id=MI:0000).
However, the type received is `null`.

The expected behaviour is the following:
[Source ontology file: Term definition](https://github.com/HUPO-PSI/psi-mi-CV/blob/56728a3d274798f1c870df1ea76297223c40defe/psi-mi.obo#L40-L46)
```obo
[Term]
id: MI:0000
name: molecular interaction
def: "Controlled vocabularies originally created for protein protein interactions, extended to other molecules interactions." [PMID:14755292]
subset: Drugable
subset: PSI-MI_slim
synonym: "mi" EXACT PSI-MI-short []
```

==> Term has a synonym `mi` of the type named `PSI-MI-short` 

[Source ontology file: Synonym types definitions](https://github.com/HUPO-PSI/psi-mi-CV/blob/56728a3d274798f1c870df1ea76297223c40defe/psi-mi.obo#L8-L22)
```obo
synonymtypedef: PSI-MI-short "Unique short label curated by PSI-MI" EXACT
```
==> type of obo_synonym of term MI:0000 should be `"Unique short label curated by PSI-MI"` as it is the definition of `PSI-MI-short`

The last time we ran our release pipeline, in January 2022, we didn't face this issue so this field was probably populated correctly then. 
This problem seems to also be present in the MOD ontology, since in [this endpoint](https://www.ebi.ac.uk/ols/api/ontologies/MOD/terms?obo_id=MOD:00000), the obo_synonym type should be `"Short label curated by PSI-MOD"`

**Comment by serjoshua** [comment]
Hi Eliot,

We already deployed our changes to production. Please let us know if any issue still exists. Kind regards.
