### ISSUE TITLE
MONDO OMIMPS split terms July release- updated in OLS yet?

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/OLS#615]
Hi
I would expect to see these changes mentioned https://github.com/monarch-initiative/mondo/issues/4864 in the current OLS?
But amendments do not seem to be reflected as I cannot see  the changes in OLS: 

example from https://github.com/monarch-initiative/mondo/issues/4864
: http://purl.obolibrary.org/obo/MONDO_0011108
id: MONDO:0011108
name: Stüve-Wiedemann syndrome
relationship: seeAlso https://github.com/monarch-initiative/mondo/issues/4521
relationship: seeAlso https://github.com/monarch-initiative/mondo/issues/4864
is_obsolete: true
replaced_by: MONDO:0800043

Thank you

**Comment by serjoshua** [comment]
Hi Louise,

Our last data release was exactly a week ago. Another release is in progress and hopefully will pick up your latest changes.

**Comment by serjoshua** [comment]
Hello,

OLS data release is done. MONDO is now updated to 2022-07-01 version. Let us know if the issue persists. Thanks.
