### ISSUE TITLE
PCL search not showing up

### ISSUE THREAD

**Issue by shawntanzk** [EBISPOT/OLS#618]
I can find cell types in OLS, but I cant seem to search for them anymore
(eg [https://www.ebi.ac.uk/ols/ontologies/pcl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org[…]o%2FPCL_0011070&lang=en&viewMode=PreferredRoots&siblings=false](https://www.ebi.ac.uk/ols/ontologies/pcl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0011070&lang=en&viewMode=PreferredRoots&siblings=false)) works but when I search for L5 ET_1 nothing comes up (https://www.ebi.ac.uk/ols/search?q=L5+ET_1+primary+motor+cortex+glutamatergic+neuron+%28Mmus%29&ontology=pcl)

**Comment by serjoshua** [comment]
Hi Shawn,

A recent data release to production seems to fix the issue. Please verify on your end. Thanks.

**Comment by shawntanzk** [comment]
just checked, looks good, thanks so much! :)
