### ISSUE TITLE
New term missing in OLS  - MONDO:0100506

### ISSUE THREAD

**Issue by marwa-elnagheeb** [EBISPOT/OLS#624]
We are unable to locate a new term in OLS: Cockayne spectrum with or without cerebrooculofacioskeletal (COFS) syndrome (MONDO:0100506). It was scheduled to be released in August. Release file: 
https://github.com/monarch-initiative/mondo/releases/tag/v2022-08-01

Could you please help us to locate this? 

This was a request from the ClinGen Syndromic Disorders GCEP/@RyanFWebb that was fulfilled last month by @nicolevasilevsky

**Comment by serjoshua** [comment]
Hi @marwa-elnagheeb I believe the term, MONDO:0100506, is already available in OLS. We did a data release last Monday and MONDO was updated together with it. Let us know if that is not the case on your end.

**Comment by marwa-elnagheeb** [comment]
> 

Thanks @serjoshua It did not appear in OLS as of Aug. 12th. I can see it now.
