### ISSUE TITLE
New version of INO available

### ISSUE THREAD

**Issue by streerm** [EBISPOT/OLS#625]
Could you update the Interaction Network Ontology? There is a newer version available on BioPortal ([1.1.13](https://bioportal.bioontology.org/ontologies/INO) v. [1.0.112](https://www.ebi.ac.uk/ols/ontologies/ino)).

**Comment by serjoshua** [comment]
Hello Mark,

We are on it. We'll let you know once a data release update on production for INO is done. Thanks.

**Comment by serjoshua** [comment]
Hi Mark,

By the way, INO has been updated in OLS. Regards.
