### ISSUE TITLE
FooOn is not Opening Up from Searches on OLS

### ISSUE THREAD

**Issue by RobertDanhi** [EBISPOT/OLS#627]
https://user-images.githubusercontent.com/110859838/186516852-0d14e27c-f969-4299-9ab4-9ad7c172c95f.mov

**Comment by serjoshua** [comment]
Hello Robert,

We encountered an issue doing a data release earlier this week. Some ontologies were affected. We are on it. Regards.

**Comment by henrietteharmse** [comment]
This should now be resolved
