### ISSUE TITLE
not able to view NCIT hierarchy today

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#628]
When I click on a NCIT term to view the hierarchy, I get an error page

<img width="832" alt="image" src="https://user-images.githubusercontent.com/6722114/186532237-6db6ecd0-4a1f-455c-819c-d84945d97bcd.png">

the term i searched for was NCIT:C85874

I'm on a Mac using Chrome

**Comment by henrietteharmse** [comment]
This should now resolved.
