### ISSUE TITLE
Cannot retrieve data with the OLS api 

### ISSUE THREAD

**Issue by imo046** [EBISPOT/OLS#629]
Hi,

It seems that for all the ontologies, the attempt to get the data from the `www.ebi.ac.uk/ols/api/ontologies/` results in the error message as shown in the attached screenshot.
![ols](https://user-images.githubusercontent.com/11870331/186612465-72372950-5a2f-4fb7-b5cc-9812c60de2bc.png)

**Comment by henrietteharmse** [comment]
This should now be resolved.
