### ISSUE TITLE
orphanet ontology in OLS doesn't match that on the orpha.data website because of change in edge annotation

### ISSUE THREAD

**Issue by fauman** [EBISPOT/OLS#631]
The orphanet ontology is corrupted in OLS.

As an example "Autosomal dominant secondary erythrocytosis" is listed as being a direct child node of "Disease" in OLS.
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_247511

However in orphanet, "Autosomal dominant secondary erythrocytosis" is a child node of "Congenital secondary polycythemia", and so on up the tree

https://www.orpha.net/consor/cgi-bin/Disease_Classif.php?lng=EN&data_id=156&PatId=19522&search=Disease_Classif_Simple&new=1

The reason for this discrepancy I think is that ORDO is using the "part_of" edge type, which is entity http://www.orpha.net/ORDO/Orphanet_C021
(https://www.ebi.ac.uk/ols/ontologies/ordo/properties?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_C021)

This is used in addition to the explicit edge type "rdfs:subClassOf"

To repair the orphanet ontology in OLS, the ontology needs to include both edges derived from "rdfs:subClassOf" as well as those derived from "<ORDO:Orphanet_C021>"

**Comment by henrietteharmse** [comment]
How OLS is configured for an ontology is done in collaboration with the ontology owners. I am not aware of any request for changing how OLS is configured for Orphanet. For this reason I suggest you take this up with Orphanet as the request needs to come from Orphanet.

May be to clarify further. Orphanet is not corrupted on OLS. In fact its rendering matches that of Protege exactly.
