### ISSUE TITLE
Can OLS resolve URLs directly?

### ISSUE THREAD

**Issue by KonradHoeffner** [EBISPOT/OLS#632]
Is it possible to align the namespace of an ontology with the URL scheme of OLS so that the URLs don't get handled by an additional URL browser component but by OLS itself?

For example, if OLS is installed under `https://example.com/` and contains an ontology with the slash namespace `https://example.com/ontologies/elefants`, is it possible that when someone enters `https://example.com/ontologies/elefants/African_Elefant` in their browser that this gets handled by OLS?

The current scheme of OLS seems to be `https://example.com/ontologies/elefants/terms?iri=https%3A%2F%2Fexample.com%2elefants%2African_Elefant`.

**Comment by henrietteharmse** [comment]
Unfortunately I do not see an easy way achieve this in OLS.

**Comment by KonradHoeffner** [comment]
Thanks for the quick reply! Then I will investigate whether we can do this with a redirect from our webserver or otherwise use an external RDF browser.
