### ISSUE TITLE
ols api parents and ancestors not working terms other than GO

### ISSUE THREAD

**Issue by selvaebi** [EBISPOT/OLS#634]
eg : http://www.ebi.ac.uk/ols/api/ontologies/go/ancestors?id=GO:0043226 is working

but http://www.ebi.ac.uk/ols/api/ontologies/doid/ancestors?id=doid:0081062 is not working am I missing something

**Comment by serjoshua** [comment]
Hi Selva,

We are looking into this but initially, I think this is caused by the recent data issue we encountered in OLS. We might need to force an update for DOID to resolve this specific example you provided. If you have examples from other ontologies, we would be more than glad to know about them.

Josh

**Comment by selvaebi** [comment]
right now this is one case, I put up if anything else comes up. And also the main use case for us is to get the root element of the provided id, to find whether it is a disease/cell type/tissue or organism. Do you have any API that you can point me to ??

**Comment by serjoshua** [comment]
Good day Selva,

DOID has just been updated in OLS. I checked your problematic API and it seems like the issue still exists. Upon checking though, the term is already obsolete. Given that, let us know if this is something that has been considered on your side. Regards.

**Comment by cmungall** [comment]
note you have to use the correct identifier. OBO Identifiers are case sensitive

https://www.ebi.ac.uk/ols/api/ontologies/doid/ancestors?id=DOID:0081062 gives the expected results given this is obsolete

**Comment by serjoshua** [comment]
Thanks Chris. I wasn't aware of this and never realized to check casing. With that said, I will consider this resolved.
