### ISSUE TITLE
404 error for GO:0000512

### ISSUE THREAD

**Issue by afg1** [EBISPOT/OLS#635]
I'm getting a 404 error when accessing the page for GO:0000512, at the url

https://www.ebi.ac.uk/ols/api/ontologies/GO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0000512

The term does appear in the search here (first hit): https://www.ebi.ac.uk/ols/search?q=GO%3A0000512&groupField=iri&start=0&ontology=go

but the link from there is also broken.

**Comment by afg1** [comment]
Two more examples: 
https://www.ebi.ac.uk/ols/api/ontologies/GO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0140869

https://www.ebi.ac.uk/ols/api/ontologies/GO/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0160028

for term GO:0140869 and GO:0160028

**Comment by henrietteharmse** [comment]
Thanks for reporting this! This happens because the OLS Neo4J and Solr indexes are out of sync for GO. We have force reindexing of GO which should resolve this. We will let you know when it is done.

**Comment by afg1** [comment]
Excellent, thank you!

**Comment by henrietteharmse** [comment]
This has been resolved
