### ISSUE TITLE
Add VBO to OLS

### ISSUE THREAD

**Issue by sabrinatoro** [EBISPOT/OLS#636]
The Vertebrate Breed Ontology (VBO) has recently been admitted to OBO Foundry (https://obofoundry.org/ontology/vbo.html). 
We kindly ask that you add it to OLS.
Please let us know if you have any questions and/or need any additional information. 
Thank you very much! 

https://github.com/monarch-initiative/vertebrate-breed-ontology

**Comment by cmungall** [comment]
this should be automatic if it's in OBO?

**Comment by cmungall** [comment]
Still not there - @henrietteharmse it would be really awesome if we could have it up in time for ICBO this weekend!!!

**Comment by jamesamcl** [comment]
Hi, sorry I missed this, I will try my best to get it added now. Our data releases are very prone to breaking at the moment which is why they have been infrequent, so if it breaks OLS I won't be able to push it through.

**Comment by jamesamcl** [comment]
Hi, VBO is in OLS now: https://www.ebi.ac.uk/ols/ontologies/vbo
