### ISSUE TITLE
Frequency of update for the MS ontology

### ISSUE THREAD

**Issue by javizca** [EBISPOT/OLS#638]
https://www.ebi.ac.uk/ols/ontologies/ms

The last time this was updated it was on August 26th.

How often does it updated by default? It would be nice to get it updated asap since there was a big update in the meantime.

Thanks in advance

**Comment by henrietteharmse** [comment]
Currently data release are slower due to us trying getting OLS4 out asap. We will force an update for MS shortly. Can you please confirm whether the update addresses the issues mentioned for MS in [#623](https://github.com/EBISPOT/OLS/issues/623) ?

Thanks!

**Comment by serjoshua** [comment]
Good day,

We just pushed a data update of MS in OLS. Please verify on your end.
