### ISSUE TITLE
Please add 'comment' field

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/OLS#64]
A lot of ontologies keep the term description short but add important info for users/curators in a 'comment' field (GO also use 'glossary'...). We have recently added a bunch of new ECO terms and none of the comments show but are vital for the user to identify what use these terms are intended for.

Thanks,
Birgit

**Comment by simonjupp** [comment]
Comments can currently be viewed in the term metadata tab. We have decided to remove the metadata tab so you'll see all this by default soon.

**Comment by bmeldal** [comment]
Ah, thanks. Another one of those not-so-intuitive placement. I admit I didn't click on the metadata tab as previously I hadn't seen any value added fields, just xefs etc...

**Comment by simonjupp** [comment]
This should be more visible now.

**Comment by bmeldal** [comment]
Thanks, that working now (has I think has been there for a little while already).
