### ISSUE TITLE
latest version of Mondo?

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/OLS#642]
Hi,
I noticed that OLS does not have the latest version of Mondo, will it be updated soon?

Related to https://github.com/monarch-initiative/mondo/issues/5461

Thanks!

**Comment by henrietteharmse** [comment]
@nicolevasilevsky We have an OLS data release planned for 18 Oct. We will ensure that Mondo is part of the update.

**Comment by nicolevasilevsky** [comment]
thanks @henrietteharmse!

**Comment by serjoshua** [comment]
Good day Nicole,

MONDO has just been updated in OLS. Let us know if you encounter any issues. Regards.
