### ISSUE TITLE
Index of pride ontology in OLS

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#644]
Hi @henrietteharmse : 

Can you make sure the new version of PRIDE Ontology vocabulary https://github.com/PRIDE-Utilities/pride-ontology/blob/master/pride_cv.obo get indexed. 

Regards 
Yasset

**Comment by serjoshua** [comment]
Good day Yasset,

Apologies for the delayed response. I checked our current configuration and it is updated. We just need to include PRIDE on our next data release which will be mid-November at the latest. We will keep you posted.

**Comment by serjoshua** [comment]
Hello Yasset,

PRIDE has been updated in OLS. Feel free to message us if there are any issues. Thanks.
