### ISSUE TITLE
New SWO location for OWL file

### ISSUE THREAD

**Issue by allysonlister** [EBISPOT/OLS#645]
Apologies, I thought this might get picked up with the new swo.md file on the[ OBO Foundry site](https://obofoundry.org/ontology/swo), but it looks like it may not have. You can always find the latest version here: http://purl.obolibrary.org/obo/swo.owl

Please could you take SWO from this location in future?

Thanks very much!

**Comment by serjoshua** [comment]
Good day Allyson,

I checked OBO configuration and `ontology_purl` points to [http://purl.obolibrary.org/obo/swo.owl](http://purl.obolibrary.org/obo/swo.owl). We just need now to force update SWO on the next data release of OLS which won't kick off until mid-November at the latest. We will keep you posted. I hope this helps.

**Comment by serjoshua** [comment]
Hello Allyson,

SWO has just been updated in OLS. Feel free to message us if you encounter any issues. Thanks.
