### ISSUE TITLE
ontology_status in ols-config.yml is ignored

### ISSUE THREAD

**Issue by KonradHoeffner** [EBISPOT/OLS#648]
I want to deactivate an ontology in my OLS configuration `ols-config.yml` file but whether I use `activity_status: active` or `activity_status: inactive`, it always gets loaded.

```
"@context":
                                                        
ontologies:
- activity_status: inactive
  id: my-ontology-that-i-want-to-deactivate
[...]
```

**Comment by serjoshua** [comment]
Hi Konrad,

The `activity_status` is more of a configuration used in OBO rather than in OLS. Sadly, we have to comment it out manually if we want to exclude something.

**Comment by KonradHoeffner** [comment]
Thanks for the clarification! Could you update the documentation so others don't trip over the same issue?
