### ISSUE TITLE
CCF page is empty

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/OLS#650]
As shown in the image below, we cannot see the preferred root terms rendering in the [landing page](https://www.ebi.ac.uk/ols/ontologies/ccf).

![Screenshot 2022-11-22 at 18 42 07](https://user-images.githubusercontent.com/2208124/203396338-ce948909-2312-40a1-bca1-5641fb22f000.png)

cc @johardi

**Comment by serjoshua** [comment]
Thank you for bringing this to our attention. We are looking into this. May I ask, if you are using the API, do you experience issues using it specifically for CCF? @johardi @anitacaron

**Comment by anitacaron** [comment]
No, we're not using the API. We share the CCF page in OLS with the users to have a look into the ontology.

**Comment by serjoshua** [comment]
Good day,

If you happen to know any information regarding the homepage or repository for CCF, it will be of help. We would like to verify some discrepancies that may have caused the issue, @johardi @anitacaron. Regards.

**Comment by anitacaron** [comment]
Here's the github repository https://github.com/hubmapconsortium/ccf-ontology

**Comment by serjoshua** [comment]
Good day,

CCF has been updated in OLS. It should be available now. Feel free to message us if there are any concerns. Thanks!

**Comment by anitacaron** [comment]
Thank you so much, @serjoshua!
