### ISSUE TITLE
OBA preferred root node and show part_of hierarchy

### ISSUE THREAD

**Issue by rays22** [EBISPOT/OLS#653]
Based on feedback from some confused users who tried to navigate the Ontology of Biological Attributes [(OBA)](https://www.ebi.ac.uk/ols/ontologies/oba) I am wondering if
    * OLS could display a preferred root node [OBA:0000001](http://purl.obolibrary.org/obo/OBA_0000001) for [OBA](https://www.ebi.ac.uk/ols/ontologies/oba), and if
    * OLS could show materialised part-of relationships in OBA with blue 'P' icons as [it does, for example, in the Uberon hierarchy.](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001703)

There are several newer releases than the currently displayed OBA v2022-08-03, and it would be great to see the [latest OBA release](https://github.com/obophenotype/bio-attribute-ontology/releases/tag/v2022-11-26) with the enhancements I am suggesting above.

**Comment by matentzn** [comment]
@rays22 the first (root node) will happen automatically at the next load. For the second, we need to edit the hierarchical properties in the OLS config. @serjoshua can you remind me where this is hosted?

**Comment by serjoshua** [comment]
Hello Nico and Ray!

Yes, we could handle configuration (overrides) besides what is in OBO Foundry. Those overrides could be found [here](https://raw.githubusercontent.com/EBISPOT/OLS-Config/prod/ols-ontologies.yaml). You could also see there examples of other configuration that some ontologies have, such as `hierarchical_property`, as mentioned. As for the data update, we will add OBA to our next data release mid-December. It would be better as well if we already have the configuration for the `hierarchical_property` before the release so it will be included in the update. Otherwise, we will keep you posted regarding the release. Regards.

Josh

**Comment by matentzn** [comment]
@rays22 will you deal with adding the part of as an hierarchical property?

**Comment by rays22** [comment]
OK, I have added the following snippet to `EBISPOT/OLS-Config/prod/ols-ontologies.yaml`

```yaml
## OBA override
  - id: oba
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
```
and created a PR https://github.com/EBISPOT/OLS-Config/pull/8 .
@serjoshua, please, let me know , if anything is missing or if it is not what you need.

**Comment by serjoshua** [comment]
Good morning Ray, that is just exactly what we need. Thank you. We will keep you posted regarding the release. Re-opening this ticket until OBA has been updated in OLS.

**Comment by rays22** [comment]
Thank you Josh.

**Comment by jonquet** [comment]
@serjoshua quick question: is there a list somewhere of all the properties that can be "overrided" ?
Could be interesting candidates for extending MOD (metadata for ontologies)... we do already have in MOD a few metadata properties to describe the properties used to define objects...

**Comment by serjoshua** [comment]
Hello Clement,

That is actually a good question. I'm not an expert in ontologies, OWL standards and the like, but we have a [documentation](https://github.com/EBISPOT/OLS/wiki/How-are-ontologies-added-to-OLS%3F) on how to add ontologies in OLS and in the spreadsheet/form that we provide there, we have five (5) property configurations that we accept:
- label_property
- definition_property
- synonym_property
- hierarchical_property
- hidden_property

I hope it helps. Regards.

**Comment by jonquet** [comment]
Thanks. 
Good we already have some matches: 

- label_property => https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L1096
- definition_property => https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L1137 
- synonym_property => https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L1115
- hierarchical_property => https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L1193
- hidden_property


We also have  in MOD2 
- mod:obsoleteProperty (https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v2.0_profile.ttl#L1174) used to inform which property the ontology used to declare its objects obsolete
- mod:obsoleteParent => to declare the root of the obsolete hierarchy (if any)
- mod:authorProperty => used to inform which property is used to declare the author of an object defined in the ontology
 
Can you clarify the meaning of hidden_property ? 
This is a bit similar to obseolete to me, but if this is a porperty that has only value in OLS UI to avoid displaying the property on the screen... then it does not belongs to MOD I believe (that the policy we took first time we review a bunch of ontology repositories (including OLS) when we did MOD1.4).

**Comment by serjoshua** [comment]
Thank you. That is a good observation. I actually just checked our code and it seems like we are not using it anymore or about to discontinue. Apologies if my earlier response confused you. So, it seems like we only have the other four properties properly supported as of the moment. Let me know if you have other questions. Regards.

**Comment by rays22** [comment]
The preferred root node [OBA:0000001](http://purl.obolibrary.org/obo/OBA_0000001) is displayed for [OBA](https://www.ebi.ac.uk/ols/ontologies/oba) on OLS.
Thank you @serjoshua !
