### ISSUE TITLE
Mondo update on OLS?

### ISSUE THREAD

**Issue by kanems** [EBISPOT/OLS#654]
I am trying to review the latest Mondo data and when I tried to go to the EBI OLS URL for a recently created Mondo ID (https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0800167) I get this error:
"Ontology Lookup Service
Something went wrong! Use the issue tracker or the support mail below to report any bugs or give feedback."

OLS https://www.ebi.ac.uk/ols/ontologies/mondo shows the last Mondo update was in October of 2022. Mondo has releases from both 1 November and 1 December 2022 that were apparently not loaded to OLS. https://github.com/monarch-initiative/mondo/releases

When will the latest Mondo release be available in OLS?

**Comment by kanems** [comment]
FYI @nicolevasilevsky @matentzn

**Comment by serjoshua** [comment]
Thank you for raising this issue. I will keep you posted regarding data update in OLS. We are planning on doing one today.

**Comment by serjoshua** [comment]
MONDO has just been updated in OLS. Regards.

**Comment by nicolevasilevsky** [comment]
Thanks @serjoshua! How often is Mondo updated in OLS? On our FAQ page, we say it is updated a few days after each release, is that no longer the case?
Thank you!
