### ISSUE TITLE
Issues with MAxO on OLS

### ISSUE THREAD

**Issue by LCCarmody** [EBISPOT/OLS#655]
Looking up this term (single-photon emission computed tomography MAXO_0009070) I got an error/blank page suggesting I make an issue. BUT, I was doing this because I noticed several terms were missing exact synonyms. I was search SPECT (which should be a synonym of the above term), but it didn't work in search.

Also, when are the OLS updates going to be performed? It is pulling from MAxO's release in June, but there have been several since then.

Thanks.

**Comment by LCCarmody** [comment]
also, analgesic therapy MAXO_0000159 does not appear to have all the exact synonyms.

**Comment by serjoshua** [comment]
Thank you for raising this issue. We are planning on doing an update today and will include MAXO.

**Comment by LCCarmody** [comment]
great, thanks!

**Comment by serjoshua** [comment]
Good day, MAXO has just been update in OLS. Both MAXO_0000159 and MAXO_0009070 are now searchable. Please do verify. Thanks.
