### ISSUE TITLE
Update CCF ontology information

### ISSUE THREAD

**Issue by anitacaron** [EBISPOT/OLS#656]
Dear OLS team,

There's a new CCF release, and we would like to update some information. Here's the [spreadsheet](https://github.com/EBISPOT/OLS/files/10237523/CCF_update_metadata.xlsx). We also expect a new CCF release in the next OLS data release, please.

**Comment by serjoshua** [comment]
You can check the configuration changes for CCF [here](https://github.com/EBISPOT/OLS-Config/commit/2d0300a36e905c4768c2070a72677a266f47e33b). I will start the data update in a few.

**Comment by anitacaron** [comment]
Thank you, Josh!

**Comment by serjoshua** [comment]
CCF has just been updated in OLS. Please verify on your end. Thanks.
