### ISSUE TITLE
Display version based on version IRI

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/OLS#66]
Versioning is dealt with confusingly by OLS.

Version is displayed as date - which appears to be the date of loading into OLS - *not* the date pulled from the version IRI.

e.g: This looks like the version is: 02-02-2016

![image](https://cloud.githubusercontent.com/assets/112839/13749738/98b3653c-e9fa-11e5-8799-12c2226b3624.png)

But the current public release of this ontology has the version IRI:

http://purl.obolibrary.org/obo/fbbt/2016-01-21/fbbt.owl

(This IRI follows the [OBO foundry standard versioning scheme](http://obofoundry.org/id-policy.html).)

Please could you:
* Store the version IRI in OLS neo4J or SOLR ( - or document where this is stored; needed for VFB)
* Display and hyperlink the version IRI for all ontologies that have one (would be great if you could pull the date from here - but understandable if you don't want to rely on a particular IRI scheme for this).

It would be great if this could be integrated with the new change tracking system - allowing users to retrieve the specific versions referred to in the tracking system.

**Comment by dosumis** [comment]
CC @cmungall

**Comment by simonjupp** [comment]
Duplicate of #7. The version IRI is now stored in the latest neo4j index, just not yet displayed in the UI. 

I have a new version that will get released in the next weekwhere the versionIri will be displayed. 

This is the new order for determining any version info 
1. Look for a owl:versionInfo
2. Parse version date out of versionIRI according to OBO versions schema 
3. Default to date loaded
