### ISSUE TITLE
Request new ontology

### ISSUE THREAD

**Issue by michellepaczosa** [EBISPOT/OLS#665]
I'd like to request a new ontology associated with the ADA2 gene to be used for a ClinGen curation. Specifically, I'd like to create a MONDO term for the disease "Deficiency of adenosine deaminase 2".

Thank you
Michelle

**Comment by matentzn** [comment]
Hey @michellepaczosa, can you make this issue here: https://github.com/monarch-initiative/mondo/issues

This is only the issue tracker for the OLS browser!

**Comment by henrietteharmse** [comment]
Closing this as Nico indeed indicated: this needs to be address on the Mondo issue tracker.
