### ISSUE TITLE
Visualization of individuals' object and data properties

### ISSUE THREAD

**Issue by iesnaola** [EBISPOT/OLS#666]
Hi,

When visualizing ontology individuals in the OLS, we cannot see their data and object property values. Only the annotation properties are displayed in the OLS. For example, from the triples below, only 'rdfs:comment' would be displayed in the OLS.

`:ind1 rdfs:comment "individual 1";`
`:ind1 myonto:myDataProperty "value1".`

I was wondering if there is any way to visualize individuals' data and object properties and, if not, if there are any plans to develop this functionality in the future.

Thanks in advance.

**Comment by henrietteharmse** [comment]
This was actually one of our testcases. See: [object property assertion test case](https://github.com/EBISPOT/ols4/blob/dev/testcases/owl2-primer/object-property-assertion.owl).

It shows the individual `John` is linked to `Mary` via the object property `hasWife`. 

![image](https://user-images.githubusercontent.com/32327979/235139798-b9f63e86-3f00-443c-a5c8-b7d9227fec28.png)

To the best of our knowledge this is working. If you can supply example from OLS where this is not working, please let us know.

**Comment by henrietteharmse** [comment]
Ah! I did not realize. This is OLS3. This working OLS4. Hence, I strongly encourage you to use OLS4. 
Closing this issue.
