### ISSUE TITLE
Update old wwwdev link

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#69]
Can you please add either a redirection from http://wwwdev.ebi.ac.uk/ols/beta/ontologies/efo/ to the new beta website, or if wider is still used for internal testing a link to the correct dev version? Some colleagues had the old link and thought OLS didn't work at all.

**Comment by simonjupp** [comment]
Where did you find the link?

**Comment by mcourtot** [comment]
It was sent by email to a UniProt curator.

**Comment by simonjupp** [comment]
Hard to know how and why they were using wwwdev links. we don't want to put a redirect in from wwwdev, but maybe some visual notification that you are on the dev site would be good.

**Comment by mcourtot** [comment]
I don't think it's a huge issue, but adding a visual indication/link towards the stable beta would be nice if possible. My colleague thought OLS was broken and not working and was quite frustrated with the tool :)
