### ISSUE TITLE
Show versionIRI of ontology

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#7]
On the ontology landing page it shows 'last updated', but this appears to be 'last loaded into OLS'. If the versionIRI is there, it should be accessible.

**Comment by mcourtot** [comment]
Was about to comment same. It shows all ontologies as "last updated" but that is actually the date of last load, not the date of last update of the ontology. Perhaps clarify the meaning by using "last loaded on" or "last refreshed on"?
