### ISSUE TITLE
Wrong Data sections 

### ISSUE THREAD

**Issue by muthuvenkat** [EBISPOT/OLS#72]
Hi, 

Looks like there is some wrong data under the sections. First image is the the data from chebi FTP (ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.obo) has only one SMILES ( [H]O[H] ) where as in second image (from OLS Beta ) it shows two and similarly with IUPAC NAME, InChI, OBO Synonyms and almost all the sections. Can you please take a look. 

Thanks, 
Venkat

![from chebi ftp](https://cloud.githubusercontent.com/assets/1352644/14559090/59c82b74-02fe-11e6-92ef-3d9b7ef912c1.png)
![from ols](https://cloud.githubusercontent.com/assets/1352644/14559088/56224bee-02fe-11e6-8b52-b1572ded7d07.png)

**Comment by tburdett** [comment]
There is something unusual going on with the interpretation of these annotations in the UI.  If, for example, I reload this page several times:
    http://www.ebi.ac.uk/ols/beta/ontologies/chebi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_15377

... I actually get a different view of the term info each time.

So, e.g. I get
*SMILES*
    [H]O[H] [ ChEBI: ]
then
*SMILES*
    [H]O[H] [ ChEBI: ]
    [OH2] [ IUPAC: ]
    BOUND OXYGEN [ PDBeChem: ]
...and so on

**Comment by LLTommy** [comment]
It is a bug in the UI, thank you for reporting. After clicking around a bit it seems to be especially relevant for Chebi, could not find other examples in other ontologies. We will fix this soon, in the meantime, if you are confused, please have a look at the JSON file (link in the right corner) - the data in there is correct.

**Comment by simonjupp** [comment]
I see what the problem is. Synonyms that are typed (e.g RELATED SMILES) get a heading SMILES in the UI. Some synonyms are not typed so you don't see a header. In the next version this will default to the scope (i.e. related/exact/narrrow).
