### ISSUE TITLE
Add support for gzipped OWL files

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/OLS#75]
VFB has some very large OWL files.   It would be very helpful if we could specify these for loading into OLS.

Latest OWL-API & Protege accept gzipped files - deflate by default:
https://github.com/owlcs/owlapi/issues/348#issuecomment-74800777  - so presumably shouldn't be hard(?).

**Comment by dosumis** [comment]
CC @robbie1977

**Comment by simonjupp** [comment]
Did you try it? I did put some support for loading zipped files from a URL, but never thoroughly tested it. I'll look into it anyway.

**Comment by Robbie1977** [comment]
Didn't work for me, complained about incorrect start of file, if my memory is correct.

**Comment by Robbie1977** [comment]
Still not working with the latest version in master branch as of today
