### ISSUE TITLE
add citation to about

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS#77]
http://www.ebi.ac.uk/ols/beta/docs/about

It would be nice to have a "how to cite OLS"

**Comment by tburdett** [comment]
Yes, +1 for this from me too.

**Comment by LLTommy** [comment]
Already mentioned in issue #61. The plan was/is to include a cite this button (e.g. on every term page)

**Comment by mcourtot** [comment]
Just to confirm as I think we are talking about slightly different things: #61 is about citing individual terms (e.g. via their PURLs). 

Here I would like to have a citation for the OLS itself for a paper I'm writing. 

Similar to 
@inproceedings{vrousgoubiomedical,
  title={Biomedical Ontology Evolution in the EMBL-EBI Ontology Lookup Service},
  author={Vrousgou, Olga and Burdett, Tony and Jupp, Simon and Parkinson, Helen},
   year={2016},
  booktitle={Proceedings of the Workshops of the EDBT/ICDT 2016 Joint Conference (EDBT/ICDT 2016)}
}
in bibtex or
Olga Vrousgou, Tony Burdett, Simon Jupp, and Helen Parkinson. Biomedical ontology evolution in the embl-ebi ontology lookup service. In Proceedings of the Workshops of the EDBT/ICDT 2016 Joint Conference (EDBT/ICDT 2016), 2016. 

in plain text.

**Comment by LLTommy** [comment]
I can see that both ways to cite make sense. What I rather wanted to say with my comment above is - 'citing' is on the to do list.

**Comment by mcourtot** [comment]
I still can't see the citation on the about page?

**Comment by simonjupp** [comment]
It's fixed in code, will be live on the website in next hour or so once everything has finished deploying
