### ISSUE TITLE
Make obo xrefs for classes and axioms hyperlinks

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/OLS#78]
E.g. http://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001727

All of these can be made into links:

GAID:815, nifext_14, C0039337, OpenCyc:Mx4rvVjan5wpEbGdrcN5Y29ycA, Taste_bud, ZFA:0001074, VHOG:0000130, 362099006, MA:0001591, C96518, EMAPA:35850, AAO:0010573, MESH:A08.800.550.700.120.800, XAO:0000445, TAO:0001074, birnlex_4101, UMLS:C0039337, CALOHA:TS-1015, BTO:0000989, FMA:54825

E.g. https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

Note that some of the above are URLs that are truncated into fragments

Also, for axiom annotations, these are rendered as:

```
A specialized receptor organ that is a collection of cells spanning the gustatory epithelium. Taste buds may be found on the tongue, soft palatte, epiglottis and upper pharynx. [ Taste_bud_histology ] 
```

It looks like this is an attempt to preserve an OBO-esque way of displaying this, but again URLs are truncated. The source obof looks like this:

```
def: "A specialized receptor organ that is a collection of cells spanning the gustatory epithelium." [http://periowiki.wikispot.org/Taste_bud_histology]
```

in OWL this is an axiom annotation

**Comment by simonjupp** [comment]
Looking into possibility of importing the information from the OBO dbxref file into identifiers.org, so OLS can delegate to that service for resolution. Need to clean up the prefix mess a bit.

**Comment by cmungall** [comment]
> Need to clean up the prefix mess a bit

That'll only be a few minutes work, yeh? :-)

cc @jmcmurry

**Comment by simonjupp** [comment]
All annotation values that are IRIs are no longer truncated and are also hyperlinked. Images are also now being displayed. 

e.g. http://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000329

We are now parsing https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml to create external links where we can match a prefix. Still some work to do on cleaning up prefixes. Ideally I want to move to identifiers.org for resolving, but first need to make sure all prefixes are covered by them.

**Comment by cmungall** [comment]
looks nice.

do you want a ticket started for the resolution part? would be interested in discussing this more. Using a standard like identifiers.org is good but it's built on different foundations (no/inconsistent assumption of prefixes) so there may occasionally be misalignments. E.g. if we were to reference OBI using a CURIE then we'd use OBI:nnnn, but in id.org it's registered as OBI_nnnn. This may be a non-problem as you consume OWL where the full URI is typically used, just obo-esque properties like hasDbXref that use the CURIEs.

**Comment by simonjupp** [comment]
Yes, we can start a new ticket for this. I'm currently in discussion with id.org to better support our use case. They are going to add an extension to support adding other "known prefixes". I'm currently doing the work to pull out everything patterns we find in OLS, cross validating against what you have and what they have. It's a lot of fun.

**Comment by cmungall** [comment]
cc @jmcmurry
