### ISSUE TITLE
Bug in the release API version

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#80]
@simonjupp 

 This url is not working in the API http://www.ebi.ac.uk/ols//api/ontologies/mod/terms/?page=0&size=1000

**Comment by LLTommy** [comment]
Short note: you have two // in there after ols

**Comment by ypriverol** [comment]
Even eplacing that is not working @simonjupp is trying to fix the server issue.

**Comment by ypriverol** [comment]
Done
