### ISSUE TITLE
NCBI Taxonomy

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/OLS#81]
@simonjupp @LLTommy I have trying to search by ncbi taxonomy into OLS if I type 9606 I expect Homo Sapiens. However the  as you can see (http://www.ebi.ac.uk/ols/search?q=9606&groupField=iri&start=0&ontology=ncbitaxon) the result is Coleofasciculus chthonoplastes CCY9606

**Comment by simonjupp** [comment]
You need to search with the prefix as discussed. Unfortunately the NCBI taxon doesn't include the raw id as an annotation on the term.
