### ISSUE TITLE
'database' attribute is null

### ISSUE THREAD

**Issue by tschaka1904** [EBISPOT/OLS#83]
Dear OLS-Team, 

I was wondering, if the 'database' attribute shouldn't be null. The old ols-client used to provide a  'database' attribute. 
<img width="356" alt="screen shot 2016-05-17 at 14 29 22" src="https://cloud.githubusercontent.com/assets/5269116/15323936/2e67aac0-1c3c-11e6-96b4-9a17de252b9d.png">

Thanks,
Max

**Comment by simonjupp** [comment]
Hi, 
I just checked in the source file (http://purl.obolibrary.org/obo/mi) that we load into OLS and there is no database info for this term 

        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:10967325</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:12634794</oboInOwl:hasDbXref>
        <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PMID:1946372</oboInOwl:hasDbXref>

You would need to contact the ontology developers to find out if/why it went away. 

Simon

**Comment by tschaka1904** [comment]
Mhm. I is not in the file. But I think it would be a nice feature if you could to the mapping. It is anyway quite confusing. Some ontologies are using PubMed:12345 and others pubid:12345. I know that is not and issue on your side, but maybe you could do a mapping and could provide the general DB name in the database field.

**Comment by simonjupp** [comment]
Yes, this is agin coming from source. We just show you what is in the file and try not to intervene too much. 

We're actually working on pulling out the xrefs into a dedicated mapping services. We'll do some cleanup of the prefixes as part of this. We're trying to align these with identifiers.org right now.
