### ISSUE TITLE
search-url on two different places

### ISSUE THREAD

**Issue by tschaka1904** [EBISPOT/OLS#85]
Dear OLS-Team, 

the general term json model has a `database_cross_reference`, which contains a attribute `search-url`. I was looking at [MI:0446](http://www.ebi.ac.uk/ols/api/ontologies/MI/terms?obo_id=MI:0446) and the `search-url` attribute is empty. Instead it can be found in the `obo_xref `object. 

Why is that? 

Thanks,
Max

**Comment by simonjupp** [comment]
By default we just show properties and their values asserted in the ontology. So in this case

database_cross_reference is a property and the value is "search-url". You can see that in the sources. 

We understand the some ontologies coming from OBO have a specific Xref pattern that OLS tries to detect, in cases where we spot this we add the obo_xref attribute. Note that most ontologies donct have this. 

If you find an obo_xref you can probably ignore the database_cross_reference. We may even move to do that by default in the future so you wouldn't see database_cross_reference if there's a properly formatted boo xrefs in the raw ontology file.

**Comment by tschaka1904** [comment]
I understand that. It's just the fact that the old old-client just gave me the meta-data and I had all the existing information. Now I have basically to search it's existent. But I understand that not all files are formatted the same way. It is just difficult from a developer point of view, who uses the ols-ws, to collect all that information. Because the information can be on different places. Please don't take my tickets as any kind of bad feedback. I'm just trying to understand how I have to deal with the new OLS.

So you say that `database_cross_reference` might be removed in the near future? I guess the` id-validation-regexp` would, in that case, also end up in the `obo_xref`. Am I assuming that right?

**Comment by tschaka1904** [comment]
I was just checking out the MI obo file and looked at `MI:0446`
It looks like this:
<img width="923" alt="screen shot 2016-05-20 at 10 49 44" src="https://cloud.githubusercontent.com/assets/5269116/15424093/a691ac38-1e78-11e6-8b29-10e14d781f95.png">

So both `id-validation-regexp` and `search-url` are annotated with `xref`. But the JSON output the one is in the `database_cross_reference` and the other in the `obo_xref`.
