### ISSUE TITLE
Misleading database attribute field

### ISSUE THREAD

**Issue by tschaka1904** [EBISPOT/OLS#86]
Dear OLS-Team, 

I think that the `database` attribute in `obo_xref` is misleading. For example in [MOD:01603](http://www.ebi.ac.uk/ols/api/ontologies/MOD/terms?obo_id=MOD:01603). The database field has values like: `(14)N -2 (15)N 2`, `C 6 H 12 (15)N 2 O 1`, `K`, `1.99`. I think that the attribute name `database` does not fit.

Best regards,
Max

**Comment by simonjupp** [comment]
As I mentioned in #85 , we try and format the OBO xrefs as they are specified in the file. Unfortunately I have a feeling MOD have the data the wrong way round in the file which is why you are seeing it like this in the OLS. I've let them know so hopefully it can get fixed at source.

**Comment by tschaka1904** [comment]
Cheers Simon! Appreciate your quick and descriptive answers.
