### ISSUE TITLE
type of obo_synonym has changed

### ISSUE THREAD

**Issue by tschaka1904** [EBISPOT/OLS#89]
Hi OLS-Team, 

I've just experienced and issue with the MOD and MI ontology. The way how I implemented the changes, I was expecting for an MI shortlabel having the type `PSI-MI-short`. But this does not apply anymore. Now it is `Unique short label curated by PSI-MI`. This obviously breaks my tests.. 

Has that happened for a reason or is that a bug? 

Max

**Comment by simonjupp** [comment]
"Unique short label curated by PSI-MI" is the correct label for the synonym property. I wasn't get this properly before.

**Comment by tschaka1904** [comment]
I thought so. That was the way how it was done in the old OLS. Thanks.
