### ISSUE TITLE
chmo IRI is invalid

### ISSUE THREAD

**Issue by JKChang2015** [EBISPOT/OLS#98]
Hi,
The IRI/URL of Chemical Methods Ontology is no longer available (http://purl.obolibrary.org/obo/chmo). Could you please help to fix it? 
Thank you.

**Comment by simonjupp** [comment]
Thanks, I've reported this to the CHMO maintainers.

**Comment by cmungall** [comment]
I think this can be closed?

The ontology PURL should be

http://purl.obolibrary.org/obo/chmo.owl

Which resolves (albeit to something with different metadata than what is on OLS, I will make a fresh issue)
